//! Every Rust example the website shows, compiled against the public API.
//!
//! Generated by `build.rs` from `web/src/data/rust-examples.json`; see that
//! script for the rules. The snippets are display code, so lints that would
//! reshape them are off -- the gate is that they compile.
#![allow(warnings, clippy::all, clippy::pedantic, clippy::nursery)]

include!(concat!(env!("OUT_DIR"), "/snippet_check.rs"));

/// A moved or unreadable JSON file compiles an empty module, which would pass
/// silently; in the repository there are always examples to check.
#[test]
fn website_examples_are_compiled() {
    assert!(
        SNIPPETS > 0,
        "web/src/data/rust-examples.json was not found; no website example was compiled"
    );
}
