"""Regression tests for deterministic inventory coverage reporting."""
from copy import deepcopy
import json
from pathlib import Path
import tempfile
import unittest

import coverage_report as report
import interaction_inventory as inventory


class CoverageReportTests(unittest.TestCase):
    def make_inventory(self):
        value = {
            "schema_version": 3,
            "recorded_on": "2026-09-13",
            "upstream": {
                "target_tag": "v3.2.6",
                "target_commit": "target-commit",
            },
            "source_snapshot": {"sha256": "source-snapshot"},
            "gallery_sections": {"button": [{"heading": "Usage"}]},
            "specimens": [
                {
                    "id": "button/primary/press",
                    "component": "Button",
                    "scope": "manual",
                    "status": "verified",
                    "verified_snapshot": "pending",
                    "evidence": {name: [] for name in report.SURFACES},
                },
                {
                    "id": "button/secondary/disabled",
                    "component": "Button",
                    "scope": "manual",
                    "status": "measured-gap",
                    "evidence": {name: [] for name in report.SURFACES},
                },
                {
                    "id": "select/usage",
                    "component": "Select",
                    "scope": "gallery-section",
                    "status": "unreviewed",
                    "evidence": {name: [] for name in report.SURFACES},
                },
            ],
        }
        value["verification_sha256"] = inventory.verification_fingerprint(value)
        # The verified row is intentionally removed from this fixture in the
        # first test; a second test supplies real files for the strict path.
        value["specimens"][0]["status"] = "specified"
        value["verification_sha256"] = inventory.verification_fingerprint(value)
        return value

    def test_counts_and_queues_are_derived_and_sorted(self):
        value = self.make_inventory()
        result = report.build_report(value, Path(tempfile.gettempdir()))
        self.assertEqual(result["totals"], {
            "specimens": 3,
            "verified": 0,
            "outstanding": 3,
            "unobserved": 2,
            "components": 2,
            "gallery_sections": 1,
        })
        self.assertEqual(result["status_counts"]["specified"], 1)
        self.assertEqual(result["status_counts"]["measured-gap"], 1)
        self.assertEqual(result["status_counts"]["unreviewed"], 1)
        self.assertEqual([row["id"] for row in result["unresolved"]], [
            "button/primary/press", "button/secondary/disabled", "select/usage",
        ])
        self.assertEqual(result["last_evidence_commit"], None)
        self.assertEqual(result["evidence_counts"]["all_surfaces"]["specimens_with_evidence"], 0)

    def test_explicit_evidence_commit_is_not_confused_with_upstream_pin(self):
        value = self.make_inventory()
        value["last_evidence_commit"] = "evidence-commit"
        value["verification_sha256"] = inventory.verification_fingerprint(value)
        result = report.build_report(value, Path(tempfile.gettempdir()))
        self.assertEqual(result["last_evidence_commit"], "evidence-commit")
        self.assertTrue(result["last_evidence_commit_recorded"])
        self.assertNotEqual(result["last_evidence_commit"], value["upstream"]["target_commit"])

    def test_verified_specimen_requires_all_current_evidence(self):
        value = self.make_inventory()
        value["specimens"][0]["status"] = "verified"
        with self.assertRaisesRegex(ValueError, "verified evidence"):
            value["verification_sha256"] = inventory.verification_fingerprint(value)
            report.build_report(value, Path(tempfile.gettempdir()))

    def test_fingerprint_mismatch_is_a_known_negative(self):
        value = self.make_inventory()
        value["verification_sha256"] = "stale"
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            report.build_report(value, Path(tempfile.gettempdir()))

    def test_markdown_contains_generated_marker_and_queue_totals(self):
        value = self.make_inventory()
        markdown = report.render_markdown(report.build_report(value, Path(tempfile.gettempdir())))
        self.assertTrue(markdown.startswith("<!-- Generated by .shots/coverage_report.py"))
        self.assertIn("Unobserved/unreviewed", markdown)
        self.assertIn("Measured gaps: **1**", markdown)
        self.assertIn("Last evidence commit: `(none recorded)`", markdown)

    def test_report_json_is_stable(self):
        value = self.make_inventory()
        first = report.build_report(value, Path(tempfile.gettempdir()))
        second = report.build_report(json.loads(json.dumps(value)), Path(tempfile.gettempdir()))
        self.assertEqual(first, second)


if __name__ == "__main__":
    unittest.main()
