import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * Typed reader for the data pipeline's `src/data/catalog.json`.
 *
 * The catalog is generated by another agent and may not exist yet; this
 * loader returns an empty, well-typed catalog instead of throwing so the
 * site builds (and renders an empty component index) either way.
 */

export interface CatalogCategory {
  name: string;
  slug: string;
  components: string[];
}

export interface CatalogComponent {
  slug: string;
  title: string;
  description: string;
  category: string;
  importLine: string;
  shot: string | null;
  shotDark: string | null;
  demos: string[];
  hasReference: boolean;
}

export interface Catalog {
  version: string;
  categories: CatalogCategory[];
  components: Record<string, CatalogComponent>;
}

export interface SidebarGroup {
  label: string;
  links: { href: string; label: string }[];
}

const EMPTY_CATALOG: Catalog = { version: "", categories: [], components: {} };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asStringOrNull(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

function asStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((entry): entry is string => typeof entry === "string")
    : [];
}

function parseComponent(value: unknown): CatalogComponent | null {
  if (!isRecord(value)) return null;
  return {
    slug: asString(value.slug),
    title: asString(value.title),
    description: asString(value.description),
    category: asString(value.category),
    importLine: asString(value.importLine),
    shot: asStringOrNull(value.shot),
    shotDark: asStringOrNull(value.shotDark),
    demos: asStringArray(value.demos),
    hasReference: value.hasReference === true,
  };
}

function parseCategory(value: unknown): CatalogCategory | null {
  if (!isRecord(value)) return null;
  const components = asStringArray(value.components);
  return {
    name: asString(value.name),
    slug: asString(value.slug),
    components,
  };
}

function parseCatalog(raw: unknown): Catalog {
  if (!isRecord(raw)) return EMPTY_CATALOG;

  const components: Record<string, CatalogComponent> = {};
  if (isRecord(raw.components)) {
    for (const [key, value] of Object.entries(raw.components)) {
      const parsed = parseComponent(value);
      if (parsed) components[key] = parsed;
    }
  }

  const categories = Array.isArray(raw.categories)
    ? raw.categories.flatMap((entry) => {
        const parsed = parseCategory(entry);
        return parsed ? [parsed] : [];
      })
    : [];

  return {
    version: asString(raw.version),
    categories,
    components,
  };
}

let cached: Catalog | null = null;

export function getCatalog(): Catalog {
  if (cached) return cached;
  try {
    const file = path.join(process.cwd(), "src", "data", "catalog.json");
    cached = parseCatalog(JSON.parse(readFileSync(file, "utf8")) as unknown);
  } catch {
    cached = EMPTY_CATALOG;
  }
  return cached;
}

/**
 * One sidebar group per catalog category, in catalog order, with each
 * component linking to its `/docs/components/<slug>` page.
 */
export function getComponentSidebarGroups(catalog: Catalog): SidebarGroup[] {
  return catalog.categories
    .map((category) => ({
      label: category.name,
      links: category.components.flatMap((slug) => {
        const component = catalog.components[slug];
        if (!component || !component.slug || !component.title) return [];
        return [{ href: `/docs/components/${component.slug}`, label: component.title }];
      }),
    }))
    .filter((group) => group.links.length > 0);
}
