[package]
name = "herogpui"
description = "Beautiful, fast and modern cross-platform Rust GPUI UI library — HeroUI for GPUI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
gpui.workspace = true
herogpui-core.workspace = true
herogpui-theme.workspace = true
herogpui-components.workspace = true

[lints]
workspace = true
