[package]
name = "herogpui-gallery"
description = "HeroGPUI component gallery and documentation showcase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "herogpui-gallery"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
prettyplease.workspace = true
syn.workspace = true
herogpui-core.workspace = true
herogpui-theme.workspace = true
herogpui-components = { workspace = true, features = ["gallery-source"] }
herogpui.workspace = true

[lints]
workspace = true
