[package]
name = "herogpui-core"
description = "Core utilities and shared types for HeroGPUI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
gpui.workspace = true

[lints]
workspace = true
