//! buttons reference metadata.

use super::*;

const BUTTON_REQUIRED_PARTS: &[&str] = &[
    // v3 exposes one root slot rather than a compound button anatomy.
    "Button",
];

const BUTTON_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Button",
        prop: "variant",
        ty: "'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger'",
        default: "'primary'",
        description: "Visual style variant; the pinned stylesheet also defines danger-soft.",
        rust_owner: "Button",
        rust: "variant(Variant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "size",
        ty: "'sm' | 'md' | 'lg'",
        default: "'md'",
        description: "Size of the button.",
        rust_owner: "Button",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "fullWidth",
        ty: "boolean",
        default: "false",
        description: "Whether the button fills its container.",
        rust_owner: "Button",
        rust: "full_width(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables pointer and keyboard presses and removes the tab stop.",
        rust_owner: "Button",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "isPending",
        ty: "boolean",
        default: "false",
        description: "Blocks presses and hover while retaining focusability.",
        rust_owner: "Button",
        rust: "is_pending(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "isIconOnly",
        ty: "boolean",
        default: "false",
        description: "Uses the size-specific square icon control geometry.",
        rust_owner: "Button",
        rust: "is_icon_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Button",
        prop: "onPress",
        ty: "(e: PressEvent) => void",
        default: "—",
        description: "Pointer and keyboard presses are supported, but the callback receives GPUI's ClickEvent rather than React Aria's PressEvent.",
        rust_owner: "Button",
        rust: "on_press(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Button",
        prop: "children",
        ty: "ReactNode | (values: ButtonRenderProps) => ReactNode",
        default: "—",
        description: "Text, arbitrary children and state-driven content are supported through separate builders.",
        rust_owner: "Button",
        rust: "label(value) / child(element) / content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Button",
        prop: "render",
        ty: "DOMRenderFunction<..., ButtonRenderProps>",
        default: "—",
        description: "Overrides the browser DOM root.",
        rust_owner: "Button",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isPending",
        ty: "boolean",
        default: "—",
        description: "Pending state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Current pressed state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isHovered",
        ty: "boolean",
        default: "—",
        description: "Current hover state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Current focus state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isFocusVisible",
        ty: "boolean",
        default: "—",
        description: "Keyboard-visible focus state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ButtonRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disabled state supplied to custom content.",
        rust_owner: "Button",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
];

const BUTTON_PARTS: &[PartDoc] = &[PartDoc {
    name: "Button",
    slot: "button",
    description: "Focusable root that owns content, visual variant and interaction state.",
    rust_owner: "Button",
    status: ImplementationStatus::Implemented,
}];

const BUTTON_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".button:hover / [data-hovered=\"true\"]",
        description: "Variant-specific hover background and render state.",
        rust: "anim::hover_fade + InteractiveState::is_hovered",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".button:active / [data-pressed=\"true\"]",
        description: "Size-specific scale and render state for pointer or keyboard press.",
        rust: "anim::pressed + InteractiveState::is_pressed",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".button:focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus displays the status-focused ring.",
        rust: "tab_stop_handle + ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".button:disabled / [aria-disabled=\"true\"]",
        description: "Disabled buttons are dimmed, inert and removed from the tab order.",
        rust: "is_disabled + disabled_opacity",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pending",
        selector: ".button[data-pending=\"true\"]",
        description: "Pending buttons are dimmed and inert but remain focusable.",
        rust: "is_pending + disabled_opacity + interactive=false",
        status: ImplementationStatus::Implemented,
    },
];

const BUTTON_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".button",
        value: "inline-flex h-10 md:h-9 w-fit items-center justify-center gap-2 rounded-3xl px-4 text-sm font-medium",
        description: "Base desktop geometry, typography and 24px rounded control surface.",
        rust: "flex + h(36px) + gap(8px) + px(16px) + control_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--primary",
        value: "accent / accent-hover / accent-foreground",
        description: "Solid accent variant tokens.",
        rust: "Variant::Primary + colors.accent",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--secondary",
        value: "default / default-hover / accent-soft-foreground",
        description: "Neutral filled surface with accent-colored foreground.",
        rust: "Variant::Secondary + colors.default + colors.accent.soft_foreground(colors.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--tertiary",
        value: "default / default-hover / currentColor",
        description: "Neutral default surface that preserves the inherited foreground.",
        rust: "Variant::Tertiary + colors.default + colors.foreground",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--ghost",
        value: "transparent / default hover / default-foreground",
        description: "Transparent low-emphasis variant with the neutral foreground.",
        rust: "Variant::Ghost + colors.default",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--outline",
        value: "transparent / 60% default hover / default-foreground / border-border",
        description: "Outlined variant with the pinned translucent hover fill.",
        rust: "Variant::Outline + colors.default.color.alpha(0.6) + colors.border",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--danger / .button--danger-soft",
        value: "danger palettes and their hover/foreground tokens",
        description: "Solid and soft danger variants from the pinned stylesheet.",
        rust: "Variant::Danger/DangerSoft + colors.danger",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--sm / .button--md / .button--lg",
        value: "desktop 32px / 36px / 40px; pressed scale 0.98 / 0.97 / 0.96",
        description: "Size-specific control metrics and press geometry.",
        rust: "Size + PRESSED_SCALE_SUBTLE/PRESSED_SCALE/PRESSED_SCALE_FIRM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--icon-only",
        value: "desktop width 32px / 36px / 40px with no padding",
        description: "Square icon-only geometry follows the selected size.",
        rust: "is_icon_only + icon_control_size",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button--full-width",
        value: "w-full",
        description: "Fills the available width.",
        rust: "full_width(true) + w_full",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button svg",
        value: "responsive 16px/20px icon size with pointer-events-none and alignment margins",
        description: "Caller-owned GPUI children do not receive selector-driven icon sizing or margins.",
        rust: "child(element)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".button background-color transition",
        value: "100ms ease-out; motion-reduce transition-none",
        description: "Hover colors interpolate on a listener-free child fill and reduced motion swaps directly.",
        rust: "anim::hover_fade + TRANSITION_MS + Curve::Out",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".button transform / box-shadow transitions",
        value: "transform 250ms ease-smooth; box-shadow 100ms ease-out; motion-reduce transition-none",
        description: "Press geometry and focus shadow reach the correct endpoints, but GPUI applies both without property interpolation.",
        rust: "anim::pressed + ring_if_focused",
        status: ImplementationStatus::Partial,
    },
];

pub(super) const BUTTON: ReferenceMetadata = ReferenceMetadata {
    page: "Button",
    import_line: "use herogpui::prelude::{Button, Size, Variant};",
    source_module: "button",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(buttons)/button.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/button/button.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.21.0/packages/react-aria-components/src/Button.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/button.css",
    required_parts: BUTTON_REQUIRED_PARTS,
    api: BUTTON_API,
    parts: BUTTON_PARTS,
    states: BUTTON_STATES,
    styling: BUTTON_STYLING,
};

const BUTTON_GROUP_REQUIRED_PARTS: &[&str] = &["ButtonGroup", "ButtonGroup.Separator"];

const BUTTON_GROUP_API: &[ApiDoc] = &[
    ApiDoc { owner: "ButtonGroup", prop: "id", ty: "string", default: "—", description: "Optional GPUI identity. A named group reports role=group; an unnamed one produces no AccessKit node.", rust_owner: "ButtonGroup", rust: "id(ElementId)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "variant", ty: "'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'danger' | 'danger-soft'", default: "—", description: "Supplies a default variant to direct Button members while preserving explicit child variants; unset members keep Button's own default. The pinned context type is ButtonProps['variant'], so all seven values inherit.", rust_owner: "ButtonGroup", rust: "variant(Variant) + Button::group_defaults", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "size", ty: "'sm' | 'md' | 'lg'", default: "—", description: "Supplies a default size to direct Button members while preserving explicit child sizes; unset members keep Button's own default.", rust_owner: "ButtonGroup", rust: "size(Size) + Button::group_defaults", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "orientation", ty: "horizontal | vertical", default: "horizontal", description: "Chooses row or column layout and the corresponding joined-edge geometry.", rust_owner: "ButtonGroup", rust: "orientation(Orientation)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "fullWidth", ty: "boolean", default: "false", description: "The group root fills its parent, and each typed member resolves pinned button.tsx's finalFullWidth = fullWidth ?? context.fullWidth: unset members inherit, an explicit child false/true overrides, and only resolved-full members take an equal stretch slot.", rust_owner: "ButtonGroup", rust: "full_width(bool) + Button::group_defaults", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables direct typed members unless a child explicitly sets isDisabled=false, matching pinned context precedence.", rust_owner: "ButtonGroup", rust: "is_disabled(bool) + Button::group_defaults", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ButtonGroup", prop: "className", ty: "string", default: "—", description: "Browser classes are unavailable.", rust_owner: "ButtonGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ButtonGroup", prop: "children", ty: "ReactNode", default: "—", description: "button(Button) preserves typed direct-child inheritance and joined edges; arbitrary ParentElement children are rendered but cannot receive that context after type erasure, so they take no fullWidth stretch slot either.", rust_owner: "ButtonGroup", rust: "button(Button) / child(AnyElement)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "ButtonGroup.Separator", prop: "className", ty: "string", default: "—", description: "The port synthesizes pinned separators through a composition flag rather than accepting browser classes.", rust_owner: "ButtonGroup", rust: "separators(bool)", status: ImplementationStatus::Partial },
];

const BUTTON_GROUP_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "ButtonGroup",
        slot: "button-group",
        description: "Orientation, width, direct-child defaults, and joined-edge owner.",
        rust_owner: "ButtonGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "ButtonGroup.Separator",
        slot: "button-group-separator",
        description: "Optional hairline drawn by ButtonGroup::separators(bool) before each member after the first; v3 composes one child per member, so per-member placement is not expressible.",
        rust_owner: "ButtonGroup",
        status: ImplementationStatus::Partial,
    },
];

const BUTTON_GROUP_STATES: &[StateDoc] = &[
    StateDoc { state: "Horizontal", selector: ".button-group--horizontal", description: "Members form a row with start/end outer corners.", rust: "Orientation::Horizontal + GroupEdge", status: ImplementationStatus::Implemented },
    StateDoc { state: "Vertical", selector: ".button-group--vertical", description: "Members form a column with top/bottom outer corners.", rust: "Orientation::Vertical + GroupEdge", status: ImplementationStatus::Implemented },
    StateDoc { state: "Full width", selector: ".button-group--full-width", description: "The group fills its parent; each member that resolves fullWidth ?? context.fullWidth shares the width equally, and an explicit child false frees its share.", rust: "full_width + w_full + resolved member flex_1 slots", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled", selector: "ButtonGroup isDisabled context", description: "Unset children inherit disabled; an explicit child false overrides it.", rust: "Button::group_defaults precedence", status: ImplementationStatus::Implemented },
    StateDoc { state: "Pressed", selector: ".button-group .button[data-pressed=true]", description: "Grouped buttons suppress the standalone press scale.", rust: "Button group_edge skips anim::pressed", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focus visible", selector: ".button-group .button[data-focus-visible=true]", description: "The focus ring is present, but GPUI has no z-index elevation equivalent for overlapping adjacent controls.", rust: "Button ring_if_focused without z-10", status: ImplementationStatus::Partial },
];

const BUTTON_GROUP_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".button-group", value: "inline-flex h-auto items-center justify-center gap-0", description: "Flex alignment and zero gap match; GPUI has no inline-flex display mode and relies on the parent layout for intrinsic width.", rust: "div flex items_center justify_center", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".button-group--horizontal / --vertical", value: "flex-row / flex-col", description: "Both orientations match.", rust: "Orientation + flex_row/flex_col", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".button-group .button edge radii", value: "3xl outer corners; middle corners square; lone member fully rounded", description: "Only the first/last external corners retain the 24px Button radius, and a lone member keeps the full radius.", rust: "GroupEdge + group_radius", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".button-group .button pressed", value: "transform: none", description: "Grouped members skip Button's pressed-scale wrapper.", rust: "group_edge.is_none() gate", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".button-group focused button", value: "z-10", description: "The outward focus ring renders, but GPUI provides no matching local z-index elevation.", rust: "ring_if_focused", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".button-group__separator", value: "1px by 50%; -1px leading inset; currentColor 15%; radius-sm", description: "Horizontal and vertical separator geometry and opacity match; bg-current resolves per member, so each hairline takes the resolved variant foreground of the member drawn in its slot and a type-erased child's slot falls back to the group variant. The inert opacity transition has no runtime-changing endpoint in this composition.", rust: "separators + separator_variant + absolute hairline", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".button-group outline border handling", value: "--horizontal outline members: :first-child border-e-0, :last-child border-s-0, middle border-x-0; --vertical mirrors with border-b-0, border-t-0, border-y-0", description: "Each outline member drops exactly the border sides its group position shares with a neighbour, resolved per GroupEdge and orientation; a lone member is :first-child:last-child so its whole stacking-axis border collapses, and a member outside a group keeps the full border.", rust: "Button outline + collapsed_border_sides(GroupEdge, vertical)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".button-group--full-width", value: "w-full; member Buttons stretch via finalFullWidth = fullWidth ?? context.fullWidth (button--full-width)", description: "The group root and each resolved-full member stretch; an explicit child fullWidth=false overrides the context and hugs content, matching pinned button.tsx precedence.", rust: "full_width + Button::group_defaults + per-member flex_1", status: ImplementationStatus::Implemented },
];

pub(super) const BUTTON_GROUP: ReferenceMetadata = ReferenceMetadata {
    page: "ButtonGroup",
    import_line: "use herogpui::components::button_group::ButtonGroup;",
    source_module: "button_group",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(buttons)/button-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/button-group/button-group.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/tests/components/button-group/button-group.test.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/button-group.css",
    required_parts: BUTTON_GROUP_REQUIRED_PARTS,
    api: BUTTON_GROUP_API,
    parts: BUTTON_GROUP_PARTS,
    states: BUTTON_GROUP_STATES,
    styling: BUTTON_GROUP_STYLING,
};

const CLOSE_BUTTON_REQUIRED_PARTS: &[&str] = &[
    // The default icon is a source-declared data-slot and can be replaced.
    "CloseButton",
    "CloseButton.Icon",
];

const CLOSE_BUTTON_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "CloseButton",
        prop: "variant",
        ty: "'default'",
        default: "'default'",
        description: "The sole visual variant exposed by v3.",
        rust_owner: "CloseButton",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CloseButton",
        prop: "children",
        ty: "ReactNode | (values: CloseButtonRenderProps) => ReactNode",
        default: "<CloseIcon />",
        description:
            "Replaces the default glyph with an element or an interactive-state render function.",
        rust_owner: "CloseButton",
        rust: "content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "CloseButton",
        prop: "onPress",
        ty: "() => void",
        default: "—",
        description: "Handler called when the enabled button is pressed.",
        rust_owner: "CloseButton",
        rust: "on_press(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CloseButton",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Whether the close button is disabled.",
        rust_owner: "CloseButton",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "React Aria Button Props",
        prop: "aria-label",
        ty: "string",
        default: "'Close'",
        description: "Accessible label; gpui-pre 0.3.3 has no accessibility tree surface.",
        rust_owner: "CloseButton",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "React Aria Button Props",
        prop: "aria-labelledby",
        ty: "string",
        default: "—",
        description: "ID of the labelling element; unavailable without an accessibility tree.",
        rust_owner: "CloseButton",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "React Aria Button Props",
        prop: "aria-describedby",
        ty: "string",
        default: "—",
        description: "ID of the describing element; unavailable without an accessibility tree.",
        rust_owner: "CloseButton",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CloseButtonRenderProps",
        prop: "isHovered",
        ty: "boolean",
        default: "—",
        description: "Current enabled hover state supplied to custom content.",
        rust_owner: "CloseButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CloseButtonRenderProps",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Current enabled press state supplied to custom content.",
        rust_owner: "CloseButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CloseButtonRenderProps",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Whether the button owns focus.",
        rust_owner: "CloseButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CloseButtonRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Whether the button is disabled.",
        rust_owner: "CloseButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
];

const CLOSE_BUTTON_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "CloseButton",
        slot: "close-button",
        description: "Focusable root button and owner of disabled, hover, press and focus state.",
        rust_owner: "CloseButton",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "CloseButton.Icon",
        slot: "close-button-icon",
        description:
            "Built-in close glyph; icon(element) or content(render) replaces it in the port.",
        rust_owner: "CloseButton",
        status: ImplementationStatus::Implemented,
    },
];

const CLOSE_BUTTON_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".close-button:hover / [data-hovered=\"true\"]",
        description: "Enabled buttons use the default-hover background and report hover to render content.",
        rust: "hover(colors.default.hover()) + InteractiveState::is_hovered",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".close-button:active / [data-pressed=\"true\"]",
        description: "Pressed state reaches custom content; the root bounds shrink to a centered 93%, but fixed child content does not scale with the CSS transform.",
        rust: "active centered root-bounds shrink + InteractiveState::is_pressed",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".close-button:focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus draws the shared status-focused ring.",
        rust: "tab_stop_handle + ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".close-button:disabled / [aria-disabled=\"true\"]",
        description: "Disabled buttons are dimmed, removed from the tab order and expose no hover, press or activation.",
        rust: "is_disabled + disabled_opacity + interaction gates",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pending",
        selector: ".close-button[data-pending=\"true\"]",
        description: "The pinned stylesheet supports status-pending, but CloseButton exposes no pending prop.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const CLOSE_BUTTON_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".close-button",
        value: "relative isolate inline-flex h-6 w-6 shrink-0 origin-center items-center justify-center rounded-xl p-1 select-none no-highlight",
        description: "Base 24px square and alignment; GPUI has no DOM isolation, selection, highlight or transform-origin controls.",
        rust: "flex + size(px(24.)) + p(px(4.)) + items_center + justify_center",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".close-button cursor",
        value: "cursor: var(--cursor-interactive)",
        description: "Enabled close buttons use the interactive pointer cursor.",
        rust: "cursor_pointer()",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".close-button",
        value: "rounded-xl",
        description: "Twelve-pixel root corner radius.",
        rust: "small_radius(cx)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".close-button--default",
        value: "bg-default text-muted",
        description: "Default surface and foreground semantic tokens.",
        rust: "colors.default.color + colors.muted",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".close-button--default:hover / [data-hovered=\"true\"]",
        value: "bg-default-hover",
        description: "Hover surface uses the pinned default-hover role token.",
        rust: "hover(colors.default.hover())",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".close-button--default:active / [data-pressed=\"true\"]",
        value: "transform: scale(0.93)",
        description: "The root bounds shrink to 93% about the center without moving neighboring layout; fixed child content remains unscaled.",
        rust: "active centered root-bounds shrink",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".close-button svg",
        value: "size-4 shrink-0 self-center -mx-0.5 my-0.5 pointer-events-none",
        description: "The built-in glyph is 16px; selector-specific margins and pointer behavior are unavailable for arbitrary replacement children.",
        rust: "svg().size(px(16.)) / icon(element)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".close-button transitions",
        value: "transform 250ms ease-out-quart; color/box-shadow 150ms ease-out; background 100ms ease-out; motion-reduce none",
        description: "The port changes hover, press and focus styling on a frame without these interpolation timelines.",
        rust: "immediate hover/active/ring styles",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".close-button:focus-visible",
        value: "status-focused",
        description: "Shared focus-visible ring and offset treatment.",
        rust: "ring_if_focused(offset = true)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".close-button:disabled / [aria-disabled=\"true\"]",
        value: "status-disabled",
        description: "The port matches opacity and interaction semantics through explicit gates rather than DOM pointer-events.",
        rust: "disabled_opacity + listener/callback/tab-stop gates",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".close-button[data-pending=\"true\"]",
        value: "status-pending",
        description: "Pending styling exists upstream but has no local state or builder.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

pub(super) const CLOSE_BUTTON: ReferenceMetadata = ReferenceMetadata {
    page: "CloseButton",
    import_line: "use herogpui::components::close_button::CloseButton;",
    source_module: "close_button",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(buttons)/close-button.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/close-button/close-button.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/close-button.css",
    required_parts: CLOSE_BUTTON_REQUIRED_PARTS,
    api: CLOSE_BUTTON_API,
    parts: CLOSE_BUTTON_PARTS,
    states: CLOSE_BUTTON_STATES,
    styling: CLOSE_BUTTON_STYLING,
};

const TOGGLE_BUTTON_REQUIRED_PARTS: &[&str] = &[
    "ToggleButton",
    "ToggleButtonGroup",
    "ToggleButtonGroup.Separator",
];

const TOGGLE_BUTTON_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "ToggleButton",
        prop: "variant",
        ty: "'default' | 'ghost'",
        default: "'default'",
        description: "Visual style variant",
        rust_owner: "ToggleButton",
        rust: "variant(ToggleVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "size",
        ty: "'sm' | 'md' | 'lg'",
        default: "'md'",
        description: "Size of the toggle button",
        rust_owner: "ToggleButton",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "isIconOnly",
        ty: "boolean",
        default: "false",
        description: "Whether the button contains only an icon",
        rust_owner: "ToggleButton",
        rust: "is_icon_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Controlled selected state",
        rust_owner: "ToggleButton",
        rust: "is_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "defaultSelected",
        ty: "boolean",
        default: "false",
        description: "Default selected state (uncontrolled)",
        rust_owner: "ToggleButton",
        rust: "default_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Whether the toggle button is disabled",
        rust_owner: "ToggleButton",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "onChange",
        ty: "(isSelected: boolean) => void",
        default: "—",
        description: "Handler called when selection changes",
        rust_owner: "ToggleButton",
        rust: "on_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "onPress",
        ty: "(e: PressEvent) => void",
        default: "—",
        description: "Handler called when the button is pressed",
        rust_owner: "ToggleButton",
        rust: "on_press(event)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButton",
        prop: "children",
        ty: "React.ReactNode | (values: ToggleButtonRenderProps) => React.ReactNode",
        default: "—",
        description: "Button content or render prop",
        rust_owner: "ToggleButton",
        rust: "label(value) / content(render) / child(element)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Whether the button is currently selected",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Whether the button is currently pressed",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isHovered",
        ty: "boolean",
        default: "—",
        description: "Whether the button is hovered",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Whether the button is focused",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isFocusVisible",
        ty: "boolean",
        default: "—",
        description: "Whether the button should show focus indicator",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Whether the button is disabled",
        rust_owner: "ToggleButton",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "\"single\"",
        description: "Whether one or multiple buttons can be selected",
        rust_owner: "ToggleButtonGroup",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Controlled selection state; the port accepts SharedString keys only.",
        rust_owner: "ToggleButtonGroup",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description:
            "Default selected keys (uncontrolled); the port accepts SharedString keys only.",
        rust_owner: "ToggleButtonGroup",
        rust: "default_selected_keys(keys)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "onSelectionChange",
        ty: "(keys: Set<Key>) => void",
        default: "—",
        description: "Called when selection changes; the port reports SharedString keys only.",
        rust_owner: "ToggleButtonGroup",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "disallowEmptySelection",
        ty: "boolean",
        default: "false",
        description: "Prevents clearing all selections",
        rust_owner: "ToggleButtonGroup",
        rust: "disallow_empty_selection(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"horizontal\"",
        description: "Layout direction",
        rust_owner: "ToggleButtonGroup",
        rust: "orientation(SelectionOrientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "size",
        ty: "\"sm\" | \"md\" | \"lg\"",
        default: "\"md\"",
        description: "Size propagated to child ToggleButtons",
        rust_owner: "ToggleButtonGroup",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "isDetached",
        ty: "boolean",
        default: "false",
        description: "Whether buttons are visually separated with gaps",
        rust_owner: "ToggleButtonGroup",
        rust: "is_detached(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "fullWidth",
        ty: "boolean",
        default: "false",
        description: "Whether the group fills available width",
        rust_owner: "ToggleButtonGroup",
        rust: "full_width(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables all buttons unless a child explicitly overrides the context.",
        rust_owner: "ToggleButtonGroup",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ToggleButtonGroup",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes",
        rust_owner: "ToggleButtonGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ToggleButtonGroup.Separator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes",
        rust_owner: "ToggleButtonGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const TOGGLE_BUTTON_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "ToggleButton",
        slot: "toggle-button",
        description: "Focusable toggle root that owns selected, press and disabled state.",
        rust_owner: "ToggleButton",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "ToggleButtonGroup",
        slot: "toggle-button-group",
        description: "Selection and layout root; separators are explicit composition requested with separators(true).",
        rust_owner: "ToggleButtonGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "ToggleButtonGroup.Separator",
        slot: "toggle-button-group-separator",
        description: "Optional explicit divider composition; the port uses separators(true), and custom className is unavailable.",
        rust_owner: "ToggleButtonGroup",
        status: ImplementationStatus::Partial,
    },
];

const TOGGLE_BUTTON_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Selected",
        selector: ".toggle-button[data-selected=\"true\"]",
        description: "Accent-soft background and foreground show the selected state.",
        rust: "is_selected + colors.accent.soft()",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ".toggle-button:hover / [data-hovered=\"true\"]",
        description: "Variant-specific hover background, including selected accent-soft-hover.",
        rust: "hover + InteractiveState::is_hovered",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Pressed",
        selector: ".toggle-button:active / [data-pressed=\"true\"]",
        description: "Pressed feedback applies the size-specific scale and pressed background.",
        rust: "anim::pressed + InteractiveState::is_pressed",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".toggle-button:focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus shows the status-focused ring.",
        rust: "tab_stop_handle + ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".toggle-button:disabled / [aria-disabled=\"true\"]",
        description: "Disabled toggles are dimmed, inert and removed from the tab order.",
        rust: "is_disabled + disabled_opacity",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Controlled selection",
        selector: "selectedKeys",
        description: "The caller owns the selected key set and receives selection callbacks.",
        rust: "selected_keys(keys) + util::controlled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Uncontrolled selection",
        selector: "defaultSelectedKeys",
        description: "The group owns its selected key set after the initial seed.",
        rust: "default_selected_keys(keys) + util::controlled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Single selection",
        selector: "selectionMode=\"single\"",
        description: "Selecting a member replaces the previous selection.",
        rust: "selection_mode(SelectionMode::Single)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Multiple selection",
        selector: "selectionMode=\"multiple\"",
        description: "Members can be selected independently.",
        rust: "selection_mode(SelectionMode::Multiple)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disallow empty selection",
        selector: "disallowEmptySelection",
        description: "The last selected member cannot be cleared in single-selection mode.",
        rust: "disallow_empty_selection(bool)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Horizontal group",
        selector: ".toggle-button-group--horizontal",
        description: "Members flow along the horizontal axis.",
        rust: "orientation(SelectionOrientation::Horizontal)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical group",
        selector: ".toggle-button-group--vertical",
        description: "Members stack along the vertical axis.",
        rust: "orientation(SelectionOrientation::Vertical)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Full width group",
        selector: ".toggle-button-group--full-width",
        description: "The group fills its parent and stretches each member.",
        rust: "full_width(true) + child slots flex_1",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Attached group",
        selector: ".toggle-button-group .toggle-button",
        description: "Adjacent members share an edge and keep only the outer corners rounded.",
        rust: "group_edge + group_radius_any",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Detached group",
        selector: ".toggle-button-group--detached",
        description: "Members regain full radii and are separated by a 4px gap.",
        rust: "is_detached(true)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Group pressed",
        selector: ".toggle-button-group .toggle-button[data-pressed=\"true\"]",
        description: "Attached members do not scale and therefore cannot open gaps at the seam.",
        rust: "is_grouped gates anim::pressed",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Group focus visible",
        selector: ".toggle-button-group .toggle-button[data-focus-visible=\"true\"]",
        description:
            "The port removes the outer offset but GPUI has no inset box-shadow equivalent.",
        rust: "ring_if_focused(offset = false)",
        status: ImplementationStatus::Partial,
    },
];

const TOGGLE_BUTTON_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".toggle-button",
        value: "inline-flex h-10 md:h-9 w-fit items-center justify-center gap-2 rounded-3xl px-4 text-sm font-medium",
        description: "Base toggle geometry, typography and rounded control surface.",
        rust: "flex + h(36px) + gap(px(8.)) + px(16.) + control_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button",
        value: "no border",
        description: "The v3 toggle has no border; selected state uses a fill and focus uses a ring.",
        rust: "no .border_1()",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--toggle-button-bg / --toggle-button-fg",
        value: "--default / currentColor; hover and pressed use --default-hover",
        description: "Default unselected tokens, with the ghost variant supplying transparent background.",
        rust: "ToggleVariant::Default/Ghost + colors.default",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--toggle-button-bg-selected / --toggle-button-fg-selected",
        value: "--accent-soft / --accent-soft-foreground; hover and pressed --accent-soft-hover",
        description: "Selected toggles use the accent-soft palette rather than the solid accent fill.",
        rust: "is_selected + colors.accent.soft/soft_foreground/soft_hover",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--default",
        value: "--default background, --default-hover hover/pressed",
        description: "Filled default variant token overrides.",
        rust: "ToggleVariant::Default",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--ghost",
        value: "transparent background; --default hover/pressed; --default-foreground text",
        description: "Low-emphasis ghost variant token overrides.",
        rust: "ToggleVariant::Ghost",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--sm",
        value: "h-9 md:h-8 px-3; pressed scale(0.98)",
        description: "Small desktop metrics and the subtle size-specific press scale.",
        rust: "Size::Sm + PRESSED_SCALE_SUBTLE",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--md",
        value: "default size; pressed scale(0.97)",
        description: "Medium is the base size and uses the standard press scale.",
        rust: "Size::Md + PRESSED_SCALE",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--lg",
        value: "h-11 md:h-10 text-base; pressed scale(0.96)",
        description: "Large desktop height, typography, default horizontal padding and firm press scale.",
        rust: "Size::Lg + PRESSED_SCALE_FIRM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--icon-only",
        value: "w-10 p-0 md:w-9",
        description: "Square medium icon-only control.",
        rust: "is_icon_only + width(height)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button--icon-only.toggle-button--sm / --lg",
        value: "w-9 md:w-8 / w-11 md:w-10",
        description: "Small and large icon-only square sizes.",
        rust: "is_icon_only + size-specific height",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button svg",
        value: "size-5 with responsive size-4 and small vertical margins",
        description: "Built-in SVG icon sizing and alignment; arbitrary child elements are accepted by the port without this selector-specific treatment.",
        rust: "child(element)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".toggle-button",
        value: "transform 250ms ease-smooth; background-color/box-shadow 100ms ease-out; motion-reduce none",
        description: "v3 transitions press geometry and color; the port applies the geometry in one frame and does not interpolate the color or press ramp.",
        rust: "anim::pressed + immediate hover/background",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group",
        value: "inline-flex h-auto w-fit items-center justify-center gap-0",
        description: "Connected group container.",
        rust: "flex + items_center + justify_center + gap(px(0.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group--horizontal / --vertical",
        value: "flex-row / flex-col",
        description: "Orientation-controlled group axis.",
        rust: "orientation(SelectionOrientation)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group--full-width",
        value: "w-full; child buttons flex-1",
        description: "Full-width group and equal-width member slots.",
        rust: "full_width(true) + slot.flex_1",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group .toggle-button",
        value: "rounded-none; outer 3xl corners by edge",
        description: "Attached members merge into one control while retaining the group perimeter radius.",
        rust: "group_edge + group_radius_any",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group .toggle-button:active",
        value: "transform: none",
        description: "Attached members suppress their individual press scale.",
        rust: "if !is_grouped { anim::pressed(...) }",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group .toggle-button:focus-visible",
        value: "ring-inset; --tw-ring-offset-width: 0px",
        description: "The port removes the offset seam but cannot draw GPUI's shadow ring inset.",
        rust: "ring_if_focused(offset = false)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group__separator",
        value: "absolute rounded-sm bg-current opacity-15; pointer-events-none",
        description: "The port uses a fixed foreground-derived color rather than each member's currentColor.",
        rust: "absolute + foreground.alpha(0.15) + hairline_radius",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group__separator",
        value: "horizontal: start -1px, top 25%, 1px x 50%; vertical: start 25%, top -1px, 50% x 1px",
        description: "Orientation-specific divider geometry.",
        rust: "separator slot geometry in ToggleButtonGroup::render",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group__separator",
        value: "opacity 150ms ease-smooth; motion-reduce none",
        description: "v3 fades separator opacity; the port draws the correct static geometry without that transition.",
        rust: "static separator div",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".toggle-button-group--detached",
        value: "gap-1; each button rounded-3xl; separators display-none",
        description: "Detached groups separate members, restore full radii and hide dividers.",
        rust: "is_detached(true) + gap(px(4.)) + GroupEdge::Only",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const TOGGLE_BUTTON: ReferenceMetadata = ReferenceMetadata {
    page: "ToggleButton",
    import_line: "use herogpui::components::toggle_button::{ToggleButton, ToggleButtonGroup};",
    source_module: "toggle_button",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(buttons)/toggle-button.mdx + https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(buttons)/toggle-button-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/toggle-button/toggle-button.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/toggle-button-group/toggle-button-group.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/toggle-button.css + https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/toggle-button-group.css",
    required_parts: TOGGLE_BUTTON_REQUIRED_PARTS,
    api: TOGGLE_BUTTON_API,
    parts: TOGGLE_BUTTON_PARTS,
    states: TOGGLE_BUTTON_STATES,
    styling: TOGGLE_BUTTON_STYLING,
};
