//! collections reference metadata.

use super::*;

const DROPDOWN_REQUIRED_PARTS: &[&str] = &[
    "Dropdown",
    "Dropdown.Trigger",
    "Dropdown.Popover",
    "Dropdown.Menu",
    "Dropdown.Section",
    "Dropdown.Item",
    "Dropdown.ItemIndicator",
    "Dropdown.SubmenuIndicator",
    "Dropdown.SubmenuTrigger",
];

const DROPDOWN_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Dropdown",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the open state of the menu (controlled).",
        rust_owner: "Dropdown",
        rust: "is_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "defaultOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the default open state of the menu (uncontrolled).",
        rust_owner: "Dropdown",
        rust: "default_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "onOpenChange",
        ty: "(isOpen: boolean) => void",
        default: "—",
        description: "Handler called when the open state changes.",
        rust_owner: "Dropdown",
        rust: "on_open_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "trigger",
        ty: "\"press\" | \"longPress\"",
        default: "\"press\"",
        description: "The type of interaction that triggers the menu.",
        rust_owner: "Dropdown",
        rust: "trigger(DropdownTrigger)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Dropdown content.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the trigger.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Trigger content or a render function.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "placement",
        ty: "PopoverPlacement",
        default: "\"bottom\"",
        description: "Placement relative to the measured trigger. All eight placements flip to the side with more room when the preferred side cannot fit, keeping a 12px cross-axis viewport inset with the scroller capped to the available height.",
        rust_owner: "Dropdown",
        rust: "placement(DropdownPlacement)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the popover.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Content children rendered in the popover.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\" | \"none\"",
        default: "\"none\"",
        description: "Whether single or multiple selection is enabled.",
        rust_owner: "Menu",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "default_selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when the selection changes.",
        rust_owner: "Menu",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items.",
        rust_owner: "Menu",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onAction",
        ty: "(key: Key) => void",
        default: "—",
        description: "Handler called when an item is activated.",
        rust_owner: "Menu",
        rust: "on_action(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the menu.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Menu content.",
        rust_owner: "Menu",
        rust: "new(id, items)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "—",
        description: "Selection mode for items within this section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when section selection changes.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items in the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Section content.",
        rust_owner: "Menu",
        rust: "SectionLabel + items",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "id",
        ty: "Key",
        default: "—",
        description: "Unique identifier for the item.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "textValue",
        ty: "string",
        default: "—",
        description: "Text content used for typeahead.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "variant",
        ty: "\"default\" | \"danger\"",
        default: "\"default\"",
        description: "Visual variant of the item.",
        rust_owner: "MenuItem",
        rust: "danger()",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Item content or a render function.",
        rust_owner: "Menu",
        rust: "item_content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "type",
        ty: "\"checkmark\" | \"dot\"",
        default: "\"checkmark\"",
        description: "Type of selection indicator to display.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the indicator.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom indicator content or render function.",
        rust_owner: "Menu",
        rust: "indicator_content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "indicator_content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "—",
        description: "Documented render state, but pinned HeroUI forwards a React Aria state that does not emit it.",
        rust_owner: "Menu",
        rust: "indicator_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item has focus.",
        rust_owner: "Menu",
        rust: "item_content(state.is_focused)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is disabled.",
        rust_owner: "Menu",
        rust: "item_content(state.is_disabled)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is being pressed.",
        rust_owner: "Menu",
        rust: "item_content(state.is_pressed)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu indicator.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom submenu indicator content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu trigger.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Submenu trigger content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Dropdown",
        slot: "root",
        description:
            "MenuTrigger wrapper that owns open state and composes the trigger and popover.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Trigger",
        slot: "dropdown-trigger",
        description: "Button or custom element that opens the menu.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Popover",
        slot: "dropdown-popover",
        description: "Floating panel positioned relative to the trigger.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Menu",
        slot: "dropdown-menu",
        description: "Scrollable menu container and selection owner.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Section",
        slot: "menu-section",
        description: "Grouped menu items with an optional header.",
        rust_owner: "Menu",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.Item",
        slot: "menu-item",
        description:
            "Focusable action or selectable menu row; descriptions wrap within the popover width.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.ItemIndicator",
        slot: "menu-item-indicator",
        description: "Checkmark or dot selection marker.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.SubmenuIndicator",
        slot: "submenu-indicator",
        description: "Trailing chevron for an item that opens a submenu.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.SubmenuTrigger",
        slot: "dropdown-submenu-trigger",
        description: "Item wrapper that keeps the parent open while opening a child popover.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
];

const DROPDOWN_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".dropdown__trigger:hover / .menu-item[data-hovered]",
        description: "Pointer is over the trigger or a menu item.",
        rust: "track_interaction + theme hover",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: "[data-focus=\"true\"]",
        description: "Element owns keyboard focus.",
        rust: "FocusHandle / keyed menu focus",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus indicator is visible.",
        rust: "focus_handle + status-focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ":active / [data-pressed=\"true\"]",
        description: "Trigger or item is being activated.",
        rust: "track_interaction + scale",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: "[data-disabled=\"true\"] / aria-disabled",
        description: "Trigger or item cannot be activated.",
        rust: "disabled_keys + disabled row",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Selected",
        selector: "[data-selected=\"true\"] / aria-selected",
        description: "Item is selected in single or multiple mode.",
        rust: "selected_keys + selection_mode",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Entering",
        selector: ".dropdown__popover[data-entering]",
        description: "Popover is playing its enter transition.",
        rust: "overlay_phase::Entering",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Exiting",
        selector: ".dropdown__popover[data-exiting]",
        description: "Popover remains mounted while its exit transition plays.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".label / .description / .header / .kbd--light", value: "label text-sm font-medium; description/header text-xs; light Kbd shortcuts", description: "Built-in labels use 14px/20px medium text; descriptions and section headers use 12px/16px. Descriptions stack without a gap, and shortcuts reuse light Kbd.", rust: "Menu built-in text styles + Kbd::new().variant(Light)", status: ImplementationStatus::Implemented },
    StyleDoc {
        class_or_token: ".dropdown",
        value: "flex flex-col gap-1",
        description: "Root wrapper layout.",
        rust: "Dropdown root: flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value: "inline-block; outline-none; cursor-interactive",
        description: "Trigger base, cursor and focus surface.",
        rust: "Dropdown::render trigger_wrap + cursor_pointer",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value:
            "transform 250ms ease-out-quart; background 150ms ease-smooth; shadow 150ms ease-out",
        description: "Trigger interaction motion.",
        rust: "Dropdown::render trigger_wrap",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "max-w-48svw; md:min-w-55; bg-overlay; p-0; text-sm; shadow-overlay",
        description: "Positions against the measured trigger; all eight placements flip to the side with more room when the preferred side cannot fit, keeping a 12px cross-axis viewport inset with the scroller capped to the available height. Overlay surface.",
        rust: "floating + scrollable_popover + max_h_full + overlay surface",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "border-radius: min(32px, var(--radius-3xl))",
        description: "Floating panel radius token.",
        rust: "util::overlay_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-entering]",
        value: "150ms ease-smooth fade-in-0 zoom-in-90 + placement slide",
        description: "Popover enter motion.",
        rust: "overlay_phase::Entering + placement",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-exiting]",
        value: "100ms ease-smooth zoom-out-95 fade-out",
        description: "Popover exit motion.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__menu",
        value: "relative flex w-full flex-col gap-0.5 overflow-clip p-1",
        description: "Menu layout and inset.",
        rust: "Menu root: flex_col + gap(px(2.)) + p(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu",
        value: "relative flex w-full flex-col gap-1 overflow-clip p-1",
        description: "Shared Menu base styles used by Dropdown.Menu.",
        rust: "Menu root",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "min-h-9; gap-3; rounded-2xl; px-2; py-1.5",
        description: "Standalone Menu row metrics: 36px minimum height, 12px gap, 16px radius, 8px horizontal inset, 6px vertical inset.",
        rust: "Menu::render row .px(px(8.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"dropdown-menu\"]",
        value: "p-1.5",
        description: "Dropdown composition overrides the menu inset to 6px.",
        rust: "Menu::render dropdown_composition .p(px(6.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"menu-item\"]",
        value: "px-2.5",
        description: "Dropdown composition overrides each row's horizontal inset to 10px.",
        rust: "Menu::render dropdown_composition .px(px(10.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "transform 250ms ease-out-quart; shadow 150ms ease-out",
        description: "Menu row interaction motion.",
        rust: "menu item press/hover motion",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-hovered]",
        value: "bg-default",
        description: "Hovered menu row surface.",
        rust: "theme hover background",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-pressed]",
        value: "transform: scale(0.98)",
        description: "Pressed menu row feedback.",
        rust: "press scale",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-disabled]",
        value: "status-disabled",
        description: "Disabled row treatment.",
        rust: "disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator",
        value: "absolute start-2; size-4; text-muted",
        description: "Selection indicator placement and size.",
        rust: "indicator slot",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator--submenu",
        value: "text-muted; svg size-3",
        description: "Submenu chevron styling.",
        rust: "submenu indicator",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".menu-item--danger",
        value: "indicator and label text-danger",
        description: "Danger item variant.",
        rust: "MenuItem::danger",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--ease-smooth / --ease-out-quart",
        value: "v3 motion curves",
        description: "Official v3 easing tokens used by trigger, popover and rows.",
        rust: "Curve constants",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--overlay / --shadow-overlay / --radius-3xl",
        value: "overlay surface tokens",
        description: "Official v3 floating-surface tokens.",
        rust: "active theme overlay tokens",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const DROPDOWN: ReferenceMetadata = ReferenceMetadata {
    page: "Dropdown",
    import_line: "use herogpui::components::dropdown::{Dropdown, MenuItem};",
    source_module: "dropdown",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/dropdown.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/dropdown/dropdown.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/dropdown.css",
    required_parts: DROPDOWN_REQUIRED_PARTS,
    api: DROPDOWN_API,
    parts: DROPDOWN_PARTS,
    states: DROPDOWN_STATES,
    styling: DROPDOWN_STYLING,
};

const LIST_BOX_REQUIRED_PARTS: &[&str] = &[
    "ListBox",
    "ListBox.Item",
    "ListBox.ItemIndicator",
    "ListBox.Section",
];

const LIST_BOX_API: &[ApiDoc] = &[
    ApiDoc { owner: "ListBox", prop: "selectionMode", ty: "\"none\" | \"single\" | \"multiple\"", default: "\"none\"", description: "Chooses inert, single, or multiple selection semantics; the wrapper sets no default, so the pinned React Stately one applies.", rust_owner: "ListBox", rust: "selection_mode(SelectionMode)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "selectedKeys", ty: "Selection", default: "—", description: "Controlled selected keys; the owner must accept reported changes.", rust_owner: "ListBox", rust: "selected_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "defaultSelectedKeys", ty: "Selection", default: "—", description: "Seeds the list's uncontrolled selected-key set once.", rust_owner: "ListBox", rust: "default_selected_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "onSelectionChange", ty: "(keys: Selection) => void", default: "—", description: "Reports the complete selected-key set after pointer and keyboard changes.", rust_owner: "ListBox", rust: "on_selection_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "disabledKeys", ty: "Iterable<Key>", default: "—", description: "Removes matching options from pointer and keyboard selection stops.", rust_owner: "ListBox", rust: "disabled_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "onAction", ty: "(key: Key) => void", default: "—", description: "Reports item activation independently from selection where React Aria gives action priority.", rust_owner: "ListBox", rust: "on_action(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "variant", ty: "\"default\" | \"danger\"", default: "\"default\"", description: "Default visual variant inherited by options unless an item overrides it.", rust_owner: "ListBox", rust: "variant(ListBoxItemVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "disallowEmptySelection", ty: "boolean", default: "false", description: "Inherited React Aria policy blocks the final-key toggle and Escape clearing.", rust_owner: "ListBox", rust: "disallow_empty_selection(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "shouldFocusWrap", ty: "boolean", default: "false", description: "Inherited React Aria policy joins the arrow-key ends.", rust_owner: "ListBox", rust: "should_focus_wrap(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "selectionBehavior", ty: "\"toggle\" | \"replace\"", default: "\"toggle\"", description: "The port implements pinned toggle behavior only; replace-on-focus selection is unavailable.", rust_owner: "ListBox", rust: "fixed toggle behavior", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox", prop: "autoFocus", ty: "boolean | FocusStrategy", default: "false", description: "Entry focus follows the selected key or first enabled option, but automatic mount focus is not exposed.", rust_owner: "ListBox", rust: "entry focus only", status: ImplementationStatus::Partial },
    ApiDoc { owner: "ListBox", prop: "escapeKeyBehavior", ty: "\"clearSelection\" | \"none\"", default: "\"clearSelection\"", description: "Controls whether unmodified Escape clears a nonempty selection or remains available to an enclosing interaction.", rust_owner: "ListBox", rust: "escape_key_behavior(EscapeKeyBehavior)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "renderEmptyState", ty: "(props: ListBoxRenderProps) => ReactNode", default: "—", description: "An empty collection renders no synthetic option and has no empty-state slot.", rust_owner: "ListBox", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox", prop: "layout / orientation", ty: "\"stack\" | \"grid\" / Orientation", default: "\"stack\" / \"vertical\"", description: "This port exposes the pinned vertical stack layout only.", rust_owner: "ListBox", rust: "fixed vertical stack", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox", prop: "children", ty: "ReactNode", default: "—", description: "Items, sections, and separators are supplied as the constructor collection.", rust_owner: "ListBox", rust: "new(id, items)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox", prop: "aria-label / aria-labelledby", ty: "string", default: "—", description: "GPUI has no accessibility tree attributes.", rust_owner: "ListBox", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox", prop: "className / render", ty: "string / DOMRenderFunction", default: "—", description: "Browser CSS classes and DOM root substitution are unavailable.", rust_owner: "ListBox", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox.Item", prop: "id", ty: "Key", default: "—", description: "Stable option identity used for selection and callbacks.", rust_owner: "ListBoxItem", rust: "new(key, label)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Item", prop: "textValue", ty: "string", default: "—", description: "The constructor label is the option's typeahead text.", rust_owner: "ListBoxItem", rust: "new(key, label)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Item", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables one option independently from disabledKeys.", rust_owner: "ListBoxItem", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Item", prop: "variant", ty: "\"default\" | \"danger\"", default: "\"default\"", description: "Overrides the option visual variant.", rust_owner: "ListBoxItem", rust: "variant(ListBoxItemVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Item", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Replacement row content receives selected, focused, focus-visible, pressed, and disabled state.", rust_owner: "ListBox", rust: "item_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Item", prop: "render", ty: "DOM render function", default: "—", description: "DOM element substitution and link attributes are unavailable.", rust_owner: "ListBoxItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListBox.ItemIndicator", prop: "children", ty: "ReactNode | RenderFunction", default: "checkmark", description: "Replaces the selected indicator and receives isSelected.", rust_owner: "ListBox", rust: "indicator(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListBox.Section", prop: "children", ty: "ReactNode", default: "—", description: "Section headers and separators are explicit collection records.", rust_owner: "ListBoxItem", rust: "section(label) / separator()", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListLayout", prop: "rowHeight", ty: "number | undefined", default: "48", description: "Fixed row geometry enables uniform-list virtualization; the virtual list caps at max_h, shrinks below it in a bounded parent, and pages by the visible viewport while skipping disabled stops.", rust_owner: "ListBox", rust: "row_height(px)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListLayout", prop: "estimatedRowHeight", ty: "number | undefined", default: "—", description: "Estimated variable row geometry enables measured list virtualization.", rust_owner: "ListBox", rust: "estimated_row_height(px)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListLayout", prop: "headingHeight", ty: "number | undefined", default: "48", description: "Sets virtual section-row height.", rust_owner: "ListBox", rust: "heading_height(px)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListLayout", prop: "estimatedHeadingHeight", ty: "number | undefined", default: "—", description: "Section headings are single-line records rather than independently estimated layouts.", rust_owner: "ListBox", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListLayout", prop: "loaderHeight / dropIndicatorThickness", ty: "number | undefined", default: "48 / 2", description: "This collection has neither a loader row nor drag-and-drop indicators.", rust_owner: "ListBox", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "ListLayout", prop: "gap", ty: "number | undefined", default: "0", description: "Overrides the pinned direct-child spacing.", rust_owner: "ListBox", rust: "gap(px)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "ListLayout", prop: "padding", ty: "number | undefined", default: "0", description: "Overrides the pinned list inset.", rust_owner: "ListBox", rust: "padding(px)", status: ImplementationStatus::Implemented },
];

const LIST_BOX_PARTS: &[PartDoc] = &[
    PartDoc { name: "ListBox", slot: "list-box", description: "Selection, focus, keyboard, scrolling, and virtualization owner.", rust_owner: "ListBox", status: ImplementationStatus::Implemented },
    PartDoc { name: "ListBox.Item", slot: "list-box-item", description: "Selectable option with label, description, icon, shortcut, variant, and render state.", rust_owner: "ListBoxItem", status: ImplementationStatus::Implemented },
    PartDoc { name: "ListBox.ItemIndicator", slot: "list-box-item-indicator", description: "Built-in check or caller-rendered selected marker.", rust_owner: "ListBox", status: ImplementationStatus::Implemented },
    PartDoc { name: "ListBox.Section", slot: "list-box-section", description: "Non-selectable heading record grouping following options; nested section ownership is flattened.", rust_owner: "ListBoxItem", status: ImplementationStatus::Partial },
];

const LIST_BOX_STATES: &[StateDoc] = &[
    StateDoc { state: "Selected", selector: ".list-box-item[data-selected=true]", description: "Selection is shown by the trailing indicator without adding a row fill.", rust: "selected_keys + indicator", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focused", selector: ".list-box-item[data-focused=true]", description: "Roving keyboard cursor tracks one enabled option.", rust: "cursor keyed state", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focus visible", selector: ".list-box-item[data-focus-visible=true]", description: "Keyboard focus draws the pinned status ring and reaches item render state.", rust: "with_focus_ring + item_content", status: ImplementationStatus::Implemented },
    StateDoc { state: "Pressed", selector: ".list-box-item[data-pressed=true]", description: "Interactive options shrink to 98% and expose pressed render state.", rust: "anim::pressed + interaction", status: ImplementationStatus::Implemented },
    StateDoc { state: "Hovered", selector: ".list-box-item[data-hovered=true]", description: "Enabled options use the default hover fill; v3 does not include hover in its documented item render-prop table.", rust: "row hover chrome", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled", selector: ".list-box-item[data-disabled=true]", description: "Disabled options dim and leave pointer, arrow, typeahead, and selection stops.", rust: "is_disabled / disabled_keys", status: ImplementationStatus::Implemented },
];

const LIST_BOX_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".label / .description / .header / .kbd--light", value: "label text-sm font-medium; description/header text-xs; light Kbd shortcuts", description: "Built-in labels use 14px/20px medium text; descriptions and section headers use 12px/16px. Descriptions stack without a gap, and shortcuts reuse light Kbd.", rust: "ListBox built-in text styles + Kbd::new().variant(Light)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box", value: "relative w-full overflow-clip p-1", description: "Full-width clipped list with four-pixel inset.", rust: "relative + w_full + overflow_hidden + padding 4px", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box > * + *", value: "mt-1", description: "Four pixels between direct collection records without flex-shrinking virtual content.", rust: "gap 4px in row geometry", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box-item", value: "min-h-9 gap-3 rounded-2xl px-2 py-1.5", description: "Option minimum height, 12px gap, 16px radius, and 8px/6px padding match.", rust: "FIELD_HEIGHT + gap(12) + soft_radius + px(8) + py(6)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box-item pressed", value: "scale(0.98); transform 250ms ease-out-quart", description: "Pressed geometry matches; the port uses its shared press timeline rather than the exact quart curve.", rust: "anim::pressed(PRESSED_SCALE_SUBTLE)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".list-box-item hover", value: "bg-default", description: "Enabled pointer hover uses the default surface fill.", rust: "colors.default.color hover", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box-item__indicator", value: "absolute end-2 size-4 text-default-foreground", description: "Size and default/danger colors match; flex layout places it at the trailing edge without the pinned absolute logical-end positioning.", rust: "inline trailing 16px indicator", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".list-box-item--danger", value: "indicator and label text-danger", description: "Danger options and their indicator use the danger semantic color.", rust: "ListBoxItemVariant::Danger", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".list-box-section", value: "flex flex-col items-start gap-0", description: "The port flattens section heading records into the list rather than nesting a section container.", rust: "ListBoxItem::Section row", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".list-box separator", value: "ms-[3%] w-[94%]", description: "Separators are centered at 94% width.", rust: "separator margin and width", status: ImplementationStatus::Implemented },
];

pub(super) const LIST_BOX: ReferenceMetadata = ReferenceMetadata {
    page: "ListBox",
    import_line: "use herogpui::components::list_box::{ListBox, ListBoxItem};",
    source_module: "list_box",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/list-box.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/list-box/list-box.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/list-box-item/list-box-item.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/list-box-section/list-box-section.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria-components/src/ListBox.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/list-box.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/list-box-item.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/list-box-section.css",
    required_parts: LIST_BOX_REQUIRED_PARTS,
    api: LIST_BOX_API,
    parts: LIST_BOX_PARTS,
    states: LIST_BOX_STATES,
    styling: LIST_BOX_STYLING,
};

const TAG_GROUP_REQUIRED_PARTS: &[&str] = &["TagGroup", "TagGroup.List", "Tag", "Tag.RemoveButton"];

const TAG_GROUP_API: &[ApiDoc] = &[
    ApiDoc { owner: "TagGroup", prop: "selectionMode", ty: "\"none\" | \"single\" | \"multiple\"", default: "\"none\"", description: "Chooses inert, single, or multiple tag selection.", rust_owner: "TagGroup", rust: "selection_mode(SelectionMode)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "selectedKeys", ty: "Selection", default: "—", description: "Controlled selected keys; the owner must accept reported changes.", rust_owner: "TagGroup", rust: "selected_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "defaultSelectedKeys", ty: "Selection", default: "—", description: "Seeds the group's uncontrolled selected-key set once.", rust_owner: "TagGroup", rust: "default_selected_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "onSelectionChange", ty: "(keys: Selection) => void", default: "—", description: "Reports the complete selected-key set after pointer and keyboard changes.", rust_owner: "TagGroup", rust: "on_selection_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "disabledKeys", ty: "Iterable<Key>", default: "—", description: "Removes matching tags from pointer and keyboard interaction.", rust_owner: "TagGroup", rust: "disabled_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables every tag and remove action in the group.", rust_owner: "TagGroup", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "onRemove", ty: "(keys: Set<Key>) => void", default: "—", description: "Adds remove actions and reports one pointer key or the keyboard-selected set.", rust_owner: "TagGroup", rust: "on_remove(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "size", ty: "\"sm\" | \"md\" | \"lg\"", default: "\"md\"", description: "Sets padding, type size, and large-tag radius for every tag.", rust_owner: "TagGroup", rust: "size(Size)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "variant", ty: "\"default\" | \"surface\"", default: "\"default\"", description: "Selects the unselected background and hover token for every tag.", rust_owner: "TagGroup", rust: "variant(TagVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "disallowEmptySelection", ty: "boolean", default: "false", description: "Inherited MultipleSelection policy blocks the final-key toggle and Escape clearing.", rust_owner: "TagGroup", rust: "disallow_empty_selection(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "escapeKeyBehavior", ty: "\"clearSelection\" | \"none\"", default: "\"clearSelection\"", description: "Controls whether unmodified Escape clears a nonempty selection or remains available to an enclosing interaction.", rust_owner: "TagGroup", rust: "escape_key_behavior(EscapeKeyBehavior)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "selectionBehavior", ty: "\"toggle\" | \"replace\"", default: "\"toggle\"", description: "The port implements pinned toggle selection only.", rust_owner: "TagGroup", rust: "fixed toggle behavior", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TagGroup", prop: "shouldSelectOnPressUp", ty: "boolean", default: "false", description: "GPUI activation occurs on click release and is not caller-configurable.", rust_owner: "TagGroup", rust: "fixed release activation", status: ImplementationStatus::Partial },
    ApiDoc { owner: "TagGroup", prop: "onAction", ty: "(key: Key) => void", default: "—", description: "Tags expose selection and removal but no separate item action callback.", rust_owner: "TagGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TagGroup", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "The constructor collection plus label and description builders provide the compound content.", rust_owner: "TagGroup", rust: "new(id, tags) / label / description", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup", prop: "errorMessage", ty: "ReactNode", default: "—", description: "The port has no validation or error-message slot on TagGroup.", rust_owner: "TagGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TagGroup", prop: "className / render", ty: "string / DOMRenderFunction", default: "—", description: "Browser CSS classes and DOM root substitution are unavailable.", rust_owner: "TagGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TagGroup.List", prop: "items", ty: "Iterable<T>", default: "—", description: "The constructor accepts the complete typed tag collection.", rust_owner: "TagGroup", rust: "new(id, tags)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TagGroup.List", prop: "renderEmptyState", ty: "(props: TagListRenderProps) => ReactNode", default: "—", description: "A custom string replaces the built-in empty message, without list render props.", rust_owner: "TagGroup", rust: "empty_state(text)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "TagGroup.List", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Static tags are supplied as the constructor collection; dynamic list render state is unavailable.", rust_owner: "TagGroup", rust: "new(id, tags)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "TagGroup.List", prop: "className / render", ty: "string / DOMRenderFunction", default: "—", description: "The list part cannot be replaced or styled through browser classes.", rust_owner: "TagGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Tag", prop: "id", ty: "Key", default: "—", description: "Stable tag identity used for selection and removal callbacks.", rust_owner: "Tag", rust: "new(key, label)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Tag", prop: "textValue", ty: "string", default: "—", description: "The constructor label is the tag's visible and keyboard text.", rust_owner: "Tag", rust: "new(key, label)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Tag", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables one tag independently from disabledKeys.", rust_owner: "Tag", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Tag", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Replacement content receives selected, disabled, hovered, pressed, focused, and focus-visible state.", rust_owner: "TagGroup", rust: "tag_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Tag", prop: "onAction", ty: "() => void", default: "—", description: "The port exposes group selection and removal callbacks only.", rust_owner: "Tag", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Tag", prop: "className / render", ty: "string / DOMRenderFunction", default: "—", description: "DOM attributes, link behavior, and element substitution are unavailable.", rust_owner: "Tag", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Tag.RemoveButton", prop: "children", ty: "ReactNode", default: "close icon", description: "Each tag may replace the automatic close glyph with custom remove-button content while preserving the built-in action.", rust_owner: "Tag", rust: "remove_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Tag.RemoveButton", prop: "className", ty: "string", default: "—", description: "Browser class customization is unavailable.", rust_owner: "TagGroup", rust: "—", status: ImplementationStatus::Unavailable },
];

const TAG_GROUP_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "TagGroup",
        slot: "tag-group",
        description: "Field-like root owning selection, removal, label, and description.",
        rust_owner: "TagGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "TagGroup.List",
        slot: "tag-group-list",
        description:
            "Wrapping horizontal list and empty-state owner, rendered inside the monolithic root.",
        rust_owner: "TagGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tag",
        slot: "tag",
        description: "Focusable selectable item with optional prefix and caller-rendered content.",
        rust_owner: "Tag",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tag.RemoveButton",
        slot: "tag-remove-button",
        description: "Automatic per-tag remove action with replaceable caller content.",
        rust_owner: "Tag",
        status: ImplementationStatus::Implemented,
    },
];

const TAG_GROUP_STATES: &[StateDoc] = &[
    StateDoc { state: "Selected", selector: ".tag[data-selected=true]", description: "Uses accent-soft foreground and fill, including its selected hover token.", rust: "selected_keys", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled", selector: ".tag[data-disabled=true]", description: "Dims the tag and removes selection, removal, and roving-focus behavior.", rust: "is_disabled / disabled_keys", status: ImplementationStatus::Implemented },
    StateDoc { state: "Hovered", selector: ".tag[data-hovered=true]", description: "Selectable enabled tags use the variant-specific hover fill and expose hover render state.", rust: "hover chrome + tag_content", status: ImplementationStatus::Implemented },
    StateDoc { state: "Pressed", selector: ".tag[data-pressed=true]", description: "The pinned stylesheet has no pressed visual rule; selectable enabled tags expose pressed render state.", rust: "interaction + tag_content", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focused", selector: ".tag[data-focused=true]", description: "One enabled tag owns the group's roving focus handle.", rust: "cursor keyed state", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focus visible", selector: ".tag[data-focus-visible=true]", description: "Keyboard focus draws the status ring and reaches tag render state.", rust: "with_focus_ring + tag_content", status: ImplementationStatus::Implemented },
];

const TAG_GROUP_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".tag-group", value: "relative flex flex-col gap-1", description: "Root positioning, column layout, and four-pixel field-part spacing match.", rust: "relative + flex_col + gap(4)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag-group__list", value: "relative flex flex-wrap gap-1.5", description: "The tag list wraps with six-pixel gaps.", rust: "relative + flex_wrap + gap(6)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag-group description / errorMessage", value: "p-1", description: "Description inset matches; TagGroup has no error-message slot.", rust: "description p(4)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".tag", value: "relative inline-flex items-center gap-1 rounded-xl font-medium", description: "Core geometry and typography match; GPUI has no selectable-text or browser highlight properties.", rust: "relative + flex + items_center + gap(4) + small_radius + MEDIUM", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag transitions", value: "color/scale/opacity/background 100ms ease-smooth; shadow 100ms ease-out", description: "Tag colors and state chrome still change on a frame rather than interpolating.", rust: "immediate state colors", status: ImplementationStatus::Unavailable },
    StyleDoc { class_or_token: ".tag--sm / --md / --lg", value: "8x2 12/16px / 8x4 12/16px / 10x6 14/20px", description: "Size paddings, text sizes and explicit line heights match independently of host text styles, including the large 16px radius.", rust: "metrics(Size) + radius(Size)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag--default", value: "bg-default text-default-foreground; bg-default-hover", description: "Default fill, foreground, and unselected hover token match.", rust: "TagVariant::Default", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag--surface", value: "bg-surface text-surface-foreground; bg-surface-hover", description: "Borderless surface fill, foreground, and derived hover token match.", rust: "TagVariant::Surface + SurfaceColor::hover", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag selected", value: "bg-accent-soft text-accent-soft-foreground; bg-accent-soft-hover", description: "Selected and selected-hover semantic tokens match.", rust: "selected_keys", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag svg", value: "size-3 text-current", description: "Prefix and remove glyphs use the fixed 12px size and resolved tag foreground.", rust: "svg size(12) + tag_foreground", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".tag__remove-button", value: "size-3 text-inherit", description: "Box size and inherited color match; the port does not expose the composed CloseButton surface independently.", rust: "12px remove action", status: ImplementationStatus::Partial },
];

pub(super) const TAG_GROUP: ReferenceMetadata = ReferenceMetadata {
    page: "TagGroup",
    import_line: "use herogpui::components::tag_group::{Tag, TagGroup};",
    source_module: "tag_group",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/tag-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/tag-group/tag-group.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/tag/tag.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria-components/src/TagGroup.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria/src/tag/useTagGroup.ts",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/tag-group.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/tag.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/close-button.css",
    required_parts: TAG_GROUP_REQUIRED_PARTS,
    api: TAG_GROUP_API,
    parts: TAG_GROUP_PARTS,
    states: TAG_GROUP_STATES,
    styling: TAG_GROUP_STYLING,
};
