//! controls reference metadata.

use super::*;

const SLIDER_REQUIRED_PARTS: &[&str] = &[
    "Slider",
    "Label",
    "Slider.Output",
    "Slider.Track",
    "Slider.Fill",
    "Slider.Thumb",
];

const SLIDER_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Slider",
        prop: "value",
        ty: "number | number[]",
        default: "—",
        description: "The current value or values (controlled).",
        rust_owner: "Slider",
        rust: "value(f32) / values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "defaultValue",
        ty: "number | number[]",
        default: "—",
        description: "The initial value or values (uncontrolled).",
        rust_owner: "Slider",
        rust: "default_value(f32) / default_values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChange",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called whenever a thumb changes value.",
        rust_owner: "Slider",
        rust: "on_change(callback) / on_change_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChangeEnd",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called once when a drag or keyboard step completes.",
        rust_owner: "Slider",
        rust: "on_change_end(callback) / on_change_end_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "minValue",
        ty: "number",
        default: "0",
        description: "The minimum value.",
        rust_owner: "Slider",
        rust: "min_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "maxValue",
        ty: "number",
        default: "100",
        description: "The maximum value.",
        rust_owner: "Slider",
        rust: "max_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "step",
        ty: "number",
        default: "1",
        description: "The increment between valid values.",
        rust_owner: "Slider",
        rust: "step(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "formatOptions",
        ty: "Intl.NumberFormatOptions",
        default: "—",
        description: "Formats the displayed value; the port supports decimal, percent and currency without CLDR locale data.",
        rust_owner: "Slider",
        rust: "format_options(NumberFormat)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"horizontal\"",
        description: "The direction in which values increase.",
        rust_owner: "Slider",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables every thumb and removes the slider from the tab order.",
        rust_owner: "Slider",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-label",
        ty: "string",
        default: "—",
        description: "Accessible label for an otherwise unlabelled slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-labelledby",
        ty: "string",
        default: "—",
        description: "ID of the element that labels the slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the root.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Compound slider content; the monolithic port exposes its label, output and thumb customizations as builders.",
        rust_owner: "Slider",
        rust: "label(value)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the root DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the output.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom output content handed every live value and its formatted thumb label.",
        rust_owner: "Slider",
        rust: "output(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the output DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the track.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Track content; the thumb closure receives each computed index and value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the track DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "style",
        ty: "CSSProperties",
        default: "—",
        description: "Inline styles for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "index",
        ty: "number",
        default: "0",
        description: "Index of the thumb within the slider.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables this thumb only and removes its form field and tab stop.",
        rust_owner: "Slider",
        rust: "disabled_keys(indices)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Name of this thumb's submitted form value.",
        rust_owner: "Slider",
        rust: "thumb_names(names)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the thumb.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom thumb content with its index and current value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the thumb DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "state",
        ty: "SliderState",
        default: "—",
        description: "Full slider state passed to Output and Track render functions.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "values",
        ty: "number[]",
        default: "—",
        description: "Live values by thumb index supplied to Slider.Output.",
        rust_owner: "Slider",
        rust: "output(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "getThumbValueLabel",
        ty: "(index: number) => string",
        default: "—",
        description: "The output closure receives one formatted label per thumb index.",
        rust_owner: "Slider",
        rust: "output(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "—",
        description: "Current orientation supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current disabled state supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const SLIDER_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Slider",
        slot: "slider",
        description: "Root value, form, pointer and keyboard state owner.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Optional text label rendered above or beside the track.",
        rust_owner: "Slider",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Slider.Output",
        slot: "slider-output",
        description:
            "Formatted current values or custom content rendered from the live value array.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Track",
        slot: "slider-track",
        description: "Pointer and keyboard surface containing fill and thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Fill",
        slot: "slider-fill",
        description: "Accent span from the minimum or between the outermost thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Thumb",
        slot: "slider-thumb",
        description: "One draggable, focusable value handle per value.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Horizontal",
        selector: ".slider[data-orientation=\"horizontal\"]",
        description: "Values increase from left to right.",
        rust: "Orientation::Horizontal",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical",
        selector: ".slider[data-orientation=\"vertical\"]",
        description: "Values increase from bottom to top.",
        rust: "Orientation::Vertical",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".slider__thumb[data-focus-visible=\"true\"]",
        description: "The active enabled thumb carries the keyboard focus ring.",
        rust: "ring_if_focused + active_thumb",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Dragging",
        selector: ".slider__thumb[data-dragging=\"true\"]",
        description: "Pointer drag state updates the value and scales the inner thumb to 90%; gpui applies the scale without CSS's 250ms ramp.",
        rust: "DragState",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled slider",
        selector: ".slider[data-disabled=\"true\"]",
        description: "All thumbs are inert, dimmed and removed from form submission and tab order.",
        rust: "Slider::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled thumb",
        selector: ".slider__thumb[data-disabled=\"true\"]",
        description: "One thumb is inert and omitted while its siblings remain interactive.",
        rust: "Slider::disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill start",
        selector: ".slider__track[data-fill-start=\"true\"]",
        description: "The accent fill reaches the low edge.",
        rust: "fill_from == 0",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill end",
        selector: ".slider__track[data-fill-end=\"true\"]",
        description: "The accent fill reaches the high edge.",
        rust: "fill_to == 1",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".slider",
        value: "grid w-full gap-1",
        description: "Root layout with label and output above the track.",
        rust: "Slider::render flex_col + gap(px(4.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: "[data-slot=\"label\"] / .slider__output",
        value: "text-sm font-medium; output tabular-nums",
        description: "Label and output typography.",
        rust: "Slider::render text_size(px(14.)) + line_height(px(20.)) + FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__track",
        value: "rounded-xl bg-default; horizontal h-5; vertical w-5; border-x/y-[0.75rem]",
        description: "Twenty-pixel track with transparent 12px end borders for the thumb overhang; fill caps paint those ends accent when the fill reaches them.",
        rust: "20px default-color track + small_radius + axis_inset(12px) + fill_start/fill_end caps",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__fill",
        value: "pointer-events-none absolute bg-accent",
        description: "Accent span representing the selected interval.",
        rust: "absolute accent fill from fill_from to fill_to",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb",
        value: "28x20 horizontal or 20x28 vertical outer pill; 24x16 or 16x24 inner pill",
        description: "Accent outer handle with accent-foreground inner handle.",
        rust: "28x20 / 20x28 outer + 24x16 / 16x24 inner",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-dragging=\"true\"]::after",
        value: "scale(0.9); 250ms ease-out; motion-reduce none",
        description: "Dragging feedback and reduced-motion override.",
        rust: "DragState inner geometry scale; instant under gpui",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-focus-visible=\"true\"]",
        value: "status-focused",
        description: "Keyboard focus treatment.",
        rust: "util::ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider[data-disabled=\"true\"]",
        value: "status-disabled; label opacity 100%",
        description: "Whole-slider disabled treatment.",
        rust: "layout.disabled_opacity",
        status: ImplementationStatus::Partial,
    },
];

pub(super) const SLIDER: ReferenceMetadata = ReferenceMetadata {
    page: "Slider",
    import_line: "use herogpui::components::slider::Slider;",
    source_module: "slider",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(controls)/slider.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/slider/slider.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/slider.css",
    required_parts: SLIDER_REQUIRED_PARTS,
    api: SLIDER_API,
    parts: SLIDER_PARTS,
    states: SLIDER_STATES,
    styling: SLIDER_STYLING,
};

const SWITCH_REQUIRED_PARTS: &[&str] = &[
    "Switch",
    "Switch.Control",
    "Switch.Thumb",
    "Switch.Icon",
    "Switch.Content",
    "Label",
    "Description",
    "FieldError",
    "SwitchGroup",
    "SwitchGroup.Items",
];

const SWITCH_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Switch",
        prop: "size",
        ty: "'sm' | 'md' | 'lg'",
        default: "'md'",
        description: "Track and thumb size.",
        rust_owner: "Switch",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "isSelected",
        ty: "boolean",
        default: "false",
        description: "Current selected state (controlled).",
        rust_owner: "Switch",
        rust: "is_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "defaultSelected",
        ty: "boolean",
        default: "false",
        description: "Initial selected state (uncontrolled).",
        rust_owner: "Switch",
        rust: "default_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Dims the whole field and removes it from interaction and form data.",
        rust_owner: "Switch",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "isInvalid",
        ty: "boolean",
        default: "false",
        description: "Marks the field invalid and blocks native form submission.",
        rust_owner: "Switch",
        rust: "is_invalid(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "isReadOnly",
        ty: "boolean",
        default: "false",
        description: "Keeps the field focusable while preventing changes.",
        rust_owner: "Switch",
        rust: "is_read_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "isRequired",
        ty: "boolean",
        default: "false",
        description: "Requires selection under native form validation.",
        rust_owner: "Switch",
        rust: "is_required(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "validate",
        ty: "(value: boolean) => ValidationError | true | null | undefined",
        default: "—",
        description: "Computes field validity from the current selection.",
        rust_owner: "Switch",
        rust: "validate(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "validationBehavior",
        ty: "'native' | 'aria'",
        default: "'native'",
        description: "Chooses blocking native validation or non-blocking ARIA-style reporting.",
        rust_owner: "Switch",
        rust: "validation_behavior(ValidationBehavior)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Submitted form field name.",
        rust_owner: "Switch",
        rust: "name(value) + form_field()",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "value",
        ty: "string",
        default: "'on'",
        description: "Submitted value when selected.",
        rust_owner: "Switch",
        rust: "value(value) + form_field()",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "onChange",
        ty: "(isSelected: boolean) => void",
        default: "—",
        description: "Reports the next selection state.",
        rust_owner: "Switch",
        rust: "on_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Switch",
        prop: "onPress",
        ty: "(event: PressEvent) => void",
        default: "—",
        description: "The port reports the next boolean rather than a browser PressEvent.",
        rust_owner: "Switch",
        rust: "on_press(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Switch",
        prop: "children",
        ty: "ReactNode | (values: SwitchRenderProps) => ReactNode",
        default: "—",
        description: "Label, control content and a state-driven content closure are supported.",
        rust_owner: "Switch",
        rust: "label(element), thumb_icons(off, on), content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Switch",
        prop: "render",
        ty: "DOMRenderFunction<..., SwitchRenderProps>",
        default: "—",
        description: "Overrides the browser DOM root.",
        rust_owner: "Switch",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Current selected state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isHovered",
        ty: "boolean",
        default: "—",
        description: "Current hover state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Current press state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Current focus state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isFocusVisible",
        ty: "boolean",
        default: "—",
        description: "Keyboard-visible focus state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disabled state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isReadOnly",
        ty: "boolean",
        default: "—",
        description: "Read-only state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isInvalid",
        ty: "boolean",
        default: "—",
        description: "Resolved validation state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "isRequired",
        ty: "boolean",
        default: "—",
        description: "Required state supplied to custom content.",
        rust_owner: "Switch",
        rust: "content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchRenderProps",
        prop: "state",
        ty: "SwitchState",
        default: "—",
        description: "React Aria's browser state object.",
        rust_owner: "Switch",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "SwitchGroup",
        prop: "orientation",
        ty: "'horizontal' | 'vertical'",
        default: "'vertical'",
        description: "Direction of the items container.",
        rust_owner: "SwitchGroup",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchGroup",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Independent Switch children.",
        rust_owner: "SwitchGroup",
        rust: "child(element) / ParentElement",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "SwitchGroup",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional browser CSS classes.",
        rust_owner: "SwitchGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const SWITCH_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Switch",
        slot: "switch",
        description: "Field root carrying selection, validation, form and disabled state.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Switch.Content",
        slot: "switch-content",
        description: "Clickable row containing the control and label in caller-selected order.",
        rust_owner: "Switch",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Switch.Control",
        slot: "switch-control",
        description: "Focusable track and interaction surface.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Switch.Thumb",
        slot: "switch-thumb",
        description: "State-positioned thumb with optional content.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Switch.Icon",
        slot: "switch-icon",
        description: "Centered off/on icon inside the thumb.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Optional label before or after the control.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Description",
        slot: "description",
        description: "Size-aligned help text outside the clickable row.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "FieldError",
        slot: "field-error",
        description: "Size-aligned validation text outside the clickable row.",
        rust_owner: "Switch",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "SwitchGroup",
        slot: "switch-group",
        description: "Layout root for independent switches.",
        rust_owner: "SwitchGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "SwitchGroup.Items",
        slot: "switch-group-items",
        description: "Horizontal or vertical items container.",
        rust_owner: "SwitchGroup",
        status: ImplementationStatus::Implemented,
    },
];

const SWITCH_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Selected",
        selector: ".switch[data-selected=\"true\"]",
        description: "Accent track and end-positioned foreground thumb.",
        rust: "checked",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ".switch__content[data-hovered=\"true\"]",
        description: "Track changes to the hover token and custom content sees isHovered.",
        rust: "hover style + SwitchState::is_hovered",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".switch__content[data-pressed=\"true\"]",
        description: "Track uses the pressed token and custom content sees isPressed.",
        rust: "active style + SwitchState::is_pressed",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".switch__content[data-focus-visible=\"true\"]",
        description: "Keyboard focus rings the track.",
        rust: "ring_if_focused + focus_visible",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".switch[data-disabled=\"true\"]",
        description: "Whole field is dimmed, inert, untabbable and omitted from form data.",
        rust: "is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Read only",
        selector: ".switch[data-readonly=\"true\"]",
        description: "Field stays focusable but pointer and keyboard activation do nothing.",
        rust: "is_read_only",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Invalid",
        selector: ".switch[data-invalid=\"true\"]",
        description: "Resolved validation is rendered and blocks native form submission.",
        rust: "validation::resolve + LiveFormFieldState::is_invalid",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Required",
        selector: ".switch[data-required=\"true\"]",
        description: "Required marker and native empty-selection validation.",
        rust: "is_required",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical group",
        selector: ".switch-group--vertical",
        description: "Items stack in a column.",
        rust: "SwitchGroup::orientation(Orientation::Vertical)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Horizontal group",
        selector: ".switch-group--horizontal",
        description: "Items flow in a row.",
        rust: "SwitchGroup::orientation(Orientation::Horizontal)",
        status: ImplementationStatus::Implemented,
    },
];

const SWITCH_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: "text-sm", value: "14px text with 20px line height", description: "Content uses 14px text with 20px lines; the built-in label uses 16px text with 24px lines.", rust: "text_size + line_height", status: ImplementationStatus::Implemented },
    StyleDoc {
        class_or_token: ".switch",
        value: "flex flex-col items-start gap-1",
        description: "Field root around content, description and error.",
        rust: "flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch__content",
        value: "inline-flex items-center gap-3 text-sm font-medium",
        description: "Clickable control and label row.",
        rust: "items_center + gap(px(12.)) + text_size(px(14.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".switch__control",
        value: "32x16 / 40x20 / 48x24; rounded-lg/xl",
        description: "Track dimensions and radii for sm, md and lg.",
        rust: "size match in Switch::render",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch__thumb",
        value: "16.5x12 / 22x16 / 27.5x20; 2px inset",
        description: "Thumb dimensions and resting inset.",
        rust: "thumb size match + px(2.)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch[data-selected] .switch__thumb",
        value: "margin 300ms ease-out-fluid",
        description: "Thumb travels from its current position and reverses without jumping.",
        rust: "ThumbMotionFrame + THUMB_TRANSITION_MS",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch__control",
        value: "background-color 250ms ease-smooth",
        description: "Track colors interpolate over 250ms and switch to an immediate fill under reduced motion.",
        rust: "TrackMotionFrame + TRACK_TRANSITION_MS",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch > [data-slot=\"description\"]",
        value: "ps: 44px sm, 52px md, 60px lg",
        description: "Help text aligns after the track and 12px content gap.",
        rust: "pl(w + px(12.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch > [data-slot=\"field-error\"]",
        value: "ps: 44px sm, 52px md, 60px lg",
        description: "Validation text uses the same size-specific alignment.",
        rust: "pl(w + px(12.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch[data-disabled]",
        value: "status-disabled",
        description: "Disabled opacity covers content and both message rows.",
        rust: "root opacity(layout.disabled_opacity)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch__thumb > *",
        value: "flex size-full items-center justify-center",
        description: "Thumb icon alignment.",
        rust: "thumb flex + items_center + justify_center",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch-group",
        value: "flex flex-col gap-6",
        description: "Group root geometry.",
        rust: "flex_col + gap(px(24.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".switch-group__items",
        value: "flex gap-4; row or column",
        description: "Orientation-controlled items layout.",
        rust: "flex_row/flex_col + gap(px(16.))",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const SWITCH: ReferenceMetadata = ReferenceMetadata {
    page: "Switch",
    import_line: "use herogpui::components::switch::Switch;",
    source_module: "switch",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(controls)/switch.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/switch/switch.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/switch.css",
    required_parts: SWITCH_REQUIRED_PARTS,
    api: SWITCH_API,
    parts: SWITCH_PARTS,
    states: SWITCH_STATES,
    styling: SWITCH_STYLING,
};
