//! data_display reference metadata.

use super::*;

const TABLE_REQUIRED_PARTS: &[&str] = &[
    "Table",
    "Table.ScrollContainer",
    "Table.Content",
    "Table.Header",
    "Table.Column",
    "Table.Body",
    "Table.Row",
    "Table.Cell",
    "Table.SortableColumnHeader",
    "Table.Footer",
    "Table.ColumnResizer",
    "Table.ResizableContainer",
    "Table.LoadMore",
    "Table.LoadMoreContent",
    "Table.Collection",
];

const TABLE_API: &[ApiDoc] = &[
    ApiDoc { owner: "Table", prop: "variant", ty: "\"primary\" | \"secondary\"", default: "\"primary\"", description: "Primary draws the gray tray and surface card; secondary is flat.", rust_owner: "Table", rust: "variant(TableVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the root container.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table", prop: "children", ty: "React.ReactNode", default: "—", description: "Compound ScrollContainer, Content, Footer and related parts; the port takes columns up front and builders for the rest.", rust_owner: "Table", rust: "new(columns)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.ScrollContainer", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the horizontal scroll wrapper.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.ScrollContainer", prop: "children", ty: "React.ReactNode", default: "—", description: "Always wraps Table.Content; the port draws the scroller rather than accepting a replaceable child part.", rust_owner: "Table", rust: "new(columns)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Content", prop: "aria-label", ty: "string", default: "—", description: "Accessible name for the table; GPUI has no accessibility tree to publish it to.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "selectionMode", ty: "\"none\" | \"single\" | \"multiple\"", default: "\"none\"", description: "Adds the selection column and row-activation behaviour when not none.", rust_owner: "Table", rust: "selection_mode(SelectionMode)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "selectedKeys", ty: "Selection", default: "—", description: "Controlled selected keys as shared strings rather than RAC's Set/\"all\" union.", rust_owner: "Table", rust: "selected_keys(keys)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Content", prop: "defaultSelectedKeys", ty: "Selection", default: "—", description: "Uncontrolled selection seed; the port only falls back to an empty set when selected_keys is unset.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "onSelectionChange", ty: "(keys: Selection) => void", default: "—", description: "Reports the whole selection after a row, checkbox or select-all change.", rust_owner: "Table", rust: "on_selection_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "sortDescriptor", ty: "SortDescriptor", default: "—", description: "Current sort column and direction, shown in the header. The table does not reorder its own rows.", rust_owner: "Table", rust: "sort_descriptor(descriptor)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "onSortChange", ty: "(descriptor: SortDescriptor) => void", default: "—", description: "Sortable header activation; the caller rebuilds rows from the descriptor.", rust_owner: "Table", rust: "on_sort_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "disabledKeys", ty: "Iterable<Key>", default: "—", description: "Pinned RAC inherited keys excluded from selection, actions and the roving tab stops.", rust_owner: "Table", rust: "disabled_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "onRowAction", ty: "(key: Key) => void", default: "—", description: "Pinned RAC row action; the port reports the visible row index rather than the collection key.", rust_owner: "Table", rust: "on_row_click(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Content", prop: "expandedKeys", ty: "Iterable<Key>", default: "—", description: "Controlled parent keys whose nested rows are shown.", rust_owner: "Table", rust: "expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "onExpandedChange", ty: "(keys: Key[]) => void", default: "—", description: "Reports the expanded set after a tree chevron is pressed.", rust_owner: "Table", rust: "on_expanded_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Content", prop: "treeColumn", ty: "Key", default: "—", description: "Column that carries the expand chevron and indent; the port takes a column index rather than a column key.", rust_owner: "Table", rust: "tree_column(index)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Content", prop: "selectionBehavior", ty: "\"toggle\" | \"replace\"", default: "\"toggle\"", description: "Pinned RAC selection behaviour; the port always uses its own toggle/shift-range path.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "disabledBehavior", ty: "\"all\" | \"selection\"", default: "\"all\"", description: "Pinned RAC disabledKeys scope; disabled rows here are excluded from selection, actions and keyboard stops together.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "disallowEmptySelection", ty: "boolean", default: "false", description: "Pinned RAC flag that keeps at least one row selected; the port has no such gate.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "dragAndDropHooks", ty: "DragAndDropHooks", default: "—", description: "Pinned RAC drag-and-drop hooks; this port does not implement table reordering.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "keyboardNavigationBehavior", ty: "\"arrow\" | \"tab\"", default: "\"arrow\"", description: "Pinned RAC 1.20 cell-vs-widget keyboard mode; interactive cell children are not a separate tab cycle here.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "onScroll", ty: "(e) => void", default: "—", description: "Pinned RAC scroll callback on the resizable container; the port's scroller is internal.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Content", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the table element.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Header", prop: "columns", ty: "T[]", default: "—", description: "Dynamic column data for the render-prop pattern; the port takes configured TableColumn values.", rust_owner: "Table", rust: "columns(columns)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Header", prop: "children", ty: "React.ReactNode | (column: T) => React.ReactNode", default: "—", description: "Static columns or a render prop; the port appends configured columns.", rust_owner: "Table", rust: "column(column)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Header", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the header row.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Column", prop: "id", ty: "string", default: "—", description: "Column identifier; the port keys sorting and labels by the constructor text rather than a separate id.", rust_owner: "TableColumn", rust: "new(label)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Column", prop: "allowsSorting", ty: "boolean", default: "false", description: "Makes the header a sort control.", rust_owner: "TableColumn", rust: "allows_sorting(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Column", prop: "isRowHeader", ty: "boolean", default: "false", description: "Marks the identifying column; without an accessibility tree the effect is medium-weight cell text.", rust_owner: "TableColumn", rust: "is_row_header(bool)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Column", prop: "defaultWidth", ty: "string | number", default: "—", description: "Starting width for a resizable column. CSS length strings are not accepted; the port takes pixels.", rust_owner: "TableColumn", rust: "default_width(width)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Column", prop: "minWidth", ty: "number", default: "75", description: "Pinned RAC resize floor; the port also applies this 75px default when resizing.", rust_owner: "TableColumn", rust: "min_width(width)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Column", prop: "maxWidth", ty: "number", default: "—", description: "Pinned RAC inherited ceiling for a resizable column.", rust_owner: "TableColumn", rust: "max_width(width)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Column", prop: "allowsResizing", ty: "boolean", default: "false", description: "Pinned RAC inherited flag that draws a drag handle on the column's trailing edge.", rust_owner: "TableColumn", rust: "allows_resizing(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Column", prop: "width", ty: "ColumnSize | null", default: "—", description: "Caller-owned controlled width in pixels; CSS length and fractional strings are not accepted.", rust_owner: "TableColumn", rust: "width(width)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Column", prop: "children", ty: "React.ReactNode | (values: ColumnRenderProps) => React.ReactNode", default: "—", description: "Label or render prop receiving sortDirection; the port takes the label in the constructor and hands sortDirection to indicator.", rust_owner: "TableColumn", rust: "new(label)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Column", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the column header.", rust_owner: "TableColumn", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Column", prop: "textValue", ty: "string", default: "—", description: "Pinned RAC accessibility string for the column; unused without an accessibility tree.", rust_owner: "TableColumn", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Column", prop: "focusMode", ty: "\"child\" | \"cell\"", default: "—", description: "Pinned RAC header focus target; the port focuses the sortable header or resizer itself.", rust_owner: "TableColumn", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Column", prop: "allowsArrowNavigation", ty: "boolean", default: "—", description: "Pinned RAC 1.20 arrow navigation inside a tab-mode header; unused without keyboardNavigationBehavior.", rust_owner: "TableColumn", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Body", prop: "items", ty: "T[]", default: "—", description: "Dynamic row data; static rows are appended one at a time and virtual tables take a factory instead of a generic item list.", rust_owner: "Table", rust: "row(cells)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Body", prop: "renderEmptyState", ty: "() => React.ReactNode", default: "—", description: "Content shown when there are no rows; the port takes an element rather than a render-prop that receives TableBodyRenderProps.", rust_owner: "Table", rust: "empty_state(content)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Body", prop: "children", ty: "React.ReactNode | (item: T) => React.ReactNode", default: "—", description: "Static rows or a render prop; the port appends TableRow values or a virtual factory.", rust_owner: "Table", rust: "row(cells)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Body", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the body.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Row", prop: "id", ty: "string | number", default: "—", description: "Row identifier used for selection; numeric RAC keys are represented as shared strings, defaulting to the row index.", rust_owner: "TableRow", rust: "key(key)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Row", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the row.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Row", prop: "children", ty: "React.ReactNode", default: "—", description: "Row cells; the port takes opaque elements rather than Table.Cell parts, so cell-level RAC props are not independently addressable.", rust_owner: "TableRow", rust: "new(cells)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Row", prop: "textValue", ty: "string", default: "—", description: "Pinned RAC typeahead string; cells are opaque, so rows without this value do not participate.", rust_owner: "TableRow", rust: "text_value(value)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.Row", prop: "isDisabled", ty: "boolean", default: "false", description: "Per-row disabled flag; the port expresses it as Table.disabledKeys rather than a row builder.", rust_owner: "Table", rust: "disabled_keys(keys)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Row", prop: "onAction", ty: "() => void", default: "—", description: "Pinned RAC per-row action; the port's callback is table-wide and receives the visible index.", rust_owner: "Table", rust: "on_row_click(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Row", prop: "hasChildItems", ty: "boolean", default: "—", description: "Whether nested rows exist, even if not loaded; the port infers this from nested TableRow children.", rust_owner: "TableRow", rust: "children(rows)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Cell", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for a data cell.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Cell", prop: "children", ty: "React.ReactNode", default: "—", description: "Cell content is an opaque element inside TableRow; there is no Cell struct to style or key independently.", rust_owner: "TableRow", rust: "new(cells)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Cell", prop: "textValue", ty: "string", default: "—", description: "Pinned RAC cell typeahead string; typeahead is row-level textValue only.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Cell", prop: "colSpan", ty: "number", default: "—", description: "Pinned RAC column span; flex columns cannot merge cells.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Cell", prop: "id", ty: "Key", default: "—", description: "Pinned RAC cell id.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Cell", prop: "focusMode", ty: "\"child\" | \"cell\"", default: "—", description: "Pinned RAC cell focus target for interactive descendants.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Cell", prop: "allowsArrowNavigation", ty: "boolean", default: "—", description: "Pinned RAC 1.20 arrow navigation inside a tab-mode cell.", rust_owner: "TableRow", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.SortableColumnHeader", prop: "sortDirection", ty: "\"ascending\" | \"descending\"", default: "—", description: "Current direction, handed to the sort-indicator closure rather than accepted as a header child prop.", rust_owner: "Table", rust: "indicator(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.SortableColumnHeader", prop: "showIndicator", ty: "boolean", default: "true", description: "Whether a sorted column draws its direction chevron.", rust_owner: "Table", rust: "show_indicator(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.SortableColumnHeader", prop: "indicator", ty: "React.ReactNode", default: "—", description: "Custom indicator; the port takes a closure handed sortDirection rather than cloning a React element with data-direction.", rust_owner: "Table", rust: "indicator(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.SortableColumnHeader", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the sortable header wrapper.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.SortableColumnHeader", prop: "children", ty: "React.ReactNode", default: "—", description: "Column label content; the port uses the TableColumn constructor text and uppercases it.", rust_owner: "TableColumn", rust: "new(label)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Footer", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the footer.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.Footer", prop: "children", ty: "React.ReactNode", default: "—", description: "Footer content such as pagination.", rust_owner: "Table", rust: "footer(content)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.ColumnResizer", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the resize handle.", rust_owner: "TableColumn", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.ResizableContainer", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the resizable wrapper.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.ResizableContainer", prop: "children", ty: "React.ReactNode", default: "—", description: "v3 wraps Content in a separate overflow-auto container; the port enables resizing per column and scrolls on ScrollContainer.", rust_owner: "TableColumn", rust: "allows_resizing(bool)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.ResizableContainer", prop: "onResizeStart", ty: "(widths: Map<Key, ColumnSize>) => void", default: "—", description: "Reports known pixel widths when pointer or keyboard resizing begins.", rust_owner: "Table", rust: "on_resize_start(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.ResizableContainer", prop: "onResize", ty: "(widths: Map<Key, ColumnSize>) => void", default: "—", description: "Reports each proposed pixel width map; feed values back through controlled TableColumn.width.", rust_owner: "Table", rust: "on_resize(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.ResizableContainer", prop: "onResizeEnd", ty: "(widths: Map<Key, ColumnSize>) => void", default: "—", description: "Reports the final known pixel widths after pointer or keyboard resizing ends.", rust_owner: "Table", rust: "on_resize_end(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.LoadMore", prop: "isLoading", ty: "boolean", default: "false", description: "Shows the load-more sentinel content; the port spells the v3 loading flag as is_pending.", rust_owner: "Table", rust: "is_pending(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.LoadMore", prop: "onLoadMore", ty: "() => void", default: "—", description: "Called when the sentinel intersects the scroll viewport.", rust_owner: "Table", rust: "on_load_more(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.LoadMore", prop: "scrollOffset", ty: "number", default: "1", description: "Pinned RAC inherited viewport-height margin before the sentinel counts as visible.", rust_owner: "Table", rust: "scroll_offset(offset)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Table.LoadMore", prop: "children", ty: "React.ReactNode", default: "—", description: "Loading indicator content; the port draws a built-in spinner and Loading… label.", rust_owner: "Table", rust: "is_pending(bool)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.LoadMore", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the sentinel row.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.LoadMoreContent", prop: "className", ty: "string", default: "—", description: "Additional CSS classes for the loading-indicator container.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Table.LoadMoreContent", prop: "children", ty: "React.ReactNode", default: "—", description: "Custom loading content; the port's sentinel content is built in.", rust_owner: "Table", rust: "is_pending(bool)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Collection", prop: "items", ty: "T[]", default: "—", description: "RAC Collection items for mixing static and dynamic cells; the port's analogue is the virtual row factory, not a cell-level collection mixer.", rust_owner: "Table", rust: "virtual_rows(count, identity, key, row)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Table.Collection", prop: "children", ty: "(item: T) => React.ReactNode", default: "—", description: "Per-item cell render prop; static rows and the virtual factory both produce whole TableRow values.", rust_owner: "Table", rust: "virtual_rows(count, identity, key, row)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "TableLayout", prop: "rowHeight", ty: "number | undefined", default: "48", description: "Fixed virtual row height; with virtual_rows this selects gpui uniform_list, caps at max_h, shrinks below it in a bounded parent, and pages by the visible viewport while skipping disabled stops.", rust_owner: "Table", rust: "row_height(height)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TableLayout", prop: "estimatedRowHeight", ty: "number | undefined", default: "—", description: "Estimated height for variable virtual rows; selects gpui list instead of uniform_list.", rust_owner: "Table", rust: "estimated_row_height(height)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TableLayout", prop: "headingHeight", ty: "number | undefined", default: "48", description: "Section-header height; this table has expandable rows, not section rows to size.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TableLayout", prop: "estimatedHeadingHeight", ty: "number | undefined", default: "—", description: "Variable section-header estimate; unused without section rows.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TableLayout", prop: "loaderHeight", ty: "number | undefined", default: "48", description: "Fixed height of the load-more row.", rust_owner: "Table", rust: "loader_height(height)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TableLayout", prop: "dropIndicatorThickness", ty: "number | undefined", default: "2", description: "Drop-indicator thickness for a drag API this port does not expose.", rust_owner: "Table", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "TableLayout", prop: "gap", ty: "number | undefined", default: "0", description: "Space between rows; v3 leaves this at 0.", rust_owner: "Table", rust: "gap(gap)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "TableLayout", prop: "padding", ty: "number | undefined", default: "0", description: "Padding around the list; v3 leaves this at 0.", rust_owner: "Table", rust: "padding(padding)", status: ImplementationStatus::Implemented },
];

const TABLE_PARTS: &[PartDoc] = &[
    PartDoc { name: "Table", slot: "table", description: "Root tray that owns variant, selection, sort, virtualization and load-more state.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.ScrollContainer", slot: "table-scroll-container", description: "Horizontal overflow wrapper around the content column so a wide table can scroll without stretching the footer.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Content", slot: "table-content", description: "Flex column standing in for the HTML table; border-separate table layout is not reproduced.", rust_owner: "Table", status: ImplementationStatus::Partial },
    PartDoc { name: "Table.Header", slot: "table-header", description: "Header row of column cells, including the optional select-all checkbox.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Column", slot: "table-column", description: "Configured header cell with sort, resize and row-header flags.", rust_owner: "TableColumn", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Body", slot: "table-body", description: "Row list, empty state and the primary-variant surface card.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Row", slot: "table-row", description: "One body row with optional nested children, selection key and typeahead text.", rust_owner: "TableRow", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Cell", slot: "table-cell", description: "Data cells are opaque elements inside TableRow; there is no Cell part to compose or span.", rust_owner: "TableRow", status: ImplementationStatus::Partial },
    PartDoc { name: "Table.SortableColumnHeader", slot: "table-sortable-column-header", description: "Sortable header wrapper and direction indicator drawn when allowsSorting is set.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.Footer", slot: "table-footer", description: "Optional row under the body, where v3 places pagination.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.ColumnResizer", slot: "table-column-resizer", description: "Trailing-edge resize handle drawn when allowsResizing is set; not a separately constructed child.", rust_owner: "TableColumn", status: ImplementationStatus::Partial },
    PartDoc { name: "Table.ResizableContainer", slot: "table-resizable-container", description: "v3's overflow-auto resize host is not a separate wrapper; resizing hangs off columns and horizontal scroll stays on ScrollContainer.", rust_owner: "Table", status: ImplementationStatus::Partial },
    PartDoc { name: "Table.LoadMore", slot: "table-load-more", description: "Intersection sentinel that fires onLoadMore, including virtual end-of-list detection.", rust_owner: "Table", status: ImplementationStatus::Implemented },
    PartDoc { name: "Table.LoadMoreContent", slot: "table-load-more-content", description: "Built-in spinner and Loading… label; caller children cannot replace that content.", rust_owner: "Table", status: ImplementationStatus::Partial },
    PartDoc { name: "Table.Collection", slot: "collection", description: "RAC mixer for static plus dynamic cells; the port exposes whole-row factories instead.", rust_owner: "Table", status: ImplementationStatus::Partial },
];

const TABLE_STATES: &[StateDoc] = &[
    StateDoc { state: "Hovered", selector: ":hover / [data-hovered=\"true\"]", description: "v3 tints cells with bg-surface/40 (secondary: bg-default/50); the port paints default.soft on the whole interactive row.", rust: "row.hover(default.soft)", status: ImplementationStatus::Partial },
    StateDoc { state: "Selected", selector: "[data-selected=\"true\"]", description: "v3 uses bg-surface/10 on cells; the port fills the row with accent.soft so selection still reads when the checkbox is off-screen.", rust: "row.bg(accent.soft)", status: ImplementationStatus::Partial },
    StateDoc { state: "Focus visible", selector: ":focus-visible / [data-focus-visible=\"true\"]", description: "Inset focus ring on the focused row, column header and resizer; one overlay stands in for v3's per-cell split ring. PageUp enters the first header — from the top of a virtual body, paging by viewport mid-body; Down and PageDown return to the first and last enabled body rows.", rust: "inset_focus_ring", status: ImplementationStatus::Partial },
    StateDoc { state: "Disabled row", selector: "[aria-disabled=\"true\"] / [data-disabled=\"true\"]", description: "disabledKeys rows are dimmed and removed from selection, actions and keyboard stops.", rust: "disabled_keys + disabled_opacity", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled table", selector: ":disabled / [aria-disabled=\"true\"]", description: "v3 styles a disabled table, but documents no prop that can disable the whole control.", rust: "—", status: ImplementationStatus::Unavailable },
    StateDoc { state: "Sortable", selector: "[data-allows-sorting=\"true\"]", description: "Sortable headers use the interactive cursor, hover fill and keyboard activation.", rust: "allows_sorting + cursor_pointer + sort_focus", status: ImplementationStatus::Implemented },
    StateDoc { state: "Resizing", selector: "[data-resizing=\"true\"] / [data-hovered=\"true\"]", description: "The handle grows to a full-height accent (or focus) bar while dragged, hovered or keyboard-resizing.", rust: "is_resizing / group_hover / resize_focused", status: ImplementationStatus::Implemented },
    StateDoc { state: "Empty", selector: "[data-empty] / renderEmptyState", description: "Caller empty-state content is centered in the body when there are no rows.", rust: "empty_state", status: ImplementationStatus::Implemented },
    StateDoc { state: "Loading", selector: "Table.LoadMore isLoading", description: "Pending sentinel shows the built-in spinner while onLoadMore can still fire from intersection.", rust: "is_pending + on_load_more", status: ImplementationStatus::Implemented },
    StateDoc { state: "Dragging", selector: "[data-dragging=\"true\"]", description: "RAC row drag opacity; this port has no table drag-and-drop.", rust: "—", status: ImplementationStatus::Unavailable },
    StateDoc { state: "Drop target", selector: "[data-drop-target=\"true\"]", description: "RAC drop-target accent; unused without dragAndDropHooks.", rust: "—", status: ImplementationStatus::Unavailable },
];

const TABLE_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".table-root", value: "relative grid w-full overflow-clip", description: "The port is a full-width overflow-hidden flex tray, not a CSS grid with minmax(0,1fr) tracks.", rust: "w_full + overflow_hidden", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table-root--primary", value: "bg-surface-secondary px-1 pb-1; radius min(32px, radius * 2.5)", description: "Gray tray inset and overlay-sized radius around the surface card.", rust: "surface_secondary + px/pb(px(4.)) + radius_lg * 2.5 min 32", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".table-root--secondary", value: "no root fill, padding or rounding", description: "Secondary leaves the root flat; first/last header rounding and per-cell hover fills are not reproduced.", rust: "variant Secondary skips the tray", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__scroll-container", value: "scrollbar overflow-x-auto", description: "Horizontal input scrolls the content column; vertical input is not remapped sideways. Custom scrollbar styling is absent.", rust: "overflow_x_scroll", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__content", value: "w-full border-separate border-spacing-0 text-sm", description: "14px type and 20px line height match; the port is a flex column rather than a border-separate table, so column tracks resolve per row and a table narrower than its columns times their widest cell staggers the body against the header.", rust: "min_w_full flex_col text_size(px(14.)) line_height(px(20.))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__header", value: "border-b border-separator/50 bg-surface-secondary", description: "Header rule and secondary fill on primary; the separator is rendered at 50% alpha.", rust: "border_b_1 + separator.alpha(0.5) + surface_secondary", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__column", value: "px-4 py-2.5 text-xs font-medium text-muted", description: "16/10px inset and 12px type with 16px lines match; the port uses medium caller-case labels, but short vertical column separators are not drawn.", rust: "px(16.) py(10.) text_size(12.) line_height(16.) MEDIUM + label.clone()", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__column::after", value: "h-4 w-px rounded-sm bg-separator", description: "Short column separators are not drawn; only a resizer replaces that edge when allowsResizing is set.", rust: "—", status: ImplementationStatus::Unavailable },
    StyleDoc { class_or_token: ".table__sortable-column-header", value: "flex items-center justify-between", description: "Label and indicator share the header cell with a 4px gap rather than space-between.", rust: "flex items_center gap(px(4.))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__sortable-column-indicator", value: "size-3 rotate-180 when descending", description: "12px chevron matches; ascending/descending are separate glyphs rather than a 100ms rotate.", rust: "svg size(px(12.)) + CHEVRON_UP/DOWN", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__body", value: "min(32px, --radius-2xl) corner rounding on first/last cells", description: "Primary clips the body to radius_2xl; secondary does not undo per-cell rounding because those cell radii are not drawn.", rust: "radius_2xl.min(px(32.)) + overflow_hidden on primary", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__row", value: "border-b border-separator/50; last-child border-b-0", description: "Rows use the separator at 50% alpha, and the final visible row omits the bottom border.", rust: "border_b_1 + separator.alpha(0.5) except final visible row", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__cell", value: "px-4 py-3 align-middle text-sm bg-surface", description: "16/12px inset matches; cell fill lives on the primary body, not on each cell, and hover/selected paints the row.", rust: "px(16.) py(12.)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__cell[data-tree-column]", value: "padding-inline-start: 1rem * var(--table-row-level, 1)", description: "v3 indents 16px per 1-based level; the port uses 12 + 20 * depth and only when depth > 0.", rust: "pl(px(12. + 20. * depth))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__footer", value: "flex items-center px-4 py-2.5", description: "Footer inset matches.", rust: "flex items_center px(16.) py(10.)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".table__column-resizer", value: "h-4 w-px rounded-sm; hover/resizing h-full w-0.5 bg-accent; px-2 hit area", description: "Resting line, hover/drag bar and 8px grab margin match; touch-none is implicit in mouse/key handling.", rust: "h(16.) w(1.) hairline_radius + group_hover/is_resizing + right(-8.)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".table__resizable-container", value: "relative scrollbar overflow-auto", description: "No separate overflow-auto host; column handles live in the header and the x-scroller is ScrollContainer.", rust: "allows_resizing handle + overflow_x_scroll", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".table__load-more-content", value: "flex items-center justify-center gap-2 py-2", description: "8px gap and padding around the built-in spinner.", rust: "gap(px(8.)) py(px(8.))", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".table__row:is(:focus-visible, [data-focus-visible]) cells", value: "split inset 2px focus ring across first/middle/last cells", description: "One overlay ring is painted on the row instead of three-sided per-cell shadows.", rust: "inset_focus_ring on the focused row", status: ImplementationStatus::Partial },
];

pub(super) const TABLE: ReferenceMetadata = ReferenceMetadata {
    page: "Table",
    import_line: "use herogpui::components::table::Table;",
    source_module: "table",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(data-display)/table.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/table/table.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.21.0/packages/react-aria-components/src/Table.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/table.css",
    required_parts: TABLE_REQUIRED_PARTS,
    api: TABLE_API,
    parts: TABLE_PARTS,
    states: TABLE_STATES,
    styling: TABLE_STYLING,
};

const BADGE_REQUIRED_PARTS: &[&str] = &["Badge", "Badge.Anchor", "Badge.Label"];

const BADGE_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Badge",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Badge content (text, number, or icon); omitted children render the dot badge. v3 auto-wraps plain string and number children in `Badge.Label`; GPUI elements carry no type a parent can intercept, so the wrap is explicit via `BadgeLabel` and bare `Badge` children draw without the label padding.",
        rust_owner: "Badge",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Badge",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the root element.",
        rust_owner: "Badge",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Badge",
        prop: "color",
        ty: "\"default\" | \"accent\" | \"success\" | \"warning\" | \"danger\"",
        default: "\"default\"",
        description: "Color role of the badge; fills and label colors resolve through the badge.css cascade.",
        rust_owner: "Badge",
        rust: "color(Color)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Badge",
        prop: "variant",
        ty: "\"primary\" | \"secondary\" | \"soft\"",
        default: "\"primary\"",
        description: "Visual style variant: solid role fill, default fill with a colored label, or the soft mix.",
        rust_owner: "Badge",
        rust: "variant(BadgeVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Badge",
        prop: "size",
        ty: "\"sm\" | \"md\" | \"lg\"",
        default: "\"md\"",
        description: "Sets the min square, radius step, and type size of the badge.",
        rust_owner: "Badge",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Badge",
        prop: "placement",
        ty: "\"top-right\" | \"top-left\" | \"bottom-right\" | \"bottom-left\"",
        default: "\"top-right\"",
        description: "Corner of the anchor the badge points at.",
        rust_owner: "Badge",
        rust: "placement(BadgePlacement)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Badge.Anchor",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "The element to anchor the badge to, plus the `Badge` itself composed as a later child.",
        rust_owner: "BadgeAnchor",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Badge.Anchor",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the anchor wrapper.",
        rust_owner: "BadgeAnchor",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Badge.Label",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Label text content. v3 wraps plain text in this slot automatically; the port's wrap is explicit because nothing can intercept a plain child, so the `px-0.5` padding only applies through `BadgeLabel`.",
        rust_owner: "BadgeLabel",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Badge.Label",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the label slot.",
        rust_owner: "BadgeLabel",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const BADGE_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Badge",
        slot: "badge",
        description: "Root indicator on the `.badge` BEM classes: an absolutely positioned min-box square (`min-h-7 min-w-7` by size) with a radius step per size, medium text, a 2px gap, and the unconditional 1px page-background ring; empty children render the dot. The port is a block-level flex (no inline-flex) and approximates v3's corner translate with a fixed inset, so it is Partial.",
        rust_owner: "Badge",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Badge.Anchor",
        slot: "badge-anchor",
        description: "Positioning wrapper on the `.badge-anchor` BEM class: `relative inline-flex shrink-0`, carrying the anchored element plus the badge. gpui-pre 0.3.3 has no inline-flex, so the wrapper hugs its content only inside a flex parent; the ported `flex_shrink_0` keeps it from compressing in an overflowing row.",
        rust_owner: "BadgeAnchor",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Badge.Label",
        slot: "badge-label",
        description: "Label text slot on the `.badge__label` BEM class — `px-0.5`, the only horizontal padding in the badge sheet. v3 auto-wraps plain string and number children of the root here; the port makes that wrap explicit with the `BadgeLabel` part.",
        rust_owner: "BadgeLabel",
        status: ImplementationStatus::Implemented,
    },
];

// `.badge` and `.badge-anchor` declare no state utilities and the docs name no
// interactive states: a badge is a static display indicator, not a control.
const BADGE_STATES: &[StateDoc] = &[];

const BADGE_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".badge",
        value: "inline-flex shrink-0 items-center justify-center gap-0.5 font-medium; min-h-7 min-w-7 rounded-3xl text-xs leading-[1.34]; border: 1px solid var(--background); background-clip: padding-box",
        description: "28px min square, 12px medium text at the 1.34 leading, 2px gap, and the unconditional 1px page-background ring. The port is a block-level flex (no inline-flex) and gpui-pre 0.3.3 has no background-clip, so the ring paints over the fill edge instead of clipping the fill to the padding box.",
        rust: "flex + items_center + justify_center + gap(px(2.)) + min_w(px(28.)) + min_h(px(28.)) + control_radius + text_size(px(12.)) + line_height(1.34) + FontWeight::MEDIUM + flex_shrink_0 + border_1(colors.background)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".badge--sm / --md / --lg",
        value: "min-h-4 min-w-4 rounded-xl text-[10px] leading-[1.34] / min-h-7 min-w-7 rounded-3xl text-xs / min-h-8 min-w-8 rounded-2xl text-sm leading-[1.43]",
        description: "16px/28px/32px min squares at the 12px/24px/16px radii with 10/12/14px text; `--md` only restates the base. The radius is a step per size, not a pill, and the leadings are Tailwind's unitless multipliers resolved against each size's own text.",
        rust: "(px(16.), px(10.), small_radius) / (px(28.), px(12.), control_radius) / (px(32.), px(14.), soft_radius)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge-anchor",
        value: "relative inline-flex shrink-0",
        description: "Positioning wrapper; `inline-flex` is not portable, so the port is a block-level flex that hugs content inside a flex parent and keeps `shrink-0`.",
        rust: "relative + flex + flex_shrink_0",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".badge__label",
        value: "px-0.5",
        description: "Two-pixel label padding — the only horizontal padding in the badge sheet; the badge itself has none.",
        rust: "BadgeLabel => px(px(2.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--{color}",
        value: "--badge-fg: var(--{color}-soft-foreground) (--default labels in --default-foreground)",
        description: "The five color classes only relabel the badge; they set no fill. The soft foreground is the muted label color shared by secondary and soft.",
        rust: "muted_foreground() => role.soft_foreground(colors.foreground); colors.default.foreground for default",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--primary",
        value: "— (no properties of its own)",
        description: "The base tokens hold until a compound rule fills with the role; the port resolves the whole pair in `paint()`.",
        rust: "BadgeVariant::Primary => paint() => (role.color, role.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--secondary",
        value: "default background with colored text (base behavior)",
        description: "Keeps the base `--badge-bg: var(--default)` whatever the color; only the label follows the color class.",
        rust: "BadgeVariant::Secondary => paint() => (colors.default.color, muted_foreground())",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--soft.badge--{color}",
        value: "--badge-bg: var(--{color}-soft); --badge-fg: var(--{color}-soft-foreground)",
        description: "The soft compound cells fill with the per-role soft mix, lighter than the role itself, and keep the soft label.",
        rust: "BadgeVariant::Soft => paint() => (role.soft(), role.soft_foreground(colors.foreground))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--primary.badge--{color}",
        value: "--badge-bg: var(--{color}); --badge-fg: var(--{color}-foreground)",
        description: "The primary compound cells fill with the role itself and label in its foreground.",
        rust: "BadgeVariant::Primary => paint() => (role.color, role.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".badge--top-right",
        value: "absolute top-0 right-0; transform: translate(25%, -25%)",
        description: "Corner overlay overhanging a quarter of the badge's own box (4px sm, 7px md, 8px lg). gpui-pre 0.3.3 has no div-level transform and a percentage inset would resolve against the containing block, so the port insets the corner by -size/4 — a quarter of the min box; a badge grown past its min box overhangs less than v3's translate would, and only dot and min-box-fitting badges are exact.",
        rust: "BadgePlacement::TopRight => top(-size/4) + right(-size/4)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".badge--top-left",
        value: "absolute top-0 left-0; transform: translate(-25%, -25%)",
        description: "Same quarter-box overhang at the top-left corner, with the same min-box approximation as top-right.",
        rust: "BadgePlacement::TopLeft => top(-size/4) + left(-size/4)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".badge--bottom-right",
        value: "absolute right-0 bottom-0; transform: translate(25%, 25%)",
        description: "Same quarter-box overhang at the bottom-right corner, with the same min-box approximation.",
        rust: "BadgePlacement::BottomRight => bottom(-size/4) + right(-size/4)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".badge--bottom-left",
        value: "absolute bottom-0 left-0; transform: translate(-25%, 25%)",
        description: "Same quarter-box overhang at the bottom-left corner, with the same min-box approximation.",
        rust: "BadgePlacement::BottomLeft => bottom(-size/4) + left(-size/4)",
        status: ImplementationStatus::Partial,
    },
];

pub(super) const BADGE: ReferenceMetadata = ReferenceMetadata {
    page: "Badge",
    import_line: "use herogpui::components::badge::{Badge, BadgeAnchor, BadgeLabel};",
    source_module: "badge",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(data-display)/badge.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/badge/badge.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/badge.css",
    required_parts: BADGE_REQUIRED_PARTS,
    api: BADGE_API,
    parts: BADGE_PARTS,
    states: BADGE_STATES,
    styling: BADGE_STYLING,
};

const CHIP_REQUIRED_PARTS: &[&str] = &["Chip", "Chip.Label"];

const CHIP_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Chip",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Chip content, rendered verbatim in composed order (an icon, a dot, the label, a trailing element). v3 auto-wraps plain string and number children in `Chip.Label`; GPUI elements carry no type a parent can intercept, so the wrap is explicit and bare `Chip` children draw without the label padding.",
        rust_owner: "Chip",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Chip",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the root element.",
        rust_owner: "Chip",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Chip",
        prop: "color",
        ty: "\"default\" | \"accent\" | \"success\" | \"warning\" | \"danger\"",
        default: "\"default\"",
        description: "Color role of the chip; fills and label colors resolve through the chip.css cascade.",
        rust_owner: "Chip",
        rust: "color(Color)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Chip",
        prop: "variant",
        ty: "\"primary\" | \"secondary\" | \"tertiary\" | \"soft\"",
        default: "\"secondary\"",
        description: "Visual style variant: solid role fill, the default fill, a transparent fill, or the soft mix.",
        rust_owner: "Chip",
        rust: "variant(ChipVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Chip",
        prop: "size",
        ty: "\"sm\" | \"md\" | \"lg\"",
        default: "\"md\"",
        description: "Sets the padding and type size of the chip; a chip has no height of its own at any size.",
        rust_owner: "Chip",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Chip.Label",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Label text content. v3 wraps plain text in this slot automatically; the port's wrap is explicit because nothing can intercept a plain child, so the `px-0.5` padding only applies through `ChipLabel`.",
        rust_owner: "ChipLabel",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Chip.Label",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the label slot.",
        rust_owner: "ChipLabel",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const CHIP_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Chip",
        slot: "chip",
        description: "Root on the `.chip` BEM classes: a padded flex row around one text line — no height, no border at any variant or color — with a 2px gap and the soft radius. gpui-pre 0.3.3 has no inline-flex or `w-fit`, so the port is a block-level flex that hugs content only inside a flex parent.",
        rust_owner: "Chip",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Chip.Label",
        slot: "chip-label",
        description: "Label text slot on the `.chip__label` BEM class — `px-0.5`; a chip root's arbitrary icon or dot children take no label padding. v3 auto-wraps plain string and number children of the root here; the port makes that wrap explicit with the `ChipLabel` part.",
        rust_owner: "ChipLabel",
        status: ImplementationStatus::Implemented,
    },
];

// `.chip` declares no state utilities and the docs name no interactive states:
// a chip is a static display element, not a control.
const CHIP_STATES: &[StateDoc] = &[];

const CHIP_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".chip",
        value: "inline-flex w-fit shrink-0 items-center gap-0.5 rounded-2xl px-2 py-0.5 text-xs leading-5 font-medium",
        description: "8px/2px padding around one 12px medium line, 16px soft radius, 2px gap, and no border. The base `leading-5` holds at every size: compiled Tailwind 4 lowers it to the `--tw-leading` custom property that every `text-*` utility consumes, so the size rules' re-applied `text-xs`/`text-sm` keep the 20px line. `inline-flex` and `w-fit` are not portable: the port is a block-level flex that hugs content only inside a flex parent (kept `shrink-0`).",
        rust: "flex + items_center + gap(px(2.)) + px(px(8.)) + py(px(2.)) + text_size(px(12.)) + line_height(px(20.)) at every size + FontWeight::MEDIUM + soft_radius + flex_shrink_0",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".chip__label",
        value: "px-0.5",
        description: "Two-pixel label padding, living on the label part and nowhere else.",
        rust: "ChipLabel => px(px(2.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--sm / --md / --lg",
        value: "px-1 py-0 text-xs / text-xs / px-3 py-1 text-sm font-medium",
        description: "4px/0, 8px/2px (the base restated), and 12px/4px paddings with 12/12/14px text on the one 20px line the base `leading-5` sets; no size touches the radius or adds a height.",
        rust: "(px(4.), px(0.), px(12.), px(20.)) / (px(8.), px(2.), px(12.), px(20.)) / (px(12.), px(4.), px(14.), px(20.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--{color}",
        value: "--chip-fg: var(--{color}-soft-foreground) (--default labels in --default-foreground)",
        description: "The five color classes only relabel the chip; they set no fill. The port resolves `currentColor` to the theme's foreground because GPUI has no ancestor color context.",
        rust: "muted_foreground() => role.soft_foreground(colors.foreground); colors.default.foreground for default",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--primary",
        value: "— (no properties of its own)",
        description: "The base tokens hold until a compound rule fills with the role; the port resolves the whole pair in `paint()`.",
        rust: "ChipVariant::Primary => paint() => (role.color, role.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--secondary",
        value: "— (no additional styles; the base --chip-bg: var(--default) holds)",
        description: "The docs' styling reference calls secondary \"with border\", but the pinned sheet declares nothing for it and no chip rule draws a border; the color class only relabels.",
        rust: "ChipVariant::Secondary => paint() => (colors.default.color, muted_foreground())",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--tertiary",
        value: "--chip-bg: transparent",
        description: "Tertiary only clears the fill and paints no background; chip.css declares no border for any chip.",
        rust: "ChipVariant::Tertiary => paint() => no background",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--primary.chip--{color}",
        value: "--chip-bg: var(--{color}); --chip-fg: var(--{color}-foreground)",
        description: "The primary compound cells fill with the role itself and label in its foreground (default has no compound cell, so the base tokens hold).",
        rust: "ChipVariant::Primary => paint() => (role.color, role.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".chip--{color}.chip--soft",
        value: "--chip-bg: var(--{color}-soft); --chip-fg: var(--{color}-soft-foreground)",
        description: "The soft compound cells fill with the per-role soft mix — the default role mixes at 50%, not the 15% the accent and status roles use — and keep the soft label.",
        rust: "ChipVariant::Soft => paint() => (role.soft(), muted_foreground())",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const CHIP: ReferenceMetadata = ReferenceMetadata {
    page: "Chip",
    import_line: "use herogpui::components::chip::{Chip, ChipLabel};",
    source_module: "chip",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(data-display)/chip.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/chip/chip.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/chip.css",
    required_parts: CHIP_REQUIRED_PARTS,
    api: CHIP_API,
    parts: CHIP_PARTS,
    states: CHIP_STATES,
    styling: CHIP_STYLING,
};
