//! media reference metadata.

use super::*;

const AVATAR_REQUIRED_PARTS: &[&str] = &["Avatar", "Avatar.Image", "Avatar.Fallback"];

const AVATAR_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Avatar",
        prop: "size",
        ty: "'sm' | 'md' | 'lg'",
        default: "'md'",
        description: "Avatar size: 32/40/48px edge, with `sm` rounding one step tighter and `lg` stepping the fallback text up to 16px.",
        rust_owner: "Avatar",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar",
        prop: "color",
        ty: "'default' | 'accent' | 'success' | 'warning' | 'danger'",
        default: "'default'",
        description: "Fallback color theme. The base avatar fills `bg-default` for every color — the color recolours the initials via the soft-foreground token.",
        rust_owner: "Avatar",
        rust: "color(Color)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar",
        prop: "variant",
        ty: "'default' | 'soft'",
        default: "'default'",
        description: "Visual style variant. `soft` clears the base fill and paints `bg-{role}-soft` with the same soft foreground.",
        rust_owner: "Avatar",
        rust: "variant(AvatarVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "src",
        ty: "string",
        default: "—",
        description: "Image source URL. A plain string or path loads through gpui's asset system (a parseable URI is fetched, anything else is an embedded resource); the gpui `ImageSource::Image` / `Render` / `Custom` variants are the explicit parts for images the app already holds or loads itself.",
        rust_owner: "Avatar",
        rust: "src(ImageSource)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "onLoad",
        ty: "(event: SyntheticEvent<HTMLImageElement>) => void",
        default: "—",
        description: "Callback when the image loads successfully and replaces the fallback. Fires once per source, on the first observed success, outside the layout phase; there is no event payload to hand over.",
        rust_owner: "Avatar",
        rust: "on_load(handler)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "onError",
        ty: "(event: SyntheticEvent<HTMLImageElement>) => void",
        default: "—",
        description: "Callback when there's an error loading the image; the fallback initials replace the image on that same failure. Fires once per source; no event payload.",
        rust_owner: "Avatar",
        rust: "on_error(handler)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "srcSet",
        ty: "string",
        default: "—",
        description: "The image `srcset` attribute for responsive images. Browser-only: gpui's asset system resolves one resource per source and never selects between candidates.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "sizes",
        ty: "string",
        default: "—",
        description: "The image `sizes` attribute. Browser-only hint for `srcset` selection; there is no viewport-density image pick to hint.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "alt",
        ty: "string",
        default: "—",
        description: "Alternative text for the image. gpui-pre 0.3.3 has no accessibility tree to carry it.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "asChild",
        ty: "boolean",
        default: "false",
        description: "Merges props onto a child element instead of rendering a native `img`. There is no DOM element graph to merge onto; a gpui `ImageSource::Custom` loader is the equivalent seam for a custom image component.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "crossOrigin",
        ty: "'anonymous' | 'use-credentials'",
        default: "—",
        description: "CORS setting for the image request. Browser fetch metadata with no analogue in gpui's asset system.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "loading",
        ty: "'eager' | 'lazy'",
        default: "—",
        description: "Native lazy loading attribute. Gpui loads a source when it is first observed; there is no viewport-distance scheduler to defer with.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Image",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Avatar.Fallback",
        prop: "delayMs",
        ty: "number",
        default: "—",
        description: "Delay before showing the fallback, measured from mount so a slow load does not flash the initials behind it. A success inside the window renders before it elapses; a failure inside it waits for the same window rather than restarting it.",
        rust_owner: "Avatar",
        rust: "delay_ms(u64)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar.Fallback",
        prop: "color",
        ty: "'default' | 'accent' | 'success' | 'warning' | 'danger'",
        default: "—",
        description: "Override color from parent. Its own documented prop, not an alias: it overrides the parent `color` for everything the fallback paints, while the parent color still governs the rest.",
        rust_owner: "Avatar",
        rust: "fallback_color(Color)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Avatar.Fallback",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Avatar",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const AVATAR_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Avatar",
        slot: "avatar",
        description: "Root container on the `.avatar` BEM class: `relative flex size-10 shrink-0 items-center justify-center overflow-hidden rounded-3xl bg-default`. The name initials come from the port's own `name` builder (v3 has no `name` prop); the load progress and the `delayMs` window key on the image source.",
        rust_owner: "Avatar",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Avatar.Image",
        slot: "avatar__image",
        description: "`absolute inset-0 aspect-square size-full` image with an opacity transition. The port draws the loaded image directly inside the root (`img(data).size_full().rounded(radius)`), applying the root radius to keep the image inside the Avatar boundary, and does not animate the swap.",
        rust_owner: "Avatar",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Avatar.Fallback",
        slot: "avatar__fallback",
        description: "`flex size-full items-center justify-center bg-default text-sm font-medium` fallback box. The separate fallback container centers initials or custom `fallback` children with 14px/20px medium text (16px/24px for large avatars), painted `text-{role}-soft-foreground`.",
        rust_owner: "Avatar",
        status: ImplementationStatus::Implemented,
    },
];

// `.avatar` declares no state utilities and the docs name no interactive
// states: an avatar is a static display, not a control.
const AVATAR_STATES: &[StateDoc] = &[];

const AVATAR_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".avatar",
        value: "relative flex size-10 shrink-0 items-center justify-center overflow-hidden rounded-3xl bg-default",
        description: "40px square at the 24px radius on `bg-default` for every color; the color only recolours the initials.",
        rust: "flex + items_center + justify_center + size(px(40.)) + flex_shrink_0 + overflow_hidden + control_radius + colors.default.color",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".avatar--sm / .avatar--md / .avatar--lg",
        value: "size-8 rounded-2xl / (no additional styles) / size-12 rounded-3xl",
        description: "32/40/48px boxes; `sm` rounds one step tighter (at 32px a 24px radius would be all but a circle) and `md` restates nothing.",
        rust: "Size::Sm => px(32.) + soft_radius; Size::Md => px(40.); Size::Lg => px(48.) + control_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".avatar--lg .avatar__fallback",
        value: "text-base",
        description: "The large avatar steps fallback text from 14px/20px to 16px/24px.",
        rust: "let font = if self.large { px(16.) } else { px(14.) }",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".avatar__fallback",
        value: "flex size-full items-center justify-center bg-default text-sm font-medium",
        description: "A separate full-size fallback container centers initials or custom children with 14px/20px medium text in the color's soft foreground.",
        rust: "fallback size_full + items_center + justify_center + text_size(font) + line_height(leading) + FontWeight::MEDIUM + soft_foreground(colors.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".avatar__image",
        value: "absolute inset-0 aspect-square size-full; transition-opacity duration-250 motion-reduce:transition-none",
        description: "The port draws the loaded image as the root's child, applies the same radius so every renderer clips it to the Avatar boundary, and does not interpolate the swap.",
        rust: "img(data).size_full().rounded(radius)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".avatar__fallback--{color}",
        value: "text-{role}-soft-foreground; --default resolves to --default-foreground",
        description: "The five color classes only recolour the fallback text; the fill stays `bg-default` in the base variant.",
        rust: "fb_role.soft_foreground(colors.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".avatar--soft / .avatar--soft .avatar__fallback--{color}",
        value: "bg-transparent; compound cells fill bg-{role}-soft with the same soft foreground",
        description: "The soft variant clears the base fill and the compound rules paint the per-role soft mix behind the same soft-foreground text.",
        rust: "AvatarVariant::Soft => (fb_role.soft(), soft_fg)",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const AVATAR: ReferenceMetadata = ReferenceMetadata {
    page: "Avatar",
    import_line: "use herogpui::components::avatar::Avatar;",
    source_module: "avatar",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(media)/avatar.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/avatar/avatar.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/avatar.css",
    required_parts: AVATAR_REQUIRED_PARTS,
    api: AVATAR_API,
    parts: AVATAR_PARTS,
    states: AVATAR_STATES,
    styling: AVATAR_STYLING,
};
