//! navigation reference metadata.

use super::*;

const PAGINATION_REQUIRED_PARTS: &[&str] = &[
    "Pagination",
    "Pagination.Summary",
    "Pagination.Content",
    "Pagination.Item",
    "Pagination.Link",
    "Pagination.Previous",
    "Pagination.PreviousIcon",
    "Pagination.Next",
    "Pagination.NextIcon",
    "Pagination.Ellipsis",
];

const PAGINATION_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Pagination",
        prop: "size",
        ty: "\"sm\" | \"md\" | \"lg\"",
        default: "\"md\"",
        description: "Size of the pagination items.",
        rust_owner: "Pagination",
        rust: "size(Size)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Pagination parts; the GPUI port generates the compound structure.",
        rust_owner: "Pagination",
        rust: "new(id, page, total)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Summary",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the summary.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.Summary",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Summary content such as a visible item range.",
        rust_owner: "Pagination",
        rust: "summary(text)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Content",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item container.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.Content",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Pagination items; generated from page and total in GPUI.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for one item wrapper.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.Item",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "One Link, Previous, Next or Ellipsis part.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Link",
        prop: "isActive",
        ty: "boolean",
        default: "false",
        description: "Marks the current page and is handed to the link render closure.",
        rust_owner: "Pagination",
        rust: "link(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.Link",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables one page link by page number.",
        rust_owner: "Pagination",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.Link",
        prop: "onPress",
        ty: "(e: PressEvent) => void",
        default: "—",
        description: "Reports a normalized pointer or keyboard press with its page number.",
        rust_owner: "Pagination",
        rust: "on_change(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Link",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for a link.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.Link",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Page-link content, with page and active state available to the closure.",
        rust_owner: "Pagination",
        rust: "link(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.Previous / Pagination.Next",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables Previous with key 0 or Next with total + 1.",
        rust_owner: "Pagination",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.Previous / Pagination.Next",
        prop: "onPress",
        ty: "(e: PressEvent) => void",
        default: "—",
        description: "Reports the destination page through the shared callback.",
        rust_owner: "Pagination",
        rust: "on_change(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.Previous / Pagination.Next",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for a navigation button.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.Previous / Pagination.Next",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Whole button content; GPUI exposes the icon children separately.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Pagination.PreviousIcon",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the previous icon.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.PreviousIcon",
        prop: "children",
        ty: "ReactNode",
        default: "Default chevron SVG",
        description: "Custom icon replacing the previous chevron.",
        rust_owner: "Pagination",
        rust: "previous_icon(icon)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.NextIcon",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the next icon.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Pagination.NextIcon",
        prop: "children",
        ty: "ReactNode",
        default: "Default chevron SVG",
        description: "Custom icon replacing the next chevron.",
        rust_owner: "Pagination",
        rust: "next_icon(icon)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Pagination.Ellipsis",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the ellipsis.",
        rust_owner: "Pagination",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const PAGINATION_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Pagination",
        slot: "pagination",
        description: "Root page-navigation container.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Pagination.Summary",
        slot: "pagination-summary",
        description: "Optional summary before the links.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Pagination.Content",
        slot: "pagination-content",
        description: "Container for navigation items.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Pagination.Item",
        slot: "pagination-item",
        description: "Implicit wrapper around one item.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Pagination.Link",
        slot: "pagination-link",
        description: "Focusable page-number button.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Pagination.Previous",
        slot: "pagination-previous",
        description: "Button targeting the previous page.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Pagination.PreviousIcon",
        slot: "pagination-previous-icon",
        description: "Replaceable previous-page icon.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Pagination.Next",
        slot: "pagination-next",
        description: "Button targeting the next page.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Pagination.NextIcon",
        slot: "pagination-next-icon",
        description: "Replaceable next-page icon.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Pagination.Ellipsis",
        slot: "pagination-ellipsis",
        description: "Non-interactive omitted-page marker.",
        rust_owner: "Pagination",
        status: ImplementationStatus::Implemented,
    },
];

const PAGINATION_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Active page",
        selector: "[data-active=\"true\"], [aria-current=\"page\"]",
        description: "Current page with tertiary-button fill.",
        rust: "n == page + link(page, active)",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Hovered",
        selector: ":hover, [data-hovered=\"true\"]",
        description: "Enabled link or nav-button hover fill.",
        rust: "hover(default.hover())",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: ":focus-visible, [data-focus-visible=\"true\"]",
        description: "Keyboard focus ring.",
        rust: "tab_stop_handle + with_focus_ring",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ":disabled, [aria-disabled=\"true\"]",
        description: "No press or tab stop, with disabled opacity.",
        rust: "is_disabled / disabled_keys gates",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Pressed",
        selector: ":active, [data-pressed=\"true\"]",
        description: "Size-specific scale and default-hover fill.",
        rust: "anim::pressed / pressed_with_background",
        status: ImplementationStatus::Partial,
    },
];

const PAGINATION_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".pagination",
        value: "flex w-full flex-col items-center justify-between gap-4 sm:flex-row",
        description: "Responsive root layout.",
        rust: "flex row + items_center + justify_between + gap(px(16.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".pagination__summary",
        value: "flex items-center gap-2 self-start text-sm text-muted",
        description:
            "Summary text follows the size-specific 12/16, 14/20 and 16/24 font/line-height pairs.",
        rust: "flex + gap(px(8.)) + cell_text + cell_leading + muted",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".pagination__content",
        value: "flex items-center gap-1 self-start",
        description: "Link-row layout.",
        rust: "row flex + items_center + gap(px(4.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".pagination__item",
        value: "inline-flex",
        description: "One compound item wrapper.",
        rust: "implicit direct child",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".pagination__link",
        value: "size-9 md:size-8 rounded-3xl text-sm font-medium",
        description: "Default link geometry and typography.",
        rust: "cell Size::Md 32px + control_radius + text_size",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination__link transitions",
        value: "transform 250ms ease-smooth; background/box-shadow 100ms ease-out",
        description: "Link state interpolation.",
        rust: "instant active refinements; press geometry has no timeline",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".pagination__link hover/pressed",
        value: "background default-hover",
        description: "Shared hover and pressed fill.",
        rust: "hover_bg / pressed_bg = colors.default.hover()",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination__link[data-active=\"true\"]",
        value: "default background; default-hover interactive background",
        description: "Tertiary-button active-page treatment.",
        rust: "active branch default.color + shared hover/pressed",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination__ellipsis",
        value: "size-9 md:size-8 text-sm text-muted",
        description: "Ellipsis geometry and colour.",
        rust: "size(cell) + cell_text + colors.muted",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination__link--nav",
        value: "w-auto gap-1.5 px-2.5",
        description: "Previous and Next width, gap and padding.",
        rust: "content width + gap(px(6.)) + nav_padding 10px",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination--sm .pagination__link",
        value: "size-8 md:size-7 text-xs; pressed scale(0.98)",
        description: "Small link variant.",
        rust: "Size::Sm => 28px / 12px / PRESSED_SCALE_SUBTLE",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination--sm .pagination__link--nav",
        value: "px-2",
        description: "Small navigation padding.",
        rust: "Size::Sm => nav_padding px(8.)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination--lg .pagination__link",
        value: "size-10 md:size-9 text-base; pressed scale(0.96)",
        description: "Large link variant.",
        rust: "Size::Lg => 36px / 16px / PRESSED_SCALE_FIRM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".pagination--lg .pagination__link--nav",
        value: "px-3",
        description: "Large navigation padding.",
        rust: "Size::Lg => nav_padding px(12.)",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const PAGINATION: ReferenceMetadata = ReferenceMetadata {
    page: "Pagination",
    import_line: "use herogpui::components::pagination::Pagination;",
    source_module: "pagination",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/pagination.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/pagination/pagination.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/pagination.css",
    required_parts: PAGINATION_REQUIRED_PARTS,
    api: PAGINATION_API,
    parts: PAGINATION_PARTS,
    states: PAGINATION_STATES,
    styling: PAGINATION_STYLING,
};

const TABS_REQUIRED_PARTS: &[&str] = &[
    "Tabs",
    "Tabs.ListContainer",
    "Tabs.List",
    "Tabs.Tab",
    "Tabs.Separator",
    "Tabs.Indicator",
    "Tabs.Panel",
];

const TABS_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Tabs",
        prop: "align",
        ty: "\"start\" | \"center\" | \"end\"",
        default: "\"center\"",
        description: "Aligns content inside each tab, independently of the panel and nested tab lists. Start/end use the port's left-to-right layout.",
        rust_owner: "Tabs",
        rust: "align(TabsAlign)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "variant",
        ty: "\"primary\" | \"secondary\"",
        default: "\"primary\"",
        description: "Visual style variant: a filled segment or an underline.",
        rust_owner: "Tabs",
        rust: "variant(TabsVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"horizontal\"",
        description: "Tab-list and panel layout orientation.",
        rust_owner: "Tabs",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "selectedKey",
        ty: "string",
        default: "—",
        description: "Controlled selected tab key.",
        rust_owner: "Tabs",
        rust: "selected_key(key)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "defaultSelectedKey",
        ty: "string",
        default: "—",
        description: "Initial selected key for uncontrolled tabs.",
        rust_owner: "Tabs",
        rust: "default_selected_key(key)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "onSelectionChange",
        ty: "(key: Key) => void",
        default: "—",
        description: "Reports the selected key from tab activation.",
        rust_owner: "Tabs",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes on the root.",
        rust_owner: "Tabs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, TabsRenderProps>",
        default: "—",
        description: "Overrides the root DOM element.",
        rust_owner: "Tabs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.List",
        prop: "aria-label",
        ty: "string",
        default: "—",
        description: "Accessible label for the tab list.",
        rust_owner: "Tabs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.List",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes on the tab list.",
        rust_owner: "Tabs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.List",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, TabListRenderProps>",
        default: "—",
        description: "Overrides the tab-list DOM element.",
        rust_owner: "Tabs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.Tab",
        prop: "id",
        ty: "string",
        default: "—",
        description: "Unique tab identifier and selection key.",
        rust_owner: "TabItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs.Tab",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Removes one tab from pointer and roving-keyboard activation.",
        rust_owner: "TabItem",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Tabs.Tab",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes on one tab.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.Tab",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, TabRenderProps>",
        default: "—",
        description: "Overrides one tab's DOM element.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.Separator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes on a separator.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.Panel",
        prop: "id",
        ty: "string",
        default: "—",
        description: "Panel identifier matching a tab id; the port derives it from the item key.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Tabs.Panel",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes on a panel.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Tabs.Panel",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, TabPanelRenderProps>",
        default: "—",
        description: "Overrides the panel DOM element.",
        rust_owner: "TabItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const TABS_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Tabs",
        slot: "tabs",
        description: "Root flex container that orients the list and active panel.",
        rust_owner: "Tabs",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.ListContainer",
        slot: "tabs-list-container",
        description: "Container owning the scroller and overflow chevrons.",
        rust_owner: "Tabs",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.List",
        slot: "tabs-list",
        description: "Scrollable row or column and its shared roving focus handle.",
        rust_owner: "Tabs",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.Tab",
        slot: "tabs-tab",
        description: "One keyed, selectable tab segment.",
        rust_owner: "TabItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.Separator",
        slot: "tabs-separator",
        description: "Optional pointer-inert hairline before a primary tab.",
        rust_owner: "TabItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.Indicator",
        slot: "tabs-indicator",
        description: "Measured filled pill or accent line following the selected tab.",
        rust_owner: "Tabs",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Tabs.Panel",
        slot: "tabs-panel",
        description: "Content associated with the selected tab key.",
        rust_owner: "TabItem",
        status: ImplementationStatus::Implemented,
    },
];

const TABS_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Selected",
        selector: "[aria-selected=\"true\"]",
        description: "Moves the indicator and applies selected foreground styling.",
        rust: "selected_key / active branch",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ":hover or [data-hovered=\"true\"]",
        description: "Dims an enabled, unselected tab to 70% opacity.",
        rust: "hover(.. opacity(0.7))",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible or [data-focus-visible=\"true\"]",
        description: "Draws the shared roving stop's focus-visible ring.",
        rust: "with_focus_ring + focus_visible",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ":disabled or [aria-disabled=\"true\"]",
        description: "Dims the tab and removes it from pointer and keyboard activation.",
        rust: "is_disabled || item.is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Controlled selection",
        selector: "selectedKey",
        description: "Moves roving focus and reports changes without mutating owner state.",
        rust: "selected_key + on_selection_change",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Uncontrolled selection",
        selector: "defaultSelectedKey",
        description: "Holds selection and repairs it when the selected item disappears.",
        rust: "default_selected_key + keyed selection state",
        status: ImplementationStatus::Implemented,
    },
];

const TABS_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".tabs--align-start / .tabs--align-end",
        value: "justify-start text-start / justify-end text-end",
        description: "Tab content alignment is applied per instance to both variants; center remains the default. Panels and nested lists keep their own alignment.",
        rust: "TabsAlign on each tab's flex and text styles",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs",
        value: "flex gap-2; horizontal flex-col; vertical flex-row",
        description: "Root orientation and spacing.",
        rust: "flex + gap(px(8)) + orientation layout",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__list-container",
        value: "relative bg-default; radius calc(var(--radius) * 2.5)",
        description: "Primary list tray.",
        rust: "relative + default fill + radius_lg * 2.5",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__list-container__scroller",
        value: "ScrollShadow size 64 with hidden scrollbar",
        description: "Scrollable viewport follows the configured axis without remapping wheel input from the other axis; fading overflow edges remain unavailable.",
        rust: "raw overflow scroller; chevrons are measured but edge fades are absent",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".tabs__list-container__scroll-prev/next",
        value: "size-4 rounded-full bg-transparent text-foreground; overflow-gated",
        description: "Previous and next overflow controls.",
        rust: "16px transparent occluding chevrons driven by ScrollHandle bounds",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__list-container__scroll-prev/next transitions",
        value: "opacity 150ms ease-smooth; hover opacity-70; focus-visible status-focused",
        description: "Chevron interaction feedback.",
        rust: "hover opacity snaps; no property interpolation or programmatic focus ring",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".tabs__list",
        value: "inline-flex p-1; horizontal w-max min-w-full",
        description: "Primary list sizing and inset.",
        rust: "flex_shrink_0 + p(px(4)) + horizontal min width",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__list[data-orientation=\"vertical\"]",
        value: "flex-col gap-1; tab min-w-20",
        description: "Vertical list geometry.",
        rust: "flex_col + gap(px(4)) + min_w(px(80))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__tab",
        value: "relative flex h-8 w-full rounded-3xl px-4 text-sm font-medium text-muted",
        description: "Box metrics and typography match. Constrained vertical labels wrap upstream, but the port keeps labels on one line and can widen the list beside a panel.",
        rust: "32px height + 16px padding + control_radius + 14px medium text; whitespace_nowrap",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".tabs__tab transitions",
        value: "color/background/opacity 150ms ease-smooth; shadow 150ms ease-out",
        description: "Property interpolation between tab states.",
        rust: "state colors and opacity swap on a frame",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".tabs__tab[data-selected=\"true\"]",
        value: "text-segment-foreground; hide own and following separator",
        description: "Selected primary-tab styling.",
        rust: "segment foreground + indicator + adjacent separator motion",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__tab:hover",
        value: "unselected enabled opacity-70",
        description: "Pointer hover treatment in both variants.",
        rust: "hover(.. opacity(0.7))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__tab:focus-visible",
        value: "status-focused",
        description: "Keyboard focus treatment.",
        rust: "with_focus_ring",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__separator",
        value: "absolute pointer-events-none rounded-sm bg-muted/25",
        description: "Separator ownership and fill.",
        rust: "absolute hairline_radius + muted alpha 0.25 child",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__separator geometry",
        value: "horizontal w-px h-1/2; vertical h-px w-[90%]",
        description: "Orientation-specific separator geometry.",
        rust: "border-width hairline with 50% or 90% relative span",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__separator transition",
        value: "opacity 150ms ease-smooth; motion-reduce none",
        description: "Selection-adjacent separator fade.",
        rust: "SeparatorMotion + Curve::Smooth + reduce_motion snap",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__panel",
        value: "w-full p-2; horizontal mt-4; vertical ms-4",
        description: "Active panel size, inset and orientation spacing.",
        rust: "w_full + p(px(8)) + 16px orientation margin",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__panel[data-exiting=\"true\"]",
        value: "absolute start-0 top-0 w-full",
        description: "Keeps an exiting panel overlaid during its transition.",
        rust: "panels are replaced immediately",
        status: ImplementationStatus::Unavailable,
    },
    StyleDoc {
        class_or_token: ".tabs__indicator",
        value: "absolute rounded-3xl bg-segment shadow-surface",
        description: "Primary selected-segment surface.",
        rust: "measured absolute child + segment fill + control_radius + surface shadow",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs__indicator transition",
        value: "translate/width/height 250ms ease-out-fluid; motion-reduce none",
        description: "Selection indicator geometry motion.",
        rust: "IndicatorMotion + Curve::OutFluid + reduce_motion snap",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs--secondary",
        value: "transparent square tray; list p-0; separators hidden; tabs rounded-none",
        description: "Secondary variant reset.",
        rust: "border-only container + zero list inset + no separators + square tabs",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs--secondary .tabs__indicator",
        value: "rounded-none bg-accent shadow-none",
        description: "Secondary selection line.",
        rust: "accent indicator without radius or shadow",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".tabs--secondary orientation",
        value: "horizontal border-b + h-0.5 line; vertical border-s + w-0.5 line",
        description: "Secondary tray border and indicator axis.",
        rust: "orientation border + 2px indicator target",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const TABS: ReferenceMetadata = ReferenceMetadata {
    page: "Tabs",
    import_line: "use herogpui::components::tabs::{TabItem, Tabs};",
    source_module: "tabs",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/tabs.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/tabs/tabs.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/tabs.css",
    required_parts: TABS_REQUIRED_PARTS,
    api: TABS_API,
    parts: TABS_PARTS,
    states: TABS_STATES,
    styling: TABS_STYLING,
};

const ACCORDION_REQUIRED_PARTS: &[&str] = &[
    "Accordion",
    "Accordion.Item",
    "Accordion.Heading",
    "Accordion.Trigger",
    "Accordion.Indicator",
    "Accordion.Panel",
    "Accordion.Body",
];

const ACCORDION_API: &[ApiDoc] = &[
    ApiDoc { owner: "Accordion", prop: "allowsMultipleExpanded", ty: "boolean", default: "false", description: "Allows more than one item to remain expanded.", rust_owner: "Accordion", rust: "allows_multiple_expanded(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "defaultExpandedKeys", ty: "Iterable<Key>", default: "—", description: "Seeds the uncontrolled expanded-key set.", rust_owner: "Accordion", rust: "default_expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "expandedKeys", ty: "Iterable<Key>", default: "—", description: "The caller-owned expanded-key set.", rust_owner: "Accordion", rust: "expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "onExpandedChange", ty: "(keys: Set<Key>) => void", default: "—", description: "Reports the complete proposed expanded-key set.", rust_owner: "Accordion", rust: "on_expanded_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables every item trigger.", rust_owner: "Accordion", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "variant", ty: "\"default\" | \"surface\"", default: "\"default\"", description: "Selects the flush or rounded surface treatment.", rust_owner: "Accordion", rust: "variant(AccordionVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "hideSeparator", ty: "boolean", default: "false", description: "Hides the rules between items.", rust_owner: "Accordion", rust: "hide_separator(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion", prop: "children", ty: "ReactNode", default: "—", description: "Typed AccordionItem values replace arbitrary compound children.", rust_owner: "Accordion", rust: "new(items)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Accordion", prop: "className", ty: "string", default: "—", description: "Arbitrary CSS classes have no GPUI equivalent.", rust_owner: "Accordion", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion", prop: "render", ty: "DOMRenderFunction<AccordionRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "Accordion", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Item", prop: "id", ty: "Key", default: "—", description: "Stable item identity used by every expanded and disabled set.", rust_owner: "AccordionItem", rust: "new(key, title)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Item", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables this item's trigger independently.", rust_owner: "AccordionItem", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Item", prop: "defaultExpanded", ty: "boolean", default: "false", description: "Seeds this item into the uncontrolled group set.", rust_owner: "AccordionItem", rust: "default_expanded(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Item", prop: "isExpanded", ty: "boolean", default: "—", description: "Within a group, pinned React Aria derives this from expandedKeys; the port does the same.", rust_owner: "Accordion", rust: "expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Item", prop: "onExpandedChange", ty: "(isExpanded: boolean) => void", default: "—", description: "Reports this item's proposed expanded state.", rust_owner: "AccordionItem", rust: "on_expanded_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Item", prop: "children", ty: "ReactNode", default: "—", description: "Title, optional subtitle, indicator and body are typed composition seams.", rust_owner: "AccordionItem", rust: "new(key, title) + subtitle(text) + indicator(render) + content(body)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Accordion.Item", prop: "className", ty: "string", default: "—", description: "Arbitrary item classes have no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Item", prop: "render", ty: "DOMRenderFunction<AccordionItemRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Trigger", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "The title and subtitle are typed text; the indicator is independently replaceable.", rust_owner: "AccordionItem", rust: "new(key, title) + subtitle(text)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Accordion.Trigger", prop: "onPress", ty: "() => void", default: "—", description: "Reports the key whose trigger was pressed.", rust_owner: "Accordion", rust: "on_toggle(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Trigger", prop: "isDisabled", ty: "boolean", default: "—", description: "Reads the owning item's disabled state.", rust_owner: "AccordionItem", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Trigger", prop: "className", ty: "string", default: "—", description: "Arbitrary trigger classes have no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Trigger", prop: "render", ty: "DOMRenderFunction<TriggerRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Panel", prop: "children", ty: "ReactNode", default: "—", description: "Caller-provided panel body content.", rust_owner: "AccordionItem", rust: "content(body)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Panel", prop: "className", ty: "string", default: "—", description: "Arbitrary panel classes have no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Panel", prop: "render", ty: "DOMRenderFunction<AccordionPanelRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Indicator", prop: "children", ty: "ReactNode", default: "chevron", description: "Custom indicator content receives the live item state.", rust_owner: "AccordionItem", rust: "indicator(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Indicator", prop: "className", ty: "string", default: "—", description: "Arbitrary indicator classes have no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Accordion.Body", prop: "children", ty: "ReactNode", default: "—", description: "The item body content.", rust_owner: "AccordionItem", rust: "content(body)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Accordion.Body", prop: "className", ty: "string", default: "—", description: "Arbitrary body classes have no GPUI equivalent.", rust_owner: "AccordionItem", rust: "—", status: ImplementationStatus::Unavailable },
];

const ACCORDION_PARTS: &[PartDoc] = &[
    PartDoc { name: "Accordion", slot: "accordion", description: "Full-width owner of item expansion and presentation.", rust_owner: "Accordion", status: ImplementationStatus::Implemented },
    PartDoc { name: "Accordion.Item", slot: "accordion-item", description: "Keyed item holding trigger and body configuration.", rust_owner: "AccordionItem", status: ImplementationStatus::Implemented },
    PartDoc { name: "Accordion.Heading", slot: "accordion-heading", description: "Heading semantics are folded into the trigger row because GPUI has no heading accessibility node.", rust_owner: "AccordionItem", status: ImplementationStatus::Partial },
    PartDoc { name: "Accordion.Trigger", slot: "accordion-trigger", description: "Focusable, pointer-pressable item header.", rust_owner: "AccordionItem", status: ImplementationStatus::Implemented },
    PartDoc { name: "Accordion.Indicator", slot: "accordion-indicator", description: "Built-in chevron or caller content receiving AccordionItemState.", rust_owner: "AccordionItem", status: ImplementationStatus::Implemented },
    PartDoc { name: "Accordion.Panel", slot: "accordion-panel", description: "Expanded body host; collapsed content leaves the tree.", rust_owner: "AccordionItem", status: ImplementationStatus::Partial },
    PartDoc { name: "Accordion.Body", slot: "accordion-body", description: "Padded, muted body around caller content.", rust_owner: "AccordionItem", status: ImplementationStatus::Implemented },
];

const ACCORDION_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Expanded",
        selector: "[aria-expanded=true] / [data-expanded=true]",
        description: "Shows the panel and supplies true to custom indicator content.",
        rust: "expanded_keys + AccordionItemState::is_expanded",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ":hover:not([aria-expanded=true]) / [data-hovered=true]",
        description: "Only a closed enabled trigger receives the hover fill.",
        rust: "!is_open header.hover(default.soft)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible / [data-focus-visible=true]",
        description: "Keyboard focus draws the inset status ring on the trigger.",
        rust: "tab_stop_handle + with_focus_ring",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ":disabled / [aria-disabled=true]",
        description:
            "Group, keyed-set and item flags remove press and focus while dimming the trigger.",
        rust: "is_disabled + disabled_keys + AccordionItem::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Single expansion",
        selector: "allowsMultipleExpanded=false",
        description: "Opening an item replaces the previous expanded set by default.",
        rust: "allows_multiple_expanded(false)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Multiple expansion",
        selector: "allowsMultipleExpanded=true",
        description: "Opening an item preserves expanded siblings.",
        rust: "allows_multiple_expanded(true)",
        status: ImplementationStatus::Implemented,
    },
];

const ACCORDION_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".accordion", value: "w-full; contain: layout style", description: "The full-width layout matches; GPUI has no CSS containment switch.", rust: "w_full()", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__body", value: "text-sm", description: "Body content uses 14px type with a 20px line height independently of host leading.", rust: "text_size(px(14.)) + line_height(px(20.))", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".accordion__body-inner", value: "px-4 pt-0 pb-4 text-muted", description: "Horizontal and bottom inset, zero top inset and muted color match.", rust: "px(16.) pt(0.) pb(16.) text_color(muted)", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".accordion__heading", value: "flex", description: "The trigger row supplies the layout without a separate heading wrapper.", rust: "header flex", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__indicator", value: "ms-auto size-4 shrink-0 text-muted; rotate 250ms; reduced-motion none", description: "Size, trailing placement and custom content match; built-in glyphs swap without rotation interpolation.", rust: "size(16.) flex_shrink_0 + indicator(render)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__item::after", value: "absolute bottom h-px w-full rounded-xs bg-separator", description: "The same one-pixel rule is a flow child rather than an absolute pseudo-element.", rust: "h(1.) w_full hairline_radius separator", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__trigger", value: "flex flex-1 items-center justify-between px-4 py-4 text-sm font-medium", description: "Trigger geometry and typography match.", rust: "flex items_center justify_between px(16.) py(16.) text 14 medium", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".accordion__trigger transition", value: "opacity and box-shadow 150ms ease-out; reduced-motion none", description: "The port reaches focus and disabled endpoints without interpolating them.", rust: "immediate style state", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__trigger hover", value: "closed default: foreground 3% mix; surface: bg-default", description: "Hover is correctly limited to closed triggers; the default variant uses default-soft rather than the exact foreground mix.", rust: "!is_open hover(default.soft)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion__panel", value: "height 200ms ease-out-quad; opacity 200ms ease-out; overflow clip", description: "Expanded content is laid out at its endpoint and collapsed content leaves immediately.", rust: "conditional body child", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".accordion--surface", value: "bg-surface; min(32px, radius-3xl)", description: "Surface fill, clipped radius and absence of an extra shadow match.", rust: "surface.background + container_radius + overflow_hidden", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".accordion--surface item separators", value: "start 3%; width 94%; surface-foreground/6", description: "Inset geometry matches; the semantic separator token supplies the line color.", rust: "mx(relative(.03)) w(relative(.94)) separator", status: ImplementationStatus::Implemented },
];

pub(super) const ACCORDION: ReferenceMetadata = ReferenceMetadata {
    page: "Accordion",
    import_line: "use herogpui::components::accordion::{Accordion, AccordionItem};",
    source_module: "accordion",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/accordion.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/accordion/accordion.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.21.0/packages/react-aria-components/src/Disclosure.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/accordion.css",
    required_parts: ACCORDION_REQUIRED_PARTS,
    api: ACCORDION_API,
    parts: ACCORDION_PARTS,
    states: ACCORDION_STATES,
    styling: ACCORDION_STYLING,
};

const DISCLOSURE_REQUIRED_PARTS: &[&str] = &[
    "DisclosureGroup",
    "Disclosure",
    "Disclosure.Heading",
    "Disclosure.Trigger",
    "Disclosure.Indicator",
    "Disclosure.Content",
    "Disclosure.Body",
];

const DISCLOSURE_API: &[ApiDoc] = &[
    ApiDoc { owner: "DisclosureGroup", prop: "expandedKeys", ty: "Set<Key>", default: "—", description: "The currently expanded items (controlled).", rust_owner: "DisclosureGroup", rust: "expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroup", prop: "defaultExpandedKeys", ty: "Iterable<Key>", default: "—", description: "The initially expanded items (uncontrolled).", rust_owner: "DisclosureGroup", rust: "default_expanded_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroup", prop: "onExpandedChange", ty: "(keys: Set<Key>) => void", default: "—", description: "Reports the complete next expanded set.", rust_owner: "DisclosureGroup", rust: "on_expanded_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroup", prop: "allowsMultipleExpanded", ty: "boolean", default: "false", description: "Allows more than one item to remain expanded.", rust_owner: "DisclosureGroup", rust: "allows_multiple_expanded(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroup", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables every disclosure trigger in the group.", rust_owner: "DisclosureGroup", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroup", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Composed disclosure items; GPUI builds keyed items through a typed method.", rust_owner: "DisclosureGroup", rust: "item(key, title, content)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "DisclosureGroup", prop: "className", ty: "string", default: "—", description: "Additional CSS classes.", rust_owner: "DisclosureGroup", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Disclosure", prop: "isExpanded", ty: "boolean", default: "false", description: "Controls whether the panel is expanded.", rust_owner: "Disclosure", rust: "is_expanded(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Disclosure", prop: "defaultExpanded", ty: "boolean", default: "false", description: "Initial expanded state when the disclosure owns its state; inherited from pinned React Aria.", rust_owner: "Disclosure", rust: "default_expanded(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Disclosure", prop: "onExpandedChange", ty: "(isExpanded: boolean) => void", default: "—", description: "Reports the proposed expanded state.", rust_owner: "Disclosure", rust: "on_expanded_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Disclosure", prop: "isDisabled", ty: "boolean", default: "false", description: "Disables the disclosure trigger.", rust_owner: "Disclosure", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Disclosure", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Compound heading, trigger and panel children; the GPUI control builds the trigger and accepts static body children through ParentElement or a state-aware body render closure.", rust_owner: "Disclosure", rust: "content(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Disclosure", prop: "className", ty: "string", default: "—", description: "Additional CSS classes.", rust_owner: "Disclosure", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Disclosure", prop: "render", ty: "DOMRenderFunction<DisclosureRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "Disclosure", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Disclosure.Trigger", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Custom trigger content; the port accepts an id and title and builds a HeroGPUI Button.", rust_owner: "Disclosure", rust: "new(id, title)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Disclosure.Trigger", prop: "className", ty: "string", default: "—", description: "Additional trigger classes.", rust_owner: "Disclosure", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Disclosure.Content", prop: "children", ty: "ReactNode", default: "—", description: "Panel body content supplied through ParentElement composition or the state-aware render closure.", rust_owner: "Disclosure", rust: "content(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Disclosure.Content", prop: "className", ty: "string", default: "—", description: "Additional content classes.", rust_owner: "Disclosure", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Disclosure.Content", prop: "render", ty: "DOMRenderFunction<DisclosureContentRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "Disclosure", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "DisclosureRenderProps", prop: "isExpanded", ty: "boolean", default: "—", description: "Current expanded state supplied to the body render closure.", rust_owner: "Disclosure", rust: "content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureRenderProps", prop: "isDisabled", ty: "boolean", default: "—", description: "Current disabled state supplied to the body render closure.", rust_owner: "Disclosure", rust: "content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "DisclosureGroupRenderProps", prop: "expandedKeys", ty: "Set<Key>", default: "—", description: "Current expanded keys; used to draw the group but not delegated to a child closure.", rust_owner: "DisclosureGroup", rust: "expanded_keys(keys)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "DisclosureGroupRenderProps", prop: "isDisabled", ty: "boolean", default: "—", description: "Current group disabled state; drawn internally but not delegated to a child closure.", rust_owner: "DisclosureGroup", rust: "is_disabled(bool)", status: ImplementationStatus::Partial },
];

const DISCLOSURE_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "DisclosureGroup",
        slot: "disclosure-group",
        description: "Full-width owner of the expanded key set.",
        rust_owner: "DisclosureGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Disclosure",
        slot: "disclosure",
        description: "Relative root for one trigger and panel.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Disclosure.Heading",
        slot: "disclosure-heading",
        description: "Heading wrapper is built into the monolithic trigger row.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Disclosure.Trigger",
        slot: "disclosure-trigger",
        description: "A built-in HeroGPUI Button rather than a separately composable trigger.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Disclosure.Indicator",
        slot: "disclosure-indicator",
        description: "Built-in 16px chevron whose glyph reflects expansion.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Disclosure.Content",
        slot: "disclosure-content",
        description: "Mounted panel container while expanded.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Disclosure.Body",
        slot: "disclosure-body",
        description: "Eight-pixel padded body around caller content.",
        rust_owner: "Disclosure",
        status: ImplementationStatus::Implemented,
    },
];

const DISCLOSURE_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Expanded",
        selector: ".disclosure[data-expanded=true]",
        description: "Shows the body and uses the expanded indicator glyph.",
        rust: "is_expanded(bool) / expanded_keys",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".disclosure[data-disabled=true] / .disclosure-group[data-disabled=true]",
        description: "Disables one trigger or every trigger in the group.",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".disclosure__trigger[data-focus-visible=true]",
        description: "The built-in Button owns keyboard focus and its focus ring.",
        rust: "Button tab_stop_handle + ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Single expansion",
        selector: ".disclosure-group:not([data-allows-multiple-expanded])",
        description: "Opening one item replaces the previous expanded set by default.",
        rust: "allows_multiple_expanded(false)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Multiple expansion",
        selector: ".disclosure-group[data-allows-multiple-expanded=true]",
        description: "Opt-in mode toggles membership without closing siblings.",
        rust: "allows_multiple_expanded(true)",
        status: ImplementationStatus::Implemented,
    },
];

const DISCLOSURE_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: ".disclosure-group", value: "w-full; contain: layout style", description: "Full width matches; GPUI has no CSS layout/style containment toggle.", rust: "w_full()", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".disclosure", value: "relative", description: "The root establishes the indicator/content positioning context.", rust: "relative()", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".disclosure__heading", value: "flex", description: "The heading and trigger are represented by one built-in Button row.", rust: "Button", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".disclosure__trigger", value: "inline-block no-highlight; interactive cursor; focused and disabled status utilities", description: "Pointer, focus and disabled behavior come from Button, but the trigger is not independently styled or composed.", rust: "Button::new(trigger_id).is_disabled(bool)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".disclosure__indicator", value: "ms-auto size-4 shrink-0 text-inherit; transform 250ms; reduced-motion none", description: "Size and trailing placement match; the port swaps chevron glyphs in one frame instead of rotating one glyph.", rust: "child(svg size(px(16.)))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".disclosure__content", value: "height 200ms ease-out-quad; opacity 200ms ease-out; overflow clip; reduced-motion none", description: "The port fades entry for 200ms but does not interpolate measured height and removes content immediately on collapse.", rust: "anim::entering + Motion::DISCLOSURE", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".disclosure__body", value: "p-2", description: "Eight-pixel inset around panel content.", rust: "p(px(8.))", status: ImplementationStatus::Implemented },
];

pub(super) const DISCLOSURE: ReferenceMetadata = ReferenceMetadata {
    page: "Disclosure",
    import_line: "use herogpui::components::disclosure::{Disclosure, DisclosureGroup};",
    source_module: "disclosure",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/disclosure.mdx + https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/disclosure-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/disclosure/disclosure.tsx + https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/disclosure-group/disclosure-group.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.21.0/packages/react-aria-components/src/Disclosure.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/disclosure.css + https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/disclosure-group.css",
    required_parts: DISCLOSURE_REQUIRED_PARTS,
    api: DISCLOSURE_API,
    parts: DISCLOSURE_PARTS,
    states: DISCLOSURE_STATES,
    styling: DISCLOSURE_STYLING,
};

const BREADCRUMBS_REQUIRED_PARTS: &[&str] = &["Breadcrumbs", "Breadcrumbs.Item"];

const BREADCRUMBS_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Breadcrumbs",
        prop: "separator",
        ty: "ReactNode",
        default: "chevron-right icon",
        description: "Custom separator between breadcrumb items; separator_render is its Rust port — a closure rebuilt for every non-last crumb and painted inside the 12px separator slot — while separator(BreadcrumbSeparator) covers the built-in presets. The closure overrides the preset.",
        rust_owner: "Breadcrumbs",
        rust: "separator_render(closure) + separator(BreadcrumbSeparator)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Breadcrumbs",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Whether all breadcrumb links are disabled; disabled crumbs leave the tab order and fade, but the current page keeps opacity-100 as v3's [data-current] rule does.",
        rust_owner: "Breadcrumbs",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Breadcrumbs",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Breadcrumbs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Breadcrumbs",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "The breadcrumb items; the port takes a Vec<Crumb> instead of composed Breadcrumbs.Item elements.",
        rust_owner: "Breadcrumbs",
        rust: "new(items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Breadcrumbs",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, undefined>",
        default: "—",
        description: "Overrides the default DOM element with a custom render function; there is no DOM element to override.",
        rust_owner: "Breadcrumbs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Breadcrumbs.Item",
        prop: "href",
        ty: "string",
        default: "—",
        description: "The URL to link to (omit for the current page); a href crumb opens it through the OS URL handler, with or without an on_navigate callback.",
        rust_owner: "Crumb",
        rust: "href(href)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Breadcrumbs.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item.",
        rust_owner: "Breadcrumbs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Breadcrumbs.Item",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Item content or render function; the port takes a label string per Crumb, so composed children are not supported.",
        rust_owner: "Crumb",
        rust: "new(label)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Breadcrumbs.Item",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, BreadcrumbRenderProps>",
        default: "—",
        description: "Overrides the default DOM element with a custom render function; there is no DOM element to override.",
        rust_owner: "Breadcrumbs",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const BREADCRUMBS_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Breadcrumbs",
        slot: "breadcrumbs",
        description: "Root container: one flex line, items centre, no wrap.",
        rust_owner: "Breadcrumbs",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Breadcrumbs.Item",
        slot: "breadcrumbs-item",
        description: "Per-crumb wrapper that hugs its content and holds the link and the trailing separator; the port draws it from a Crumb, so it is not a composed element.",
        rust_owner: "Breadcrumbs",
        status: ImplementationStatus::Implemented,
    },
];

const BREADCRUMBS_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Current",
        selector: ".breadcrumbs__link[data-current=\"true\"]",
        description: "The last crumb is the current page: it renders in the link token, is not a tab stop, answers no press even with an href, and never takes the disabled fade.",
        rust: "is_last -> colors.link + no tab stop + no on_click",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hover",
        selector: ".breadcrumbs__link:hover / [data-hovered=\"true\"]",
        description: "Link crumbs underline on hover; the colour stays muted.",
        rust: "hover(|s| s.underline()) when navigable",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus",
        selector: "[data-focus-visible=\"true\"]",
        description: "Every link crumb is a tab stop (React Aria link semantics) and draws the focus-visible status ring when keyboard-focused; mouse focus leaves the ring off. Enter and Space activate the focused crumb through gpui's focused-click, so no second key handler is bound. The current page and disabled crumbs are not tab stops at all.",
        rust: "tab_stop_handle per link crumb + ring_if_focused + gpui focused-click",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: "aria-disabled=\"true\"",
        description: "isDisabled disables every link: none takes a press, none stays a tab stop, and all of them fade — except the current page, which [data-current] holds at opacity-100.",
        rust: "is_disabled -> disabled_opacity when !is_last + focus gated on !disabled",
        status: ImplementationStatus::Implemented,
    },
];

const BREADCRUMBS_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".breadcrumbs",
        value: "flex items-center",
        description: "One line, items centred, no wrap.",
        rust: "root flex items_center",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".breadcrumbs__link",
        value: "relative px-0.5 text-sm leading-5 font-medium text-muted no-underline opacity-100",
        description: "14px medium muted link text on a fixed 20px line box with 2px horizontal padding; leading-5 is a fixed height, not a ratio of the text size.",
        rust: "text_size(px(14.)) + line_height(px(20.)) + FontWeight::MEDIUM + px(px(2.)) + muted",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".breadcrumbs__link:hover / [data-hovered=\"true\"]",
        value: "underline",
        description: "Underline only; the colour stays muted.",
        rust: "hover(|s| s.underline()) when navigable",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".breadcrumbs__link[data-current=\"true\"]",
        value: "text-link opacity-100",
        description: "The current page takes the link token and never the disabled fade.",
        rust: "is_last -> current_color colors.link + opacity kept",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".breadcrumbs__item",
        value: "flex shrink-0 items-center justify-center gap-0.5 px-0.5",
        description: "A 2px gap between link and separator, 2px of horizontal padding, and content that never compresses when the bar outgrows its parent.",
        rust: "row flex + flex_shrink_0 + items_center + justify_center + gap(px(2.)) + px(px(2.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".breadcrumbs__separator",
        value: "size-3 text-muted rtl:rotate-180",
        description: "A 12px muted slot that holds the chevron icon, the slash/dash glyphs or a custom node; gpui has no rtl direction, so the rtl flip has nothing to mirror.",
        rust: "separator slot size(px(12.)) + text_color(muted)",
        status: ImplementationStatus::Partial,
    },
];

pub(super) const BREADCRUMBS: ReferenceMetadata = ReferenceMetadata {
    page: "Breadcrumbs",
    import_line: "use herogpui::components::breadcrumbs::{Breadcrumbs, Crumb};",
    source_module: "breadcrumbs",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/breadcrumbs.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/breadcrumbs/breadcrumbs.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/breadcrumbs.css",
    required_parts: BREADCRUMBS_REQUIRED_PARTS,
    api: BREADCRUMBS_API,
    parts: BREADCRUMBS_PARTS,
    states: BREADCRUMBS_STATES,
    styling: BREADCRUMBS_STYLING,
};

const LINK_REQUIRED_PARTS: &[&str] = &["Link", "Link.Icon"];

const LINK_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Link",
        prop: "href",
        ty: "string",
        default: "—",
        description: "Destination for the anchor. GPUI has no in-app navigation graph, so `href` opens through the OS handler (`App::open_url`) on press.",
        rust_owner: "Link",
        rust: "href(url)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Link",
        prop: "target",
        ty: "string",
        default: "\"_self\"",
        description: "Where to open the linked document. The port has no browser navigation or HTTP transport — `href` opens through the OS handler — so there is nothing for a target to control.",
        rust_owner: "Link",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Link",
        prop: "rel",
        ty: "string",
        default: "—",
        description: "Relationship between the documents. Meaningless without an anchor element handed to a browser; the OS handler receives only the URL string.",
        rust_owner: "Link",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Link",
        prop: "download",
        ty: "boolean | string",
        default: "—",
        description: "Prompts a file download. The OS handler decides what to do with the URL; the port has no HTTP transport to fetch and save it.",
        rust_owner: "Link",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Link",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables pointer and keyboard interaction: the disabled opacity, no pointer reach, and no tab stop.",
        rust_owner: "Link",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Link",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Custom classes merged with the default styles.",
        rust_owner: "Link",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Link",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Content rendered inside the link. The port composes it as the label text plus an optional icon element, ordered by where the icon belongs (v3 orders `Link.Icon` among the children).",
        rust_owner: "Link",
        rust: "label(text) / icon(element)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Link",
        prop: "onPress",
        ty: "(e: PressEvent) => void",
        default: "—",
        description: "Fired when the link is activated, in addition to opening `href`. The callback receives GPUI's ClickEvent rather than React Aria's PressEvent.",
        rust_owner: "Link",
        rust: "on_press(handler)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Link",
        prop: "autoFocus",
        ty: "boolean",
        default: "—",
        description: "Whether the element should receive focus on render. A link is not otherwise a focus target here, so this also makes it one; a disabled link is skipped by Tab and must not grab focus either.",
        rust_owner: "Link",
        rust: "auto_focus(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Link",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, LinkRenderProps>",
        default: "—",
        description: "Overrides the default DOM element with a custom render function. GPUI has no DOM props to spread onto a caller-built element, so the closure receives the interactive half alone (`isHovered`, `isPressed`, `isFocused`, `isFocusVisible`, `isDisabled`) and draws the content; the root keeps the `href`, `onPress`, focus and disabled wiring either way.",
        rust_owner: "Link",
        rust: "render(closure)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Link.Icon",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Custom icon content. A childless `Link.Icon` renders v3's built-in arrow with `data-default-icon=\"true\"` and its `ms-1 pb-1.5` spacing, and that default arrow has no port path: `icon(element)` is the custom-children path only, so the port draws no icon at all without it. `icon_first(true)` moves the icon before the label the way v3's child ordering does.",
        rust_owner: "Link",
        rust: "icon(element)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Link.Icon",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Link",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const LINK_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Link",
        slot: "link",
        description: "Root anchor on the `.link` BEM class: `relative inline-flex h-fit w-fit items-center rounded-xl font-medium text-link no-underline decoration-[1.5px]`. The text colour is the `--link` token and never changes state; the port is a block-level flex row (no inline-flex) that hugs its content.",
        rust_owner: "Link",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Link.Icon",
        slot: "link__icon",
        description: "`pointer-events-none inline-flex size-[0.75em] shrink-0 items-center justify-center text-current opacity-60`, raised to full opacity on hover, press and focus. `[data-default-icon=true]` adds `ms-1 pb-1.5`, but that rule belongs only to the childless built-in arrow, which the port does not draw; `icon(element)` is the arbitrary-children path and gets no default-icon spacing. The port draws the caller's element verbatim, flush against the label, without the em-sized box or the default 60% opacity.",
        rust_owner: "Link",
        status: ImplementationStatus::Partial,
    },
];

const LINK_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".link:hover / [data-hovered=\"true\"]",
        description: "Turns the 1.5px underline on with `decoration-muted/50`; the text colour never changes.",
        rust: "hover(StyleRefinement underline) with colors.muted.alpha(0.5)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".link:active / [data-pressed=\"true\"]",
        description: "Takes the underline decoration to full `decoration-muted`.",
        rust: "active(StyleRefinement underline) with colors.muted",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".link:focus-visible:not(:focus) / [data-focus-visible=\"true\"]",
        description: "Keyboard focus displays the status-focused ring; `track_focus` is what puts the link in the tab order.",
        rust: "tab_stop_handle + ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".link[aria-disabled=\"true\"]",
        description: "status-disabled: the disabled opacity, no pointer reach, and no tab stop.",
        rust: "is_disabled + disabled_opacity + track_focus gated on interactivity",
        status: ImplementationStatus::Implemented,
    },
];

const LINK_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".link",
        value: "relative inline-flex h-fit w-fit items-center rounded-xl font-medium text-link no-underline decoration-separator-tertiary decoration-[1.5px] underline-offset-4 no-highlight",
        description: "The stylesheet is the contract — the docs' Global CSS snippet still says `font-semibold`, but the pinned rule is `font-medium`. `--link` defaults to `--foreground`. The port is a block-level flex row with no gap of its own (`.link` has none), and `underline-offset-4` has no GPUI analogue.",
        rust: "flex + items_center + text_color(colors.link) + FontWeight::MEDIUM + small_radius + cursor_pointer",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".link:hover / .link:active",
        value: "underline decoration-muted/50 on hover; decoration-muted on active",
        description: "Only the decoration colour changes between the two states; gpui panics on a second `hover` call, so each state's closure owns its whole underline.",
        rust: "hover/active StyleRefinement underline 1.5px via colors.muted",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".link transition",
        value: "color 100ms / background-color 150ms / box-shadow 150ms / opacity 100ms var(--ease-*), motion-reduce:transition-none",
        description: "The port applies the hover, press and focus styles directly without property interpolation; the underline flips instantly.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    StyleDoc {
        class_or_token: ".link__icon",
        value: "pointer-events-none inline-flex size-[0.75em] shrink-0 items-center justify-center text-current opacity-60; [data-default-icon=true] ms-1 pb-1.5",
        description: "Em-sized icon box with a 60% resting opacity that fills on interaction. The `ms-1 pb-1.5` spacing belongs to `[data-default-icon=true]` alone — the childless built-in arrow, which the port does not draw. The port's `icon(element)` draws the caller's element as-is, flush against the label.",
        rust: "icon(element) laid out as a plain root child; no gap, no default-icon spacing",
        status: ImplementationStatus::Partial,
    },
];

pub(super) const LINK: ReferenceMetadata = ReferenceMetadata {
    page: "Link",
    import_line: "use herogpui::components::link::Link;",
    source_module: "link",
    version: "3.2.5",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/apps/docs/content/docs/en/react/components/(navigation)/link.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/react/src/components/link/link.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.5/packages/styles/components/link.css",
    required_parts: LINK_REQUIRED_PARTS,
    api: LINK_API,
    parts: LINK_PARTS,
    states: LINK_STATES,
    styling: LINK_STYLING,
};
