//! pickers reference metadata.

use super::*;

const COMBO_BOX_REQUIRED_PARTS: &[&str] = &[
    "ComboBox",
    "ComboBox.InputGroup",
    "ComboBox.Value",
    "ComboBox.Trigger",
    "ComboBox.Popover",
];

const COMBO_BOX_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "ComboBox",
        prop: "inputValue",
        ty: "string",
        default: "—",
        description: "Current text in the input (controlled).",
        rust_owner: "ComboBox",
        rust: "input_value(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "defaultInputValue",
        ty: "string",
        default: "—",
        description: "Initial text in the input (uncontrolled).",
        rust_owner: "ComboBox",
        rust: "default_input_value(text)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "onInputChange",
        ty: "(value: string) => void",
        default: "—",
        description: "Called when the input text changes.",
        rust_owner: "ComboBox",
        rust: "on_input_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Controlled open state inherited from the pinned React Aria ComboBox primitive.",
        rust_owner: "ComboBox",
        rust: "is_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "defaultOpen",
        ty: "boolean",
        default: "false",
        description: "Initial open state for the uncontrolled popover.",
        rust_owner: "ComboBox",
        rust: "default_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "onOpenChange",
        ty: "(isOpen: boolean) => void",
        default: "—",
        description: "Called when focus, typing, the trigger, Escape, selection or outside press changes the open state.",
        rust_owner: "ComboBox",
        rust: "on_open_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "\"single\"",
        description: "Whether one or multiple options may be selected.",
        rust_owner: "ComboBox",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "selectedKey",
        ty: "Key | null",
        default: "—",
        description: "Controlled single-selection item key, with v3's null spelled as the empty string; the port writes the key's label through the input state and hands the key to the controlled selection.",
        rust_owner: "ComboBox",
        rust: "selected_key(key)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "defaultSelectedKey",
        ty: "Key | null",
        default: "—",
        description: "Uncontrolled single-selection seed addressed by item key; default_value takes an ordered key list rather than a nullable key.",
        rust_owner: "ComboBox",
        rust: "default_value(keys)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "onSelectionChange",
        ty: "(key: Key | null) => void",
        default: "—",
        description: "Reports the picked key; the null a cleared input or a committed custom value stands for is spelled through on_selection_change_all's empty slice — reported only when a previous selection existed — the port's rendering of the primitive's null.",
        rust_owner: "ComboBox",
        rust: "on_selection_change(callback) / on_selection_change_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "value",
        ty: "Key | null | Key[]",
        default: "—",
        description: "Controlled selection as ordered item keys for both single and multiple modes; v3's null is the empty list, and a single-mode selection keeps the first listed key.",
        rust_owner: "ComboBox",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "defaultValue",
        ty: "Key | null | Key[]",
        default: "—",
        description: "Uncontrolled selection seed as an ordered item-key list in the owner's order; scalar/null key semantics are represented by the port's iterable key list.",
        rust_owner: "ComboBox",
        rust: "default_value(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "onChange",
        ty: "(value: Key | null | Key[]) => void",
        default: "—",
        description: "Selection callback; the single-value builder reports a pick and on_selection_change_all covers the complete Key | null | Key[] union, spelling null as the empty slice — reported only when a previous selection existed.",
        rust_owner: "ComboBox",
        rust: "on_selection_change(callback) / on_selection_change_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "items",
        ty: "Iterable<T>",
        default: "—",
        description: "Options displayed in the listbox as keyed PickerItems: the stable key the selection, disabledKeys and form value address, and the label the filtering, input text and rendering use.",
        rust_owner: "ComboBox",
        rust: "new(state, items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of the options that remain visible but cannot be selected; the state is per key, so one of two same-label items can be disabled alone.",
        rust_owner: "ComboBox",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "defaultFilter",
        ty: "(text: string, inputValue: string) => boolean",
        default: "—",
        description: "Custom option matcher; the pinned React Aria default is the language-sensitive useFilter base contains matcher, while the port's built-in matcher is case-insensitive substring and its filter callback is the direct companion seam.",
        rust_owner: "ComboBox",
        rust: "filter(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Filter",
        prop: "useFilter",
        ty: "({sensitivity}) => {contains, startsWith, endsWith}",
        default: "—",
        description: "Pinned React Aria filtering companion whose ComboBox caller supplies sensitivity=\"base\"; it is not a compound part, and the port accepts a matcher rather than a locale-aware hook object.",
        rust_owner: "ComboBox",
        rust: "filter(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables the input, trigger, keyboard navigation and popover.",
        rust_owner: "ComboBox",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "isReadOnly",
        ty: "boolean",
        default: "false",
        description: "Keeps the field readable and focusable while preventing edits and opening.",
        rust_owner: "ComboBox",
        rust: "is_read_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "isRequired",
        ty: "boolean",
        default: "false",
        description: "Marks the field as required; the port carries the flag to its field and validation surface, without browser constraint-validation semantics.",
        rust_owner: "ComboBox",
        rust: "is_required(bool)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "isInvalid",
        ty: "boolean",
        default: "false",
        description: "Marks the field invalid and switches the description slot to the error message.",
        rust_owner: "ComboBox",
        rust: "is_invalid(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "validate",
        ty: "(value: ComboBoxValidationValue) => ValidationError | true | null | undefined",
        default: "—",
        description: "Runs validation against the input text and surfaces an error, but the port does not pass the browser primitive's selectedKey-shaped validation value or full return union.",
        rust_owner: "ComboBox",
        rust: "validate(callback)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "validationBehavior",
        ty: "\"native\" | \"aria\"",
        default: "\"native\"",
        description: "Selects the local validation behavior carried by the field; native form blocking and ARIA attributes are not browser semantics in GPUI.",
        rust_owner: "ComboBox",
        rust: "validation_behavior(ValidationBehavior)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Names the local FormField whose live value follows formValue; the input keeps its implicit-Enter submission, but there is no automatic DOM form boundary.",
        rust_owner: "ComboBox",
        rust: "name(value) + form_field()",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "form",
        ty: "string",
        default: "—",
        description: "Associates the input with a browser form by id; GPUI has no DOM form owner.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "formValue",
        ty: "\"text\" | \"key\"",
        default: "\"key\"",
        description: "Chooses what a named field submits: the selected key(s) by default, the typed text under allowsCustomValue (pinned React Aria Components 1.20.0 forces text there). The serialization rides the local FormField; there is no browser form boundary.",
        rust_owner: "ComboBox",
        rust: "form_value(ComboBoxFormValue)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "autoComplete",
        ty: "string",
        default: "—",
        description: "Browser autocomplete hint for the input.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "autoFocus",
        ty: "boolean",
        default: "false",
        description: "Focuses the input on its first render.",
        rust_owner: "ComboBox",
        rust: "auto_focus(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "allowsCustomValue",
        ty: "boolean",
        default: "false",
        description: "Allows Enter to commit text that is not in the collection; the committed custom value keeps the typed text, carries a null selected key, and forces formValue to text as pinned React Aria does.",
        rust_owner: "ComboBox",
        rust: "allows_custom_value(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "allowsEmptyCollection",
        ty: "boolean",
        default: "false",
        description: "Keeps the popover open when filtering produces no rows.",
        rust_owner: "ComboBox",
        rust: "allows_empty_collection(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "menuTrigger",
        ty: "\"focus\" | \"input\" | \"manual\"",
        default: "\"focus\"",
        description: "Chooses whether focus, input, or only an explicit trigger/key action opens the list.",
        rust_owner: "ComboBox",
        rust: "menu_trigger(MenuTrigger)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "shouldFocusWrap",
        ty: "boolean",
        default: "false",
        description: "Wraps keyboard navigation from the last option to the first and back.",
        rust_owner: "ComboBox",
        rust: "should_focus_wrap(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "fullWidth",
        ty: "boolean",
        default: "false",
        description: "Makes the field and its input group fill the available width.",
        rust_owner: "ComboBox",
        rust: "full_width(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "variant",
        ty: "\"primary\" | \"secondary\"",
        default: "\"primary\"",
        description: "Visual field treatment for the input group.",
        rust_owner: "ComboBox",
        rust: "variant(FieldVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional DOM classes.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Compound content or root render function; the port takes items and field text as builders and renders the input, trigger and list monolithically.",
        rust_owner: "ComboBox",
        rust: "new(state, items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox",
        prop: "render",
        ty: "DOMRenderFunction<keyof React.JSX.IntrinsicElements, ComboBoxRenderProps>",
        default: "—",
        description: "Replaces the browser DOM root with a custom render function; GPUI does not expose a DOM render seam.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.InputGroup",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional classes for the input and trigger group.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.InputGroup",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Input and trigger content; the port always supplies its own group through the field composition.",
        rust_owner: "ComboBox",
        rust: "new(state, items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox.Value",
        prop: "placeholder",
        ty: "ReactNode",
        default: "—",
        description: "Fallback content when no item is selected; there is no separate placeholder builder on the port's value closure.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.Value",
        prop: "className",
        ty: "string | (values: ComboBoxValueRenderProps) => string",
        default: "—",
        description: "Static or state-derived DOM classes for the selected-value part.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.Value",
        prop: "children",
        ty: "ReactNode | (values: ComboBoxValueRenderProps) => ReactNode",
        default: "—",
        description: "Custom selected-value content; the local closure receives SelectionValue rather than the browser state object.",
        rust_owner: "ComboBox",
        rust: "value_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox.Trigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional classes for the popover trigger button.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.Trigger",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom trigger content; the port draws a fixed chevron hit surface.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.Popover",
        prop: "placement",
        ty: "\"bottom\" | \"bottom left\" | \"bottom right\" | \"bottom start\" | \"bottom end\" | \"top\" | \"top left\" | \"top right\" | \"top start\" | \"top end\" | \"left\" | \"left top\" | \"left bottom\" | \"start\" | \"start top\" | \"start bottom\" | \"right\" | \"right top\" | \"right bottom\" | \"end\" | \"end top\" | \"end bottom\"",
        default: "\"bottom\"",
        description: "Eight cardinal/start/end placements are available; RAC's full 22-value placement union is not. The panel anchors to the measured field with an 8px gap and flips when the preferred side cannot fit and the opposite side has more room.",
        rust_owner: "ComboBox",
        rust: "placement(Placement)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBox.Popover",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional classes for the popover surface.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBox.Popover",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Listbox content; the port builds its filtered rows, sections and empty state from items instead of accepting arbitrary children.",
        rust_owner: "ComboBox",
        rust: "new(state, items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBoxRenderProps",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Open state supplied to the React Aria root render function.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBoxRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disabled state supplied to the React Aria root render function.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBoxRenderProps",
        prop: "isInvalid",
        ty: "boolean",
        default: "—",
        description: "Resolved invalid state supplied to the React Aria root render function.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBoxRenderProps",
        prop: "isRequired",
        ty: "boolean",
        default: "—",
        description: "Required state supplied to the React Aria root render function.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBoxRenderProps",
        prop: "isReadOnly",
        ty: "boolean",
        default: "—",
        description: "Read-only state supplied to the React Aria root render function.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "ComboBoxValueRenderProps",
        prop: "isPlaceholder",
        ty: "boolean",
        default: "—",
        description: "Whether the value part has no selected items.",
        rust_owner: "ComboBox",
        rust: "value_content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBoxValueRenderProps",
        prop: "selectedItems",
        ty: "(T | null)[]",
        default: "—",
        description: "Selected item labels in the selection's own order, with indices and keys; the local closure supplies labels and indices rather than generic collection objects.",
        rust_owner: "ComboBox",
        rust: "value_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "ComboBoxValueRenderProps",
        prop: "selectedText",
        ty: "string",
        default: "—",
        description: "Comma-separated selected labels supplied to the local value closure.",
        rust_owner: "ComboBox",
        rust: "value_content(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "ComboBoxValueRenderProps",
        prop: "state",
        ty: "ComboBoxState",
        default: "—",
        description: "React Aria/Stately state object for the value render function; no browser state entity is exposed.",
        rust_owner: "ComboBox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const COMBO_BOX_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "ComboBox",
        slot: "combo-box",
        description: "Field root owning input text, selection, filtering, validation, open state and the floating list.",
        rust_owner: "ComboBox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "ComboBox.InputGroup",
        slot: "combo-box-input-group",
        description: "Input and trigger group; the port renders this as a built-in field composition rather than a child slot.",
        rust_owner: "ComboBox",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "ComboBox.Value",
        slot: "combo-box-value",
        description: "Optional selected-value row with SelectionValue content; the browser placeholder and state object are not separate builders.",
        rust_owner: "ComboBox",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "ComboBox.Trigger",
        slot: "combo-box-trigger",
        description: "Built-in chevron hit surface that toggles the list and focuses the input; it is not a separate browser Button element.",
        rust_owner: "ComboBox",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "ComboBox.Popover",
        slot: "combo-box-popover",
        description: "Placement-aware floating list surface with outside-press and Escape dismissal; arbitrary popover children are not composable.",
        rust_owner: "ComboBox",
        status: ImplementationStatus::Partial,
    },
];

const COMBO_BOX_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Open",
        selector: ".combo-box__trigger[data-open=\"true\"]",
        description: "The input group owns a live filtered list when the menu is open.",
        rust: "open_state + overlay_active + show_list",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: ".combo-box [data-slot=\"input\"]:focus, .combo-box [data-focus]",
        description: "Input focus drives the field's focused treatment and the default focus menu trigger.",
        rust: "InputState::focus_handle + MenuTrigger::Focus",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Hovered trigger",
        selector: ".combo-box__trigger:hover, .combo-box__trigger[data-hovered=\"true\"]",
        description: "The trigger responds to hover, but the local hover fill is broader than v3's trigger text-color change.",
        rust: "trigger.hover(default.hover())",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Focus visible trigger",
        selector: ".combo-box__trigger:focus-visible, .combo-box__trigger[data-focus-visible=\"true\"]",
        description: "The separate browser trigger focus ring has no GPUI focusable Button equivalent; keyboard focus remains on the input.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    StateDoc {
        state: "Pressed trigger",
        selector: ".combo-box__trigger[data-pressed=\"true\"]",
        description: "The local trigger captures the press for dismissal ordering but does not reproduce v3's pressed opacity surface.",
        rust: "trigger_pressed capture token",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Disabled",
        selector: ".combo-box[data-disabled=\"true\"], .combo-box__trigger[data-disabled]",
        description: "Input and trigger are inert and the popover cannot open; browser disabled attributes and root data state are unavailable.",
        rust: "is_disabled + interaction gates",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Read only",
        selector: ".combo-box[data-readonly=\"true\"]",
        description: "The input remains readable while edits, opening and selection changes are gated.",
        rust: "is_read_only + interaction gates",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Invalid",
        selector: ".combo-box[data-invalid=\"true\"], .combo-box[aria-invalid=\"true\"]",
        description: "Error content replaces the description and the field is styled invalid; GPUI has no matching DOM attributes.",
        rust: "is_invalid/error_message + Input invalid",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Required",
        selector: ".combo-box[data-required=\"true\"]",
        description: "The required flag reaches the local field and validator, without browser required/form semantics.",
        rust: "is_required + form_field",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Filtered",
        selector: ".combo-box__popover [data-slot=\"list-box-item\"]",
        description: "Rows are limited by the current input and optional custom matcher; the pinned locale-sensitive useFilter default is approximated by case-insensitive substring matching.",
        rust: "filter/default substring + max_items",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Empty collection",
        selector: "allowsEmptyCollection",
        description: "allowsEmptyCollection keeps the panel open and the port draws an explicit no-match or custom-value message.",
        rust: "allows_empty_collection + empty message",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled option",
        selector: ".combo-box__popover [data-slot=\"list-box-item\"][data-disabled=\"true\"]",
        description: "Disabled labels remain visible and cannot be activated, with local muted opacity in place of browser collection semantics.",
        rust: "disabled_keys + disabled opacity gate",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Selected option",
        selector: ".combo-box__popover [data-slot=\"list-box-item\"][data-selected=\"true\"]",
        description: "Selected labels are tracked and multiple selection can draw an indicator; generic ListBox item data attributes are not emitted.",
        rust: "selected_keys + indicator(render)",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Multiple selection",
        selector: "selectionMode=\"multiple\"",
        description: "Rows toggle membership without closing and ComboBox.Value can receive the selected labels.",
        rust: "selection_mode(Multiple) + on_selection_change_all",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Custom value",
        selector: "allowsCustomValue",
        description: "Enter commits unmatched input and reports it through the local selection callback.",
        rust: "allows_custom_value + Enter activation",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Menu trigger",
        selector: "menuTrigger=\"focus\" | \"input\" | \"manual\"",
        description: "Focus, input and manual opening modes match the documented trigger choices, including arrow-key opening.",
        rust: "menu_trigger(MenuTrigger)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus wrap",
        selector: "shouldFocusWrap",
        description: "Keyboard navigation can wrap between the first and last enabled rows.",
        rust: "should_focus_wrap + list_nav::resolve",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Entering",
        selector: ".combo-box__popover[data-entering=\"true\"]",
        description: "The list fades and grows from 95% over 150ms with the list curve; placement-specific slide translations are not reproduced.",
        rust: "anim::entering_zoom + Motion::LIST_IN",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Exiting",
        selector: ".combo-box__popover[data-exiting=\"true\"]",
        description: "v3 fades and shrinks the panel over 100ms; the port removes the panel without a matching exit animation.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const COMBO_BOX_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: "text-sm / .header", value: "14px/20px value, option and empty-state text; Header 12px/16px medium px-2 pt-1.5 pb-1", description: "Text keeps its line height under surrounding styles. Section headers have 8px horizontal, 6px top and 4px bottom padding; selecting an option does not add font weight.", rust: "ComboBox text_size + line_height + section header styles", status: ImplementationStatus::Implemented },
    StyleDoc {
        class_or_token: ".combo-box",
        value: "flex flex-col gap-1",
        description: "Root field stack; the port matches the 4px gap but also enforces a local 180px minimum when not full width.",
        rust: "flex_col + gap(px(4.)) + min_w(px(180.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box[data-invalid=\"true\"] [data-slot=\"description\"]",
        value: "hidden",
        description: "Invalid fields hide the description slot so the error message can occupy the message position.",
        rust: "is_invalid/error_message branch",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".combo-box [data-slot=\"input\"]",
        value: "min-w-0 flex-1; focused status field border and background",
        description: "The input expands beside the trigger and uses the field focus treatment; the port delegates the inner field to Input.",
        rust: "Input::new + end_content(trigger) + Input focus styles",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__input-group",
        value: "relative isolate inline-flex items-center",
        description: "Input and trigger positioning context; the port provides a relative group but not the full DOM isolation contract.",
        rust: "input_group.relative + Input end_content",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__value",
        value: "text-sm wrap-break-word text-field-foreground empty:hidden; placeholder text-field-placeholder",
        description: "Selected-value row typography and placeholder treatment; the port supplies equivalent values only through value_content.",
        rust: "value_content(SelectionValue) + FIELD_TEXT + field.foreground",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__trigger",
        value: "absolute end-0 top-1/2 flex h-full shrink-0 -translate-y-1/2 pe-2 text-field-placeholder transition duration-150",
        description: "Chevron trigger positioning and chrome; the port draws a 20px local hit surface through Input's end content.",
        rust: "trigger flex + size(px(20.)) + muted + end_content",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__trigger hover/focus/pressed/disabled",
        value: "hover foreground; focus-visible ring; pressed opacity-70; disabled cursor and opacity-50",
        description: "The port has hover and disabled interaction gates, but no separate trigger focus ring and no pressed opacity treatment.",
        rust: "trigger.hover + interaction gates",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__trigger [data-slot=\"combo-box-trigger-default-icon\"]",
        value: "size-4; 150ms rotation when open; motion-reduce disables transition",
        description: "The port uses a 16px chevron, but it does not rotate the icon from closed to open.",
        rust: "svg size(FIELD_ICON) + CHEVRON_DOWN",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__popover",
        value: "min-w-(--trigger-width) scroll-py-1 scrollbar overflow-y-auto overscroll-contain bg-overlay p-0 text-sm; radius min(32px, var(--radius-3xl)); shadow-overlay",
        description: "Anchored to the field with an 8px gap, flipping to the side with more room when the preferred side cannot fit, keeping a 12px cross-axis viewport inset with the scroller capped to the available height; plain and virtual lists scroll within the available height and wheel input stays in the panel. The port uses its own 4px panel inset and exact trigger width rather than upstream p-0 and min-width.",
        rust: "scrollable_field_popover + max_h_full (plain) / Infer (virtual) + occlude + p(px(4.)) + overlay bg/shadow",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__popover[data-entering=\"true\"]",
        value: "fade-in-0 zoom-in-95 duration-150 ease-smooth with placement slide",
        description: "The port matches fade, 95% start, duration and curve through metric animation, but has no placement-specific slide.",
        rust: "anim::entering_zoom + Motion::LIST_IN",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__popover[data-exiting=\"true\"]",
        value: "fade-out zoom-out-95 duration-100 ease-smooth",
        description: "The port does not keep this panel in an exit phase with the matching shrink and fade.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    StyleDoc {
        class_or_token: ".combo-box__popover [data-slot=\"list-box\"]",
        value: "p-1.5 outline-none",
        description: "Listbox inset; the port places 4px around the outer panel and 8px/6px on each row instead.",
        rust: "panel p(px(4.)) + row px(8.)/py(6.)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box__popover [data-slot=\"list-box-item\"]",
        value: "px-2.5; single-select indicator has no transition",
        description: "The local rows have 8px horizontal padding and draw a tick for multiple selections only.",
        rust: "row px(px(8.)) + indicator(render)",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".combo-box--full-width / .combo-box__input-group--full-width",
        value: "w-full",
        description: "Full-width root and input group.",
        rust: "full_width(true) + root/input w_full",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const COMBO_BOX: ReferenceMetadata = ReferenceMetadata {
    page: "ComboBox",
    import_line: "use herogpui::components::combo_box::ComboBox;",
    source_module: "combo_box",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(pickers)/combo-box.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/combo-box/combo-box.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria-components/src/ComboBox.tsx + https://github.com/adobe/react-spectrum/blob/react-aria@3.51.0/packages/react-aria/src/combobox/useComboBox.ts + https://github.com/adobe/react-spectrum/blob/react-aria@3.51.0/packages/react-aria/src/i18n/useFilter.ts",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/combo-box.css",
    required_parts: COMBO_BOX_REQUIRED_PARTS,
    api: COMBO_BOX_API,
    parts: COMBO_BOX_PARTS,
    states: COMBO_BOX_STATES,
    styling: COMBO_BOX_STYLING,
};

const AUTOCOMPLETE_REQUIRED_PARTS: &[&str] = &[
    "Autocomplete",
    "Autocomplete.Trigger",
    "Autocomplete.Value",
    "Autocomplete.Indicator",
    "Autocomplete.ClearButton",
    "Autocomplete.Popover",
    "Autocomplete.Filter",
];

const AUTOCOMPLETE_API: &[ApiDoc] = &[
    ApiDoc { owner: "Autocomplete", prop: "placeholder", ty: "string", default: "'Select an item'", description: "Temporary trigger text while no item is selected.", rust_owner: "Autocomplete", rust: "placeholder(value)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "selectionMode", ty: "\"single\" | \"multiple\"", default: "\"single\"", description: "Whether one or multiple options may be selected.", rust_owner: "Autocomplete", rust: "selection_mode(SelectionMode)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "allowsEmptyCollection", ty: "boolean", default: "false", description: "Allows the trigger to open when the unfiltered collection has no items.", rust_owner: "Autocomplete", rust: "allows_empty_collection(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "isOpen", ty: "boolean", default: "—", description: "Controlled popover open state.", rust_owner: "Autocomplete", rust: "is_open(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "defaultOpen", ty: "boolean", default: "false", description: "Initial popover state for an uncontrolled Autocomplete.", rust_owner: "Autocomplete", rust: "default_open(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "onOpenChange", ty: "(isOpen: boolean) => void", default: "—", description: "Reports trigger, keyboard, selection, blur, Escape and outside-press open changes.", rust_owner: "Autocomplete", rust: "on_open_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "disabledKeys", ty: "Iterable<Key>", default: "—", description: "Keys of the options that remain visible but cannot be selected; per key, so one of two same-label items can be disabled alone.", rust_owner: "Autocomplete", rust: "disabled_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "isDisabled", ty: "boolean", default: "false", description: "Removes the trigger from interaction and form submission and prevents the popover from opening.", rust_owner: "Autocomplete", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "value", ty: "Key | Key[] | null", default: "—", description: "Controlled selection as an iterable of item keys; the trigger renders each selected key's label once in selection insertion order.", rust_owner: "Autocomplete", rust: "value(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "defaultValue", ty: "Key | Key[] | null", default: "—", description: "Uncontrolled selection seed as an iterable of item keys; the held selection survives filtering and reordering by key.", rust_owner: "Autocomplete", rust: "default_value(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "onChange", ty: "(value: Key | Key[] | null) => void", default: "—", description: "Reports the complete selection as an empty, single-key or multiple-key slice.", rust_owner: "Autocomplete", rust: "on_selection_change_all(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "isRequired", ty: "boolean", default: "false", description: "Marks an empty successful field invalid for native Form submission and labels it required.", rust_owner: "Autocomplete", rust: "is_required(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "isInvalid", ty: "boolean", default: "false", description: "Marks the field invalid, applies invalid chrome and exposes invalid Form state.", rust_owner: "Autocomplete", rust: "is_invalid(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "name", ty: "string", default: "—", description: "Names the live FormField returned by form_field().", rust_owner: "Autocomplete", rust: "name(value)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "fullWidth", ty: "boolean", default: "false", description: "Fills the available horizontal space.", rust_owner: "Autocomplete", rust: "full_width(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "variant", ty: "\"primary\" | \"secondary\"", default: "\"primary\"", description: "Selects the elevated or lower-emphasis field chrome.", rust_owner: "Autocomplete", rust: "variant(FieldVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete", prop: "className", ty: "string", default: "—", description: "Additional DOM classes have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "The port builds the documented compound anatomy monolithically from state and items.", rust_owner: "Autocomplete", rust: "new(state, items)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Trigger", prop: "className", ty: "string", default: "—", description: "Additional DOM classes for the trigger have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.Trigger", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "The field-shaped trigger is built in rather than an independently composable Group.", rust_owner: "Autocomplete", rust: "new(state, items)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Value", prop: "className", ty: "string", default: "—", description: "Additional DOM classes for the value have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.Value", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Custom value content receives the local SelectionValue projection.", rust_owner: "Autocomplete", rust: "value_content(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Indicator", prop: "className", ty: "string", default: "—", description: "Additional DOM classes for the indicator have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.Indicator", prop: "children", ty: "ReactNode", default: "default chevron", description: "Replaces the trigger chevron; the local closure also receives the open state.", rust_owner: "Autocomplete", rust: "indicator(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.ClearButton", prop: "className", ty: "string", default: "—", description: "Additional DOM classes for the clear button have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.ClearButton", prop: "onClick", ty: "(event: MouseEvent) => void", default: "—", description: "The local callback runs after selection clears but does not receive a browser MouseEvent; the button renders and clears without it.", rust_owner: "Autocomplete", rust: "on_clear(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.ClearButton", prop: "ref", ty: "RefObject<HTMLButtonElement>", default: "—", description: "Browser element refs have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.Popover", prop: "placement", ty: "PopoverPlacement", default: "\"bottom\"", description: "Eight cardinal/start/end placements are available; RAC's full 22-value placement union is not. The panel anchors to the measured trigger with an 8px gap and flips when the preferred side cannot fit and the opposite side has more room.", rust_owner: "Autocomplete", rust: "placement(Placement)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Popover", prop: "className", ty: "string", default: "—", description: "Additional DOM classes for the popover have no GPUI analogue.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Autocomplete.Popover", prop: "children", ty: "ReactNode", default: "—", description: "The built-in popover composes SearchField and ListBox equivalents rather than arbitrary children.", rust_owner: "Autocomplete", rust: "new(state, items)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Filter", prop: "filter", ty: "(text: string, input: string) => boolean", default: "useFilter contains", description: "Replaces the built-in matcher with a caller-supplied predicate.", rust_owner: "Autocomplete", rust: "filter(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Filter", prop: "inputValue", ty: "string", default: "—", description: "Controls the visible search text and filtering value.", rust_owner: "Autocomplete", rust: "input_value(value)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Filter", prop: "onInputChange", ty: "(value: string) => void", default: "—", description: "Reports proposed search edits while a controlled value remains owner-owned.", rust_owner: "Autocomplete", rust: "on_input_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Filter", prop: "children", ty: "ReactNode", default: "—", description: "The port supplies its SearchField and ListBox composition internally.", rust_owner: "Autocomplete", rust: "new(state, items)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "useFilter", prop: "sensitivity", ty: "\"base\" | \"accent\" | \"case\" | \"variant\"", default: "\"base\"", description: "Locale-sensitive matching is available through the separate Filter utility; Autocomplete accepts its predicate output.", rust_owner: "Autocomplete", rust: "filter(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "useFilter", prop: "contains / startsWith / endsWith", ty: "(string, substring) => boolean", default: "—", description: "The companion Filter utility provides all three matchers; the component consumes any matching closure.", rust_owner: "Autocomplete", rust: "filter(callback)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Value Render Props", prop: "defaultChildren", ty: "ReactNode", default: "—", description: "Built-in selected text or placeholder content supplied to the value closure.", rust_owner: "Autocomplete", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Value Render Props", prop: "isPlaceholder", ty: "boolean", default: "—", description: "Whether no selected item resolves from the collection.", rust_owner: "Autocomplete", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Value Render Props", prop: "selectedItems", ty: "Node[]", default: "—", description: "Selected collection items projected as their labels, indices and keys, once per selected item in selection insertion order, rather than as React collection nodes.", rust_owner: "Autocomplete", rust: "value_content(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Autocomplete.Value Render Props", prop: "selectedText", ty: "string", default: "—", description: "Selected labels joined with comma-space separators.", rust_owner: "Autocomplete", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Autocomplete.Value Render Props", prop: "state", ty: "SelectState", default: "—", description: "The browser SelectState object is not exposed; the local closure receives its resolved value projection.", rust_owner: "Autocomplete", rust: "—", status: ImplementationStatus::Unavailable },
];

const AUTOCOMPLETE_PARTS: &[PartDoc] = &[
    PartDoc { name: "Autocomplete", slot: "autocomplete", description: "Root field stack owning selection, open state, filtering, form state and the floating panel.", rust_owner: "Autocomplete", status: ImplementationStatus::Implemented },
    PartDoc { name: "Autocomplete.Trigger", slot: "autocomplete-trigger", description: "Field-shaped trigger with value, clear button and indicator; it is built in rather than independently composable.", rust_owner: "Autocomplete", status: ImplementationStatus::Partial },
    PartDoc { name: "Autocomplete.Value", slot: "autocomplete-value", description: "Selected labels or placeholder, with a SelectionValue render closure.", rust_owner: "Autocomplete", status: ImplementationStatus::Partial },
    PartDoc { name: "Autocomplete.Indicator", slot: "autocomplete-indicator", description: "Default chevron or caller content receiving the current open state.", rust_owner: "Autocomplete", status: ImplementationStatus::Implemented },
    PartDoc { name: "Autocomplete.ClearButton", slot: "autocomplete-clear-button", description: "Built-in clear affordance always mounted with the trigger; invisible and pointer-inert while the selection is empty, inert when disabled, and left working by read-only.", rust_owner: "Autocomplete", status: ImplementationStatus::Partial },
    PartDoc { name: "Autocomplete.Popover", slot: "autocomplete-popover", description: "Placement-aware overlay with pinned entry/exit motion, outside dismissal, SearchField and ListBox content.", rust_owner: "Autocomplete", status: ImplementationStatus::Partial },
    PartDoc { name: "Autocomplete.Filter", slot: "autocomplete-filter", description: "Search value and matcher boundary applied to the collection inside the popover.", rust_owner: "Autocomplete", status: ImplementationStatus::Partial },
];

const AUTOCOMPLETE_STATES: &[StateDoc] = &[
    StateDoc { state: "Open", selector: ".autocomplete__indicator[data-open=\"true\"]", description: "The trigger indicator receives the live open state and the popover is mounted.", rust: "open + indicator(render)", status: ImplementationStatus::Implemented },
    StateDoc { state: "Hovered", selector: ".autocomplete__trigger:hover, .autocomplete__trigger[data-hovered=\"true\"]", description: "Enabled trigger hover changes its field background while the clear button inside is not itself hovered; the color change is not interpolated.", rust: "field.hover(background)", status: ImplementationStatus::Partial },
    StateDoc { state: "Focus visible", selector: ".autocomplete__trigger[data-focus-visible=\"true\"]", description: "Keyboard-visible trigger focus draws the offset status ring.", rust: "ring_if_focused(field, handle, true, ...)", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled", selector: ".autocomplete__trigger[data-disabled=\"true\"]", description: "The trigger leaves the tab order, cannot open and is omitted from FormData.", rust: "is_disabled + interaction/form gates", status: ImplementationStatus::Implemented },
    StateDoc { state: "Read only", selector: ".autocomplete[data-readonly=\"true\"]", description: "The selection remains visible while opening and query edits are inert; v3 gates the clear button on disabled only, so it keeps working.", rust: "is_read_only + interaction gates", status: ImplementationStatus::Implemented },
    StateDoc { state: "Invalid", selector: ".autocomplete[data-invalid=\"true\"]", description: "Invalid chrome and error content replace the normal description and block native Form submission.", rust: "is_invalid/error_message + form_state", status: ImplementationStatus::Implemented },
    StateDoc { state: "Required", selector: ".autocomplete[data-required=\"true\"]", description: "The label and FormField carry required state; an empty value blocks native submission.", rust: "is_required + form_field", status: ImplementationStatus::Implemented },
    StateDoc { state: "Placeholder", selector: ".autocomplete__value[data-placeholder=\"true\"]", description: "Missing selected items use the placeholder palette and value render state.", rust: "is_placeholder + value_content", status: ImplementationStatus::Implemented },
    StateDoc { state: "Empty selection", selector: ".autocomplete__clear-button[data-empty=\"true\"]", description: "The always-mounted clear affordance turns invisible and pointer-inert (opacity-0 with pointer-events-none) while the selection is empty.", rust: "clear_empty + clear_active gates", status: ImplementationStatus::Implemented },
    StateDoc { state: "Multiple selection", selector: "selectionMode=\"multiple\"", description: "Rows toggle membership, keep the panel open and report the whole selection.", rust: "selection_mode(Multiple) + on_selection_change_all", status: ImplementationStatus::Implemented },
    StateDoc { state: "Empty collection", selector: "allowsEmptyCollection", description: "An empty unfiltered collection can open only when explicitly allowed.", rust: "toggle_allowed + allows_empty_collection", status: ImplementationStatus::Implemented },
    StateDoc { state: "Entering", selector: ".autocomplete__popover[data-entering=\"true\"]", description: "The panel fades and grows from 95% over 250ms with ease-out-fluid; placement slide is not reproduced.", rust: "entering_zoom + Motion::FLUID_IN", status: ImplementationStatus::Partial },
    StateDoc { state: "Exiting", selector: ".autocomplete__popover[data-exiting=\"true\"]", description: "The retained panel fades and shrinks to 95% over 100ms with ease-out-quad.", rust: "overlay_phase + exiting + Motion::FLUID_OUT", status: ImplementationStatus::Implemented },
];

const AUTOCOMPLETE_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: "text-sm / .header", value: "14px/20px value, option and empty-state text; Header 12px/16px medium px-2 pt-1.5 pb-1", description: "Text keeps its line height under surrounding styles. Section headers have 8px horizontal, 6px top and 4px bottom padding; selecting an option does not add font weight.", rust: "Autocomplete text_size + line_height + section header styles", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete", value: "flex flex-col gap-1", description: "Four-pixel field stack with label and message siblings.", rust: "flex_col + gap(px(4.))", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete__trigger", value: "min-h-9 rounded-field border bg-field px-3 py-2 text-sm shadow-field", description: "The port matches the field tokens but adds a 180px local floor when fullWidth is false.", rust: "FIELD_HEIGHT + apply_field_chrome + px(px(12.))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__trigger transitions", value: "background-color 150ms ease-smooth; border-color 150ms ease-smooth; box-shadow 150ms ease-out; reduced motion none", description: "Static hover, focus and invalid colors match, but those trigger-color changes still swap in one frame.", rust: "apply_field_chrome + field.hover", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete--secondary .autocomplete__trigger", value: "shadow-none bg-default; hover default-hover; focus default", description: "Secondary field chrome uses the lower-emphasis default palette.", rust: "FieldVariant::Secondary + apply_field_chrome", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete__value", value: "flex-1 text-start text-sm wrap-break-word; placeholder field color", description: "Typography and colors match, while the port truncates long selected text instead of wrapping it.", rust: "flex_1 + truncate + FIELD_TEXT + field colors", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__indicator", value: "absolute inset-y-0 end-2 size-4; open rotate-180; transition 150ms", description: "Position and size match; the built-in glyph swaps direction and custom content receives open state, but no rotation interpolation is applied.", rust: "absolute right(px(8.)) + FIELD_ICON + indicator(render)", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__clear-button", value: "size-5 rounded-xl p-1; icon size-3.5; hover default-hover; pressed scale .93", description: "Size, radius, padding and hover match; pressed scale and the 150ms visible opacity transition are not reproduced.", rust: "size(px(20.)) + p(px(4.)) + small_radius + hover", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__popover", value: "trigger width; overflow hidden; bg-overlay pt-2 text-sm; radius min(32px, radius-3xl); shadow-overlay", description: "Anchors to the measured trigger with an 8px gap, flipping to the side with more room when the preferred side cannot fit and keeping a 12px cross-axis viewport inset with the scroller capped to the available height; the search stays visible while the inner list scrolls and shrinks to the available height within the upstream 320px max, and virtual paging follows the visible list height. The reduced placement vocabulary and placement slide remain unported.", rust: "placement(Placement) + pt(px(8.)) + max_h(px(320.)) + scroll + overlay bg/shadow", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__popover[data-entering=\"true\"]", value: "fade-in-0 zoom-in-95 duration-250 ease-out-fluid with placement slide", description: "Fade, zoom, duration and curve match; placement-specific one-step translation is not reproduced.", rust: "entering_zoom + Motion::FLUID_IN", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".autocomplete__popover[data-exiting=\"true\"]", value: "fade-out zoom-out-95 duration-100 ease-out-quad", description: "Exit fade, geometry, duration and curve match through retained overlay frames.", rust: "exiting + Motion::FLUID_OUT", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete__popover [data-slot=\"search-field\"]", value: "shrink-0 px-3 py-1", description: "The built-in secondary SearchField uses the documented 12px/4px wrapper inset and stays visible while the inner list scrolls.", rust: "SearchField::new + px(px(12.)) + py(px(4.))", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete__popover [data-slot=\"list-box\"]", value: "max-h-[320px] min-h-0 overflow-y-auto p-1.5", description: "Both normal and virtual lists use the upstream 320px cap with a six-pixel inset; the list shrinks below the cap to the available height and virtual paging follows the visible list height.", rust: "max_h/h(px(320.)) + p(px(6.)) + scroll", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete__popover [data-slot=\"list-box-item\"]", value: "px-2.5", description: "Rows use the documented ten-pixel horizontal inset and the shared ListBox item geometry.", rust: "row px(px(10.)) + FIELD_HEIGHT + soft_radius", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".autocomplete--full-width / .autocomplete__trigger--full-width", value: "w-full", description: "Full-width root and trigger.", rust: "full_width(true) + w_full", status: ImplementationStatus::Implemented },
];

pub(super) const AUTOCOMPLETE: ReferenceMetadata = ReferenceMetadata {
    page: "Autocomplete",
    import_line: "use herogpui::components::autocomplete::Autocomplete;",
    source_module: "autocomplete",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(pickers)/autocomplete.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/autocomplete/autocomplete.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria-components/src/Autocomplete.tsx + https://github.com/adobe/react-spectrum/blob/react-stately@3.49.0/packages/react-stately/src/autocomplete/useAutocompleteState.ts",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/autocomplete.css",
    required_parts: AUTOCOMPLETE_REQUIRED_PARTS,
    api: AUTOCOMPLETE_API,
    parts: AUTOCOMPLETE_PARTS,
    states: AUTOCOMPLETE_STATES,
    styling: AUTOCOMPLETE_STYLING,
};

const SELECT_REQUIRED_PARTS: &[&str] = &[
    "Select",
    "Select.Trigger",
    "Select.Value",
    "Select.Indicator",
    "Select.Popover",
];

const SELECT_API: &[ApiDoc] = &[
    ApiDoc { owner: "Select", prop: "placeholder", ty: "string", default: "'Select an item'", description: "Temporary text shown while no option is selected.", rust_owner: "Select", rust: "placeholder(text)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "selectionMode", ty: "\"single\" | \"multiple\"", default: "\"single\"", description: "Chooses single or multiple selection.", rust_owner: "Select", rust: "selection_mode(SelectionMode)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "isOpen", ty: "boolean", default: "—", description: "Controlled popover open state.", rust_owner: "Select", rust: "is_open(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "defaultOpen", ty: "boolean", default: "—", description: "Initial uncontrolled popover state.", rust_owner: "Select", rust: "default_open(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "onOpenChange", ty: "(isOpen: boolean) => void", default: "—", description: "Reports popover state changes.", rust_owner: "Select", rust: "on_open_change(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "disabledKeys", ty: "Iterable<Key>", default: "—", description: "Keys which cannot be selected or focused.", rust_owner: "Select", rust: "disabled_keys(keys)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "isDisabled", ty: "boolean", default: "—", description: "Disables the field and its interactions.", rust_owner: "Select", rust: "is_disabled(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "value", ty: "Key | Key[] | null", default: "—", description: "Controlled selection; GPUI separates scalar and multiple values into typed builders.", rust_owner: "Select", rust: "value(Option<usize>) / selected_indices(indices)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "defaultValue", ty: "Key | Key[] | null", default: "—", description: "Initial uncontrolled scalar or multiple selection, seeded once.", rust_owner: "Select", rust: "default_value(Option<usize>) / default_selected_indices(indices)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "onChange", ty: "(value: Key | Key[] | null) => void", default: "—", description: "Selection callback; scalar and multiple signatures use separate builders.", rust_owner: "Select", rust: "on_change(callback) / on_selection_change_all(callback)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "isRequired", ty: "boolean", default: "—", description: "Draws the required marker and makes an empty live FormField block native submission and focus the trigger.", rust_owner: "Select", rust: "is_required(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "isInvalid", ty: "boolean", default: "—", description: "Forces the field into its invalid state.", rust_owner: "Select", rust: "is_invalid(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "name", ty: "string", default: "—", description: "Exports a live single- or multiple-selection FormField with disabled omission and reset behavior.", rust_owner: "Select", rust: "name(name)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "autoComplete", ty: "string", default: "—", description: "Browser autofill hint; GPUI has no browser input autocomplete channel.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select", prop: "fullWidth", ty: "boolean", default: "false", description: "Expands both the root and trigger to the available width.", rust_owner: "Select", rust: "full_width(bool)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "variant", ty: "\"primary\" | \"secondary\"", default: "\"primary\"", description: "Selects the shadowed or lower-emphasis field chrome.", rust_owner: "Select", rust: "variant(FieldVariant)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select", prop: "className", ty: "string", default: "—", description: "Additional CSS classes.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Compound parts; GPUI takes a typed option collection and draws the field structure.", rust_owner: "Select", rust: "new(id, options)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Select", prop: "render", ty: "DOMRenderFunction<SelectRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Trigger", prop: "className", ty: "string", default: "—", description: "Additional trigger classes.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Trigger", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "The trigger is built in rather than separately replaceable.", rust_owner: "Select", rust: "new(id, options)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Select.Value", prop: "className", ty: "string", default: "—", description: "Additional value classes.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Value", prop: "children", ty: "ReactNode | RenderFunction", default: "—", description: "Custom value content receives the live selected-value projection.", rust_owner: "Select", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Select.Value", prop: "render", ty: "DOMRenderFunction<SelectValueRenderProps>", default: "—", description: "DOM element substitution has no GPUI equivalent.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Indicator", prop: "className", ty: "string", default: "—", description: "Additional trigger-indicator classes.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Indicator", prop: "children", ty: "ReactNode", default: "—", description: "The similarly named GPUI builder replaces option checkmarks, not the trigger chevron.", rust_owner: "Select", rust: "indicator(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Select.Popover", prop: "placement", ty: "Placement", default: "\"bottom\"", description: "Eight cardinal/start/end placements are available; RAC's full 22-value placement union is not. The panel anchors to the measured trigger with an 8px gap and flips when the preferred side cannot fit and the opposite side has more room.", rust_owner: "Select", rust: "placement(Placement)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Select.Popover", prop: "className", ty: "string", default: "—", description: "Additional popover classes.", rust_owner: "Select", rust: "—", status: ImplementationStatus::Unavailable },
    ApiDoc { owner: "Select.Popover", prop: "children", ty: "ReactNode", default: "—", description: "The popover draws the typed options rather than arbitrary content children.", rust_owner: "Select", rust: "new(id, options)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Render Props", prop: "defaultChildren", ty: "ReactNode", default: "—", description: "Default selected text supplied to the value closure.", rust_owner: "Select", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Render Props", prop: "isPlaceholder", ty: "boolean", default: "—", description: "Placeholder state supplied to the value closure.", rust_owner: "Select", rust: "value_content(render)", status: ImplementationStatus::Implemented },
    ApiDoc { owner: "Render Props", prop: "state", ty: "SelectState", default: "—", description: "The closure receives a selected-value projection, not the full mutable SelectState object.", rust_owner: "Select", rust: "value_content(render)", status: ImplementationStatus::Partial },
    ApiDoc { owner: "Render Props", prop: "selectedItems", ty: "Node[]", default: "—", description: "Selected items and indices supplied to the value closure.", rust_owner: "Select", rust: "value_content(render)", status: ImplementationStatus::Implemented },
];

const SELECT_PARTS: &[PartDoc] = &[
    PartDoc { name: "Select", slot: "select", description: "Selection, form and overlay state owner.", rust_owner: "Select", status: ImplementationStatus::Implemented },
    PartDoc { name: "Select.Trigger", slot: "select-trigger", description: "Focus and press target; its internal content is not separately composable.", rust_owner: "Select", status: ImplementationStatus::Partial },
    PartDoc { name: "Select.Value", slot: "select-value", description: "Placeholder or selected-value content with a live render projection.", rust_owner: "Select", status: ImplementationStatus::Implemented },
    PartDoc { name: "Select.Indicator", slot: "select-indicator", description: "Built-in trigger chevron; the public indicator closure belongs to list options instead.", rust_owner: "Select", status: ImplementationStatus::Partial },
    PartDoc { name: "Select.Popover", slot: "select-popover", description: "List surface anchored to the trigger; it can flip within the window and supports a reduced placement vocabulary.", rust_owner: "Select", status: ImplementationStatus::Partial },
];

const SELECT_STATES: &[StateDoc] = &[
    StateDoc { state: "Hovered trigger", selector: ".select__trigger[data-hovered]", description: "Field background changes on pointer hover.", rust: "trigger hover style", status: ImplementationStatus::Implemented },
    StateDoc { state: "Focus visible", selector: ".select__trigger[data-focus-visible]", description: "Keyboard focus rings the trigger and applies the field-focus background. Enter and Space finish a single selection without reopening a popup closed by its owner.", rust: "ring_if_focused + focus-visible background", status: ImplementationStatus::Implemented },
    StateDoc { state: "Disabled", selector: ".select__trigger[data-disabled]", description: "Field is dimmed, inert, untabbable and omitted from FormData while disabled.", rust: "is_disabled + live FormField is_successful", status: ImplementationStatus::Implemented },
    StateDoc { state: "Invalid", selector: ".select[data-invalid]", description: "Invalid field chrome applies the focus background and suppresses the description row.", rust: "is_invalid + description suppression", status: ImplementationStatus::Implemented },
    StateDoc { state: "Placeholder", selector: ".select__value[data-placeholder]", description: "Empty value uses muted placeholder colour.", rust: "SelectionValue::is_placeholder", status: ImplementationStatus::Implemented },
    StateDoc { state: "Open indicator", selector: ".select__indicator[data-open]", description: "The glyph swaps direction immediately instead of rotating over 150ms.", rust: "is_open chevron selection", status: ImplementationStatus::Partial },
    StateDoc { state: "Entering", selector: ".select__popover[data-entering]", description: "150ms Smooth fade and 95% zoom match; placement-specific four-pixel translation is absent.", rust: "overlay_phase Entering + entering_zoom", status: ImplementationStatus::Partial },
    StateDoc { state: "Exiting", selector: ".select__popover[data-exiting]", description: "100ms Smooth fade and zoom to 95%.", rust: "overlay_phase Exiting + exiting", status: ImplementationStatus::Implemented },
    StateDoc { state: "Selected option", selector: ".list-box-item[data-selected]", description: "Selection is visible, but GPUI adds accent text and weight beyond v3's indicator-only state.", rust: "selected option style + indicator", status: ImplementationStatus::Partial },
    StateDoc { state: "Focused option", selector: ".list-box-item[data-focused]", description: "Keyboard focus is visible, but uses a two-pixel border rather than v3's status ring.", rust: "focused option border", status: ImplementationStatus::Partial },
    StateDoc { state: "Disabled option", selector: ".list-box-item[data-disabled]", description: "Disabled rows are dimmed and skipped by navigation and selection.", rust: "disabled_keys", status: ImplementationStatus::Implemented },
    StateDoc { state: "Multiple selection", selector: ".select[data-selection-mode=multiple]", description: "The popover stays open while multiple options are toggled.", rust: "SelectionMode::Multiple", status: ImplementationStatus::Implemented },
];

const SELECT_STYLING: &[StyleDoc] = &[
    StyleDoc { class_or_token: "text-sm / .header", value: "14px/20px value and option text; Header 12px/16px medium px-2 pt-1.5 pb-1", description: "Text keeps its line height under surrounding styles. Section headers have 8px horizontal, 6px top and 4px bottom padding; selecting an option does not add font weight.", rust: "Select text_size + line_height + section header styles", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select", value: "flex flex-col gap-1", description: "The inner field wrapper stacks at four pixels only when label or description content exists; the root adds a 320px cap unless full width is enabled.", rust: "conditional flex_col + gap(px(4.)) + default max_w(px(320.))", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select[data-invalid] [data-slot=description]", value: "hidden", description: "Description text is suppressed while the field is invalid.", rust: "description rendered only when !is_invalid", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select > [data-slot=label]", value: "w-fit", description: "The shared label has natural content but does not explicitly opt out of flex-column stretching.", rust: "Label natural width", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__trigger", value: "min-h-9 px-3 py-2 rounded-field border bg-field shadow-field text-sm", description: "Primary trigger dimensions, chrome and typography.", rust: "h(px(36.)) + px(px(12.)) + field chrome", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__trigger transitions", value: "background-color and border-color 150ms Smooth; box-shadow 150ms Out", description: "Pinned property transitions are immediate in GPUI.", rust: "static trigger style", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__trigger:hover", value: "bg-field-hover", description: "Hover field background.", rust: "hover background", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__trigger:focus-visible", value: "status-focused bg-field-focus", description: "Ring and background match; the focus background does not interpolate.", rust: "ring_if_focused + field focus background", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__trigger[data-invalid]", value: "status-invalid-field bg-field-focus", description: "Invalid field treatment and focus background.", rust: "invalid field border/ring + focus background", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__trigger[data-disabled]", value: "status-disabled", description: "Disabled opacity and interaction treatment.", rust: "disabled_opacity + listener suppression", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select--secondary .select__trigger", value: "shadow-none bg-default hover:bg-default-hover", description: "Lower-emphasis secondary trigger.", rust: "FieldVariant::Secondary", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__value", value: "flex-1 text-start text-sm wrap-break-word", description: "Alignment and size match, but GPUI truncates instead of wrapping long values.", rust: "flex_1 + text_size(px(14.)) + truncate", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__value[data-placeholder]", value: "text-muted", description: "Placeholder colour.", rust: "muted foreground", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__value [data-slot=list-box-item-indicator]", value: "hidden", description: "Selected-value rendering does not include option checkmarks.", rust: "SelectionValue text/items only", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__indicator", value: "absolute end-2 size-4; rotate 150ms when open", description: "GPUI uses a flow-positioned chevron and swaps glyphs without rotation animation.", rust: "chevron_down/chevron_up", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__popover", value: "min trigger width; overflow-auto; bg-overlay; radius min(32px, 3xl); shadow-overlay", description: "Anchored to the measured trigger width with an 8px gap, flipping to the side with more room when the preferred side cannot fit and keeping a 12px cross-axis viewport inset with the scroller capped to the available height; the plain list scrolls the panel and the virtual list sizes itself to the same bound. Overlay surface, radius and shadow.", rust: "scrollable_field_popover + max_h_full (plain) / Infer (virtual) + floating_radius + overlay_shadow", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__popover[data-entering]", value: "150ms ease-smooth fade-in zoom-in-95 + placement slide 4px", description: "Fade and zoom match; transform origin and placement slide are absent.", rust: "Motion::LIST_IN + entering_zoom", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select__popover[data-exiting]", value: "100ms ease-smooth fade-out zoom-out-95", description: "Exit motion matches.", rust: "Motion::LIST_OUT + exiting", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select__popover .list-box / .list-box-item", value: "p-1.5 / px-2.5", description: "Six-pixel list inset and ten-pixel option-row horizontal padding.", rust: "panel p(px(6.)) + option px(px(10.))", status: ImplementationStatus::Implemented },
    StyleDoc { class_or_token: ".select:not([data-selection-mode=multiple]) indicators", value: "transition-none", description: "GPUI has no indicator transition in either selection mode.", rust: "static indicator", status: ImplementationStatus::Partial },
    StyleDoc { class_or_token: ".select--full-width / .select__trigger--full-width", value: "w-full", description: "Both the root and trigger expand to the available container width.", rust: "root.w_full() + field.w_full()", status: ImplementationStatus::Implemented },
];

pub(super) const SELECT: ReferenceMetadata = ReferenceMetadata {
    page: "Select",
    import_line: "use herogpui::components::select::Select;",
    source_module: "select",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(pickers)/select.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/select/select.tsx + https://github.com/adobe/react-spectrum/blob/react-aria-components@1.20.0/packages/react-aria-components/src/Select.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/select.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/list-box.css + https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/list-box-item.css",
    required_parts: SELECT_REQUIRED_PARTS,
    api: SELECT_API,
    parts: SELECT_PARTS,
    states: SELECT_STATES,
    styling: SELECT_STYLING,
};
