//! typography reference metadata.

use super::*;

const KBD_REQUIRED_PARTS: &[&str] = &["Kbd", "Kbd.Abbr", "Kbd.Content"];

const KBD_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Kbd",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Content of the key. v3 renders plain text directly in the root; the port's children are laid out by the same centered row, so the key text needs no wrapper part.",
        rust_owner: "Kbd",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Kbd",
        prop: "variant",
        ty: "\"default\" | \"light\"",
        default: "\"default\"",
        description: "Visual variant of the key. Both variants share the base key style; light only clears the background for inline prose.",
        rust_owner: "Kbd",
        rust: "variant(KbdVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Kbd",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Kbd.Abbr",
        prop: "title",
        ty: "string",
        default: "—",
        description: "Accessibility title for the key (e.g., \"Command\" for ⌘). v3 sets it on the `<abbr>` element; gpui-pre 0.3.3 has no accessibility tree and the part renders no element, so there is nothing to carry a title.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Kbd.Abbr",
        prop: "keyValue",
        ty: "KbdKey",
        default: "—",
        description: "Named key (`\"command\"`, `\"shift\"`, …) that resolves the symbol and the accessibility title. The symbol/title map rides on the `<abbr>` element, which gpui-pre 0.3.3 has no accessibility tree to express, so the port takes the key symbol as ordinary children instead.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Kbd.Abbr",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "The symbol or text to display. v3 wraps it in an `<abbr title>` for screen readers; the part is not rendered here at all (no accessibility element), so nothing owns its children.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Kbd.Abbr",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the abbreviation.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Kbd.Content",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "The key text itself; the port draws it directly inside the root row, whose centering already covers the content wrapper's flex centering.",
        rust_owner: "Kbd",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Kbd.Content",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the content wrapper.",
        rust_owner: "Kbd",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

// The v3.2.4 docs also carry a `Kbd.Key` prop table, but the pinned
// `kbd.tsx` exports only `KbdRoot`, `KbdAbbr` and `KbdContent` — the table
// has no backing component, so it is deliberately not ported.
const KBD_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Kbd",
        slot: "— (no data-slot)",
        description: "Composition root on the `.kbd` BEM class — v3's Kbd carries no `data-slot`: an inline-flex, centered key chip at the key radius — `h-6 px-2 text-sm font-medium text-muted` on `bg-default`, space between multiple keys, `whitespace-nowrap` and v3's negative word-spacing. Static: no states.",
        rust_owner: "Kbd",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Kbd.Abbr",
        slot: "— (no data-slot)",
        description: "The `<abbr title>` v3 wraps the symbol in for screen readers, styled by the `.kbd__abbr` BEM class. gpui-pre 0.3.3 has no accessibility tree and no abbr element, so the port renders no such part and the key text is drawn as the root's own child.",
        rust_owner: "Kbd",
        status: ImplementationStatus::Unavailable,
    },
    PartDoc {
        name: "Kbd.Content",
        slot: "— (no data-slot)",
        description: "Content wrapper on the `.kbd__content` BEM class: a centered flex box. The port folds it into the root row's centering and draws the key text directly.",
        rust_owner: "Kbd",
        status: ImplementationStatus::Partial,
    },
];

// `.kbd` declares no state utilities and the docs name no interactive states:
// a key chip is a static display, not a control.
const KBD_STATES: &[StateDoc] = &[];

const KBD_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".kbd",
        value: "inline-flex h-6 items-center space-x-0.5 rounded-lg bg-default px-2 text-center font-sans text-sm font-medium whitespace-nowrap text-muted rtl:space-x-reverse; word-spacing: -0.25rem",
        description: "Key chip: 24px tall, 8px side padding, 14px medium muted text at the 20px text-sm leading on `bg-default` at the key radius, with 2px between multiple keys and no border or shadow. The negative word-spacing is not portable — gpui-pre 0.3.3 has no word-spacing — and the root is a block-level flex rather than inline-flex.",
        rust: "flex + items_center + justify_center + text_center + gap(px(2.)) + px(px(8.)) + h(px(24.)) + key_radius + text_size(px(14.)) + line_height(px(20.)) + FontWeight::MEDIUM + whitespace_nowrap + colors.muted",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".kbd__abbr",
        value: "display: flex; justify-content: center; align-items: center; width: 100%; height: 100%; text-decoration: none",
        description: "The abbreviation element fills the key and strips its underline. Not rendered: gpui-pre 0.3.3 has no accessibility element to express it.",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    StyleDoc {
        class_or_token: ".kbd__content",
        value: "display: flex; justify-content: center; align-items: center",
        description: "Centered content wrapper; the root row's centering covers it.",
        rust: "folded into Kbd's items_center + justify_center",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".kbd--light",
        value: "bg-transparent",
        description: "The light variant only clears the background; every other style is inherited from the base rule, which is why the variant branch changes nothing else.",
        rust: "KbdVariant::Light => el.bg(transparent_black())",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const KBD: ReferenceMetadata = ReferenceMetadata {
    page: "Kbd",
    import_line: "use herogpui::components::kbd::Kbd;",
    source_module: "kbd",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(typography)/kbd.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/kbd/kbd.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/kbd.css",
    required_parts: KBD_REQUIRED_PARTS,
    api: KBD_API,
    parts: KBD_PARTS,
    states: KBD_STATES,
    styling: KBD_STYLING,
};

const TYPOGRAPHY_REQUIRED_PARTS: &[&str] = &["Typography", "Typography.Prose"];

const TYPOGRAPHY_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Typography",
        prop: "type",
        ty: "'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'body' | 'body-sm' | 'body-xs' | 'code'",
        default: "'body'",
        description: "Semantic typography style, carrying the tagged scale's size/line-height pair, the heading weight and the code family. Named `kind` because `type` is a Rust keyword.",
        rust_owner: "Typography",
        rust: "kind(TypographyType)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography",
        prop: "align",
        ty: "'start' | 'center' | 'end' | 'justify'",
        default: "'start'",
        description: "Text alignment. gpui-pre 0.3.3 has no `text-justify`; justify falls back to start alignment.",
        rust_owner: "Typography",
        rust: "align(TextAlign)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Typography",
        prop: "color",
        ty: "'default' | 'muted'",
        default: "'default'",
        description: "Text color role.",
        rust_owner: "Typography",
        rust: "color(TextColor)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography",
        prop: "weight",
        ty: "'normal' | 'medium' | 'semibold' | 'bold'",
        default: "—",
        description: "Font weight override over the type's default.",
        rust_owner: "Typography",
        rust: "weight(FontWeight)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography",
        prop: "truncate",
        ty: "boolean",
        default: "—",
        description: "Truncates the text to one line with an ellipsis.",
        rust_owner: "Typography",
        rust: "truncate(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "React Aria render prop that re-targets the rendered element. The port has no element polymorphism to re-target — every type draws a plain div — so there is nothing for a render function to override.",
        rust_owner: "Typography",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Typography",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Text content, either as the constructor's text or as composed children.",
        rust_owner: "Typography",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Typography.Heading",
        prop: "level",
        ty: "1 | 2 | 3 | 4 | 5 | 6",
        default: "1",
        description: "Maps to `type=\"h1\"` through `type=\"h6\"`; higher levels clamp to h6.",
        rust_owner: "Typography",
        rust: "heading(u8, text)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography.Paragraph",
        prop: "size",
        ty: "'base' | 'sm' | 'xs'",
        default: "'base'",
        description: "Maps to the `body`, `body-sm` and `body-xs` types.",
        rust_owner: "Typography",
        rust: "paragraph(ParagraphSize, text)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography.Code",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "The inline code text; `Typography.Code` is the `code` type.",
        rust_owner: "Typography",
        rust: "code(text)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Typography.Prose",
        prop: "children",
        ty: "React.ReactNode",
        default: "—",
        description: "Rich content, rendered in order with `text-foreground`. Upstream styles each descendant tag through CSS selectors (`p`, `code`, `a`, lists, …); GPUI has no selectors and no ancestor context propagation, so children must be already-semantic elements such as `Typography` that carry their own metrics.",
        rust_owner: "Prose",
        rust: "ParentElement::extend",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Typography.Prose",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Prose",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const TYPOGRAPHY_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Typography",
        slot: "typography",
        description: "Root primitive: v3 maps each type to its semantic element (`h1`–`h6`, `p`, `code`) through React Aria's Text, and headings tighten their tracking. gpui-pre 0.3.3 has no DOM semantics and no letter-spacing, so the same metrics, weight and color render on a plain div.",
        rust_owner: "Typography",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Typography.Prose",
        slot: "prose",
        description: "Prose container: `text-foreground` with the children rendered in order. The per-tag descendant styles in `.typography-prose h1`, `p`, `code`, `a`, lists and friends need CSS selectors GPUI does not have, so nothing is inherited automatically.",
        rust_owner: "Prose",
        status: ImplementationStatus::Partial,
    },
];

// `.typography` declares no state utilities and the docs name no interactive
// states: typography is display-only.
const TYPOGRAPHY_STATES: &[StateDoc] = &[];

const TYPOGRAPHY_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".typography",
        value: "text-foreground",
        description: "Base primitive: foreground color only; every metric comes from the type modifier.",
        rust: "text_color(colors.foreground)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--h1",
        value: "text-4xl font-semibold tracking-tight",
        description: "36px semibold at the 40px text-4xl leading. `tracking-tight` is an honest limitation: gpui-pre 0.3.3 has no letter-spacing.",
        rust: "H1 => text_size(px(36.)) + line_height(px(40.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--h2",
        value: "text-3xl font-semibold tracking-tight",
        description: "30/36 semibold; `tracking-tight` unsupported (no letter-spacing in GPUI).",
        rust: "H2 => text_size(px(30.)) + line_height(px(36.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--h3",
        value: "text-2xl font-semibold tracking-tight",
        description: "24/32 semibold; `tracking-tight` unsupported (no letter-spacing in GPUI).",
        rust: "H3 => text_size(px(24.)) + line_height(px(32.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--h4",
        value: "text-xl font-semibold tracking-tight",
        description: "20/28 semibold; `tracking-tight` unsupported (no letter-spacing in GPUI).",
        rust: "H4 => text_size(px(20.)) + line_height(px(28.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--h5",
        value: "text-lg font-semibold tracking-tight",
        description: "18/28 semibold; `tracking-tight` unsupported (no letter-spacing in GPUI).",
        rust: "H5 => text_size(px(18.)) + line_height(px(28.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--h6",
        value: "text-base font-semibold tracking-tight",
        description: "16/24 semibold; `tracking-tight` unsupported (no letter-spacing in GPUI).",
        rust: "H6 => text_size(px(16.)) + line_height(px(24.)) + FontWeight::SEMIBOLD",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--body",
        value: "text-base leading-7",
        description: "16px body copy at the 28px leading-7.",
        rust: "Body => text_size(px(16.)) + line_height(px(28.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--body-sm",
        value: "text-sm leading-6",
        description: "14px text at the 24px leading-6.",
        rust: "BodySm => text_size(px(14.)) + line_height(px(24.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--body-xs",
        value: "text-xs leading-5",
        description: "12px text at the 20px leading-5.",
        rust: "BodyXs => text_size(px(12.)) + line_height(px(20.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--code",
        value: "rounded-md bg-default px-1.5 py-0.5 font-mono text-sm text-foreground",
        description: "Inline code chip: mono 14/20 text painted on the `bg-default` chip at the mark radius with 6px/2px padding.",
        rust: "Code => font_family(MONO) + bg(colors.default.color) + mark_radius + px(px(6.)) + py(px(2.)) + text_size(px(14.)) + line_height(px(20.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--align-start",
        value: "text-start",
        description: "Start alignment, the default.",
        rust: "TextAlign::Start => text_left",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--align-center",
        value: "text-center",
        description: "Centered alignment.",
        rust: "TextAlign::Center => text_center",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--align-end",
        value: "text-end",
        description: "End alignment.",
        rust: "TextAlign::End => text_right",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--align-justify",
        value: "text-justify",
        description: "Justified text: gpui-pre 0.3.3 has no `text-justify`, so the port falls back to start alignment.",
        rust: "TextAlign::Justify => text_left",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".typography--color-default",
        value: "text-foreground",
        description: "Default color role.",
        rust: "TextColor::Default => colors.foreground",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--color-muted",
        value: "text-muted",
        description: "Muted color role.",
        rust: "TextColor::Muted => colors.muted",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--truncate",
        value: "block truncate",
        description: "Single-line ellipsis truncation; the port's root div is already a block, so only the truncation applies.",
        rust: "truncate()",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--weight-normal",
        value: "font-normal",
        description: "Normal (400) weight override, demonstrated in the gallery weight examples.",
        rust: "FontWeight::Normal => gpui::FontWeight::NORMAL",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--weight-medium",
        value: "font-medium",
        description: "Medium (500) weight override, demonstrated in the gallery weight examples.",
        rust: "FontWeight::Medium => gpui::FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--weight-semibold",
        value: "font-semibold",
        description: "Semibold (600) weight override, demonstrated in the gallery weight examples.",
        rust: "FontWeight::Semibold => gpui::FontWeight::SEMIBOLD",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".typography--weight-bold",
        value: "font-bold",
        description: "Bold (700) weight override, demonstrated in the gallery weight examples.",
        rust: "FontWeight::Bold => gpui::FontWeight::BOLD",
        status: ImplementationStatus::Implemented,
    },
];

pub(super) const TYPOGRAPHY: ReferenceMetadata = ReferenceMetadata {
    page: "Typography",
    import_line: "use herogpui::components::typography::{Typography, TypographyType};",
    source_module: "typography",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(typography)/typography.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/typography/typography.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/typography.css",
    required_parts: TYPOGRAPHY_REQUIRED_PARTS,
    api: TYPOGRAPHY_API,
    parts: TYPOGRAPHY_PARTS,
    states: TYPOGRAPHY_STATES,
    styling: TYPOGRAPHY_STYLING,
};
