//! Component source embedded only for the installable gallery's generic API
//! reference fallback.

/// Returns the Rust source for one public component module.
pub fn source_for(module: &str) -> Option<&'static str> {
    Some(match module {
        "accordion" => include_str!("accordion.rs"),
        "alert" => include_str!("alert.rs"),
        "alert_dialog" => include_str!("alert_dialog.rs"),
        "autocomplete" => include_str!("autocomplete.rs"),
        "avatar" => include_str!("avatar.rs"),
        "badge" => include_str!("badge.rs"),
        "breadcrumbs" => include_str!("breadcrumbs.rs"),
        "button" => include_str!("button.rs"),
        "button_group" => include_str!("button_group.rs"),
        "calendar" => include_str!("calendar.rs"),
        "card" => include_str!("card.rs"),
        "checkbox" => include_str!("checkbox.rs"),
        "chip" => include_str!("chip.rs"),
        "close_button" => include_str!("close_button.rs"),
        "color_picker" => include_str!("color_picker.rs"),
        "combo_box" => include_str!("combo_box.rs"),
        "date_picker" => include_str!("date_picker.rs"),
        "disclosure" => include_str!("disclosure.rs"),
        "drawer" => include_str!("drawer.rs"),
        "dropdown" => include_str!("dropdown.rs"),
        "field" => include_str!("field.rs"),
        "form" => include_str!("form.rs"),
        "input" => include_str!("input.rs"),
        "input_group" => include_str!("input_group.rs"),
        "input_otp" => include_str!("input_otp.rs"),
        "kbd" => include_str!("kbd.rs"),
        "link" => include_str!("link.rs"),
        "list_box" => include_str!("list_box.rs"),
        "meter" => include_str!("meter.rs"),
        "modal" => include_str!("modal.rs"),
        "number_field" => include_str!("number_field.rs"),
        "pagination" => include_str!("pagination.rs"),
        "popover" => include_str!("popover.rs"),
        "progress" => include_str!("progress.rs"),
        "radio_group" => include_str!("radio_group.rs"),
        "range_calendar" => include_str!("range_calendar.rs"),
        "scroll_shadow" => include_str!("scroll_shadow.rs"),
        "select" => include_str!("select.rs"),
        "separator" => include_str!("separator.rs"),
        "skeleton" => include_str!("skeleton.rs"),
        "slider" => include_str!("slider.rs"),
        "spinner" => include_str!("spinner.rs"),
        "surface" => include_str!("surface.rs"),
        "switch" => include_str!("switch.rs"),
        "table" => include_str!("table.rs"),
        "tabs" => include_str!("tabs.rs"),
        "tag_group" => include_str!("tag_group.rs"),
        "textarea" => include_str!("textarea.rs"),
        "time_field" => include_str!("time_field.rs"),
        "toast" => include_str!("toast.rs"),
        "toggle_button" => include_str!("toggle_button.rs"),
        "toolbar" => include_str!("toolbar.rs"),
        "tooltip" => include_str!("tooltip.rs"),
        "typography" => include_str!("typography.rs"),
        _ => return None,
    })
}
