//! Checked-in, build-time reference data sourced from HeroUI v3.
//!
//! This module is intentionally data-only. A later metadata wave can add a
//! `ReferenceMetadata` value without changing the renderer in `reference.rs`.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ImplementationStatus {
    Implemented,
    Partial,
    Unavailable,
}

impl ImplementationStatus {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Implemented => "Implemented",
            Self::Partial => "Partial",
            Self::Unavailable => "Not ported",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ApiDoc {
    pub(crate) owner: &'static str,
    pub(crate) prop: &'static str,
    pub(crate) ty: &'static str,
    pub(crate) default: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct PartDoc {
    pub(crate) name: &'static str,
    pub(crate) slot: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StateDoc {
    pub(crate) state: &'static str,
    pub(crate) selector: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StyleDoc {
    pub(crate) class_or_token: &'static str,
    pub(crate) value: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ReferenceMetadata {
    pub(crate) page: &'static str,
    pub(crate) import_line: &'static str,
    pub(crate) source_module: &'static str,
    pub(crate) version: &'static str,
    pub(crate) docs_source: &'static str,
    pub(crate) api_source: &'static str,
    pub(crate) style_source: &'static str,
    pub(crate) required_parts: &'static [&'static str],
    pub(crate) api: &'static [ApiDoc],
    pub(crate) parts: &'static [PartDoc],
    pub(crate) states: &'static [StateDoc],
    pub(crate) styling: &'static [StyleDoc],
}

const DROPDOWN_REQUIRED_PARTS: &[&str] = &[
    "Dropdown",
    "Dropdown.Trigger",
    "Dropdown.Popover",
    "Dropdown.Menu",
    "Dropdown.Section",
    "Dropdown.Item",
    "Dropdown.ItemIndicator",
    "Dropdown.SubmenuIndicator",
    "Dropdown.SubmenuTrigger",
];

const DROPDOWN_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Dropdown",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the open state of the menu (controlled).",
        rust_owner: "Dropdown",
        rust: "is_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "defaultOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the default open state of the menu (uncontrolled).",
        rust_owner: "Dropdown",
        rust: "default_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "onOpenChange",
        ty: "(isOpen: boolean) => void",
        default: "—",
        description: "Handler called when the open state changes.",
        rust_owner: "Dropdown",
        rust: "on_open_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "trigger",
        ty: "\"press\" | \"longPress\"",
        default: "\"press\"",
        description: "The type of interaction that triggers the menu.",
        rust_owner: "Dropdown",
        rust: "trigger(DropdownTrigger)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Dropdown content.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the trigger.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Trigger content or a render function.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "placement",
        ty: "PopoverPlacement",
        default: "\"bottom\"",
        description: "Placement of the popover relative to the trigger.",
        rust_owner: "Dropdown",
        rust: "placement(DropdownPlacement)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the popover.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Content children rendered in the popover.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\" | \"none\"",
        default: "\"none\"",
        description: "Whether single or multiple selection is enabled.",
        rust_owner: "Menu",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "default_selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when the selection changes.",
        rust_owner: "Menu",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items.",
        rust_owner: "Menu",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onAction",
        ty: "(key: Key) => void",
        default: "—",
        description: "Handler called when an item is activated.",
        rust_owner: "Menu",
        rust: "on_action(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the menu.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Menu content.",
        rust_owner: "Menu",
        rust: "new(id, items)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "—",
        description: "Selection mode for items within this section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when section selection changes.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items in the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Section content.",
        rust_owner: "Menu",
        rust: "SectionLabel + items",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "id",
        ty: "Key",
        default: "—",
        description: "Unique identifier for the item.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "textValue",
        ty: "string",
        default: "—",
        description: "Text content used for typeahead.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "variant",
        ty: "\"default\" | \"danger\"",
        default: "\"default\"",
        description: "Visual variant of the item.",
        rust_owner: "MenuItem",
        rust: "danger()",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Item content or a render function.",
        rust_owner: "MenuItem",
        rust: "new(key, label) + item_content",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "type",
        ty: "\"checkmark\" | \"dot\"",
        default: "\"checkmark\"",
        description: "Type of selection indicator to display.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the indicator.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom indicator content or render function.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item selection is indeterminate.",
        rust_owner: "Menu",
        rust: "item_content(state.is_indeterminate)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item has focus.",
        rust_owner: "Menu",
        rust: "item_content(state.is_focused)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is disabled.",
        rust_owner: "Menu",
        rust: "item_content(state.is_disabled)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is being pressed.",
        rust_owner: "Menu",
        rust: "item_content(state.is_pressed)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu indicator.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom submenu indicator content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu trigger.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Submenu trigger content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Dropdown",
        slot: "root",
        description:
            "MenuTrigger wrapper that owns open state and composes the trigger and popover.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Trigger",
        slot: "dropdown-trigger",
        description: "Button or custom element that opens the menu.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Popover",
        slot: "dropdown-popover",
        description: "Floating panel positioned relative to the trigger.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Menu",
        slot: "dropdown-menu",
        description: "Scrollable menu container and selection owner.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Section",
        slot: "menu-section",
        description: "Grouped menu items with an optional header.",
        rust_owner: "Menu",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.Item",
        slot: "menu-item",
        description: "Focusable action or selectable menu row.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.ItemIndicator",
        slot: "menu-item-indicator",
        description: "Checkmark or dot selection marker.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.SubmenuIndicator",
        slot: "submenu-indicator",
        description: "Trailing chevron for an item that opens a submenu.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.SubmenuTrigger",
        slot: "dropdown-submenu-trigger",
        description: "Item wrapper that keeps the parent open while opening a child popover.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
];

const DROPDOWN_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".dropdown__trigger:hover / .menu-item[data-hovered]",
        description: "Pointer is over the trigger or a menu item.",
        rust: "track_interaction + theme hover",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: "[data-focus=\"true\"]",
        description: "Element owns keyboard focus.",
        rust: "FocusHandle / keyed menu focus",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus indicator is visible.",
        rust: "focus_handle + status-focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ":active / [data-pressed=\"true\"]",
        description: "Trigger or item is being activated.",
        rust: "track_interaction + scale",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: "[data-disabled=\"true\"] / aria-disabled",
        description: "Trigger or item cannot be activated.",
        rust: "disabled_keys + disabled row",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Selected",
        selector: "[data-selected=\"true\"] / aria-selected",
        description: "Item is selected in single or multiple mode.",
        rust: "selected_keys + selection_mode",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Entering",
        selector: ".dropdown__popover[data-entering]",
        description: "Popover is playing its enter transition.",
        rust: "overlay_phase::Entering",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Exiting",
        selector: ".dropdown__popover[data-exiting]",
        description: "Popover remains mounted while its exit transition plays.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".dropdown",
        value: "flex flex-col gap-1",
        description: "Root wrapper layout.",
        rust: "Dropdown root: flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value: "inline-block; outline-none; cursor-interactive",
        description: "Trigger base, cursor and focus surface.",
        rust: "Dropdown::render trigger_wrap + cursor_pointer",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value:
            "transform 250ms ease-out-quart; background 150ms ease-smooth; shadow 150ms ease-out",
        description: "Trigger interaction motion.",
        rust: "Dropdown::render trigger_wrap",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "max-w-48svw; md:min-w-55; bg-overlay; p-0; text-sm; shadow-overlay",
        description: "Popover dimensions, surface and overflow behavior.",
        rust: "placed_panel + overlay surface",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "border-radius: min(32px, var(--radius-3xl))",
        description: "Floating panel radius token.",
        rust: "util::overlay_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-entering]",
        value: "150ms ease-smooth fade-in-0 zoom-in-90 + placement slide",
        description: "Popover enter motion.",
        rust: "overlay_phase::Entering + placement",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-exiting]",
        value: "100ms ease-smooth zoom-out-95 fade-out",
        description: "Popover exit motion.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__menu",
        value: "relative flex w-full flex-col gap-0.5 overflow-clip p-1",
        description: "Menu layout and inset.",
        rust: "Menu root: flex_col + gap(px(2.)) + p(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu",
        value: "relative flex w-full flex-col gap-1 overflow-clip p-1",
        description: "Shared Menu base styles used by Dropdown.Menu.",
        rust: "Menu root",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "min-h-9; gap-3; rounded-2xl; px-2; py-1.5",
        description: "Standalone Menu row metrics: 36px minimum height, 12px gap, 16px radius, 8px horizontal inset, 6px vertical inset.",
        rust: "Menu::render row .px(px(8.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"dropdown-menu\"]",
        value: "p-1.5",
        description: "Dropdown composition overrides the menu inset to 6px.",
        rust: "Menu::render dropdown_composition .p(px(6.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"menu-item\"]",
        value: "px-2.5",
        description: "Dropdown composition overrides each row's horizontal inset to 10px.",
        rust: "Menu::render dropdown_composition .px(px(10.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "transform 250ms ease-out-quart; shadow 150ms ease-out",
        description: "Menu row interaction motion.",
        rust: "menu item press/hover motion",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-hovered]",
        value: "bg-default",
        description: "Hovered menu row surface.",
        rust: "theme hover background",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-pressed]",
        value: "transform: scale(0.98)",
        description: "Pressed menu row feedback.",
        rust: "press scale",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-disabled]",
        value: "status-disabled",
        description: "Disabled row treatment.",
        rust: "disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator",
        value: "absolute start-2; size-4; text-muted",
        description: "Selection indicator placement and size.",
        rust: "indicator slot",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator--submenu",
        value: "text-muted; svg size-3",
        description: "Submenu chevron styling.",
        rust: "submenu indicator",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".menu-item--danger",
        value: "indicator and label text-danger",
        description: "Danger item variant.",
        rust: "MenuItem::danger",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--ease-smooth / --ease-out-quart",
        value: "v3 motion curves",
        description: "Official v3 easing tokens used by trigger, popover and rows.",
        rust: "Curve constants",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--overlay / --shadow-overlay / --radius-3xl",
        value: "overlay surface tokens",
        description: "Official v3 floating-surface tokens.",
        rust: "active theme overlay tokens",
        status: ImplementationStatus::Implemented,
    },
];

pub(crate) const DROPDOWN: ReferenceMetadata = ReferenceMetadata {
    page: "Dropdown",
    import_line: "use herogpui::components::dropdown::{Dropdown, MenuItem};",
    source_module: "dropdown",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/dropdown.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/dropdown/dropdown.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/dropdown.css",
    required_parts: DROPDOWN_REQUIRED_PARTS,
    api: DROPDOWN_API,
    parts: DROPDOWN_PARTS,
    states: DROPDOWN_STATES,
    styling: DROPDOWN_STYLING,
};

const SLIDER_REQUIRED_PARTS: &[&str] = &[
    "Slider",
    "Label",
    "Slider.Output",
    "Slider.Track",
    "Slider.Fill",
    "Slider.Thumb",
];

const SLIDER_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Slider",
        prop: "value",
        ty: "number | number[]",
        default: "—",
        description: "The current value or values (controlled).",
        rust_owner: "Slider",
        rust: "value(f32) / values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "defaultValue",
        ty: "number | number[]",
        default: "—",
        description: "The initial value or values (uncontrolled).",
        rust_owner: "Slider",
        rust: "default_value(f32) / default_values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChange",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called whenever a thumb changes value.",
        rust_owner: "Slider",
        rust: "on_change(callback) / on_change_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChangeEnd",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called once when a drag or keyboard step completes.",
        rust_owner: "Slider",
        rust: "on_change_end(callback) / on_change_end_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "minValue",
        ty: "number",
        default: "0",
        description: "The minimum value.",
        rust_owner: "Slider",
        rust: "min_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "maxValue",
        ty: "number",
        default: "100",
        description: "The maximum value.",
        rust_owner: "Slider",
        rust: "max_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "step",
        ty: "number",
        default: "1",
        description: "The increment between valid values.",
        rust_owner: "Slider",
        rust: "step(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "formatOptions",
        ty: "Intl.NumberFormatOptions",
        default: "—",
        description: "Formats the displayed value; the port supports decimal, percent and currency without CLDR locale data.",
        rust_owner: "Slider",
        rust: "format_options(NumberFormat)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"horizontal\"",
        description: "The direction in which values increase.",
        rust_owner: "Slider",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables every thumb and removes the slider from the tab order.",
        rust_owner: "Slider",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-label",
        ty: "string",
        default: "—",
        description: "Accessible label for an otherwise unlabelled slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-labelledby",
        ty: "string",
        default: "—",
        description: "ID of the element that labels the slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the root.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Compound slider content; the monolithic port exposes its label, output and thumb customizations as builders.",
        rust_owner: "Slider",
        rust: "label(value)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the root DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the output.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom output content; the port currently provides only its formatted built-in output.",
        rust_owner: "Slider",
        rust: "show_value(bool)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the output DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the track.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Track content; the thumb closure receives each computed index and value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the track DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "style",
        ty: "CSSProperties",
        default: "—",
        description: "Inline styles for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "index",
        ty: "number",
        default: "0",
        description: "Index of the thumb within the slider.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables this thumb only and removes its form field and tab stop.",
        rust_owner: "Slider",
        rust: "disabled_keys(indices)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Name of this thumb's submitted form value.",
        rust_owner: "Slider",
        rust: "thumb_names(names)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the thumb.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom thumb content with its index and current value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the thumb DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "state",
        ty: "SliderState",
        default: "—",
        description: "Full slider state passed to Output and Track render functions.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "values",
        ty: "number[]",
        default: "—",
        description: "Values by thumb index; the thumb closure receives one index and value at a time.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "getThumbValueLabel",
        ty: "(index: number) => string",
        default: "—",
        description: "Returns the formatted label for a thumb.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "—",
        description: "Current orientation supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current disabled state supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const SLIDER_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Slider",
        slot: "slider",
        description: "Root value, form, pointer and keyboard state owner.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Optional text label rendered above or beside the track.",
        rust_owner: "Slider",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Slider.Output",
        slot: "slider-output",
        description: "Formatted current value; custom output content is not yet composable.",
        rust_owner: "Slider",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Slider.Track",
        slot: "slider-track",
        description: "Pointer and keyboard surface containing fill and thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Fill",
        slot: "slider-fill",
        description: "Accent span from the minimum or between the outermost thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Thumb",
        slot: "slider-thumb",
        description: "One draggable, focusable value handle per value.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Horizontal",
        selector: ".slider[data-orientation=\"horizontal\"]",
        description: "Values increase from left to right.",
        rust: "Orientation::Horizontal",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical",
        selector: ".slider[data-orientation=\"vertical\"]",
        description: "Values increase from bottom to top.",
        rust: "Orientation::Vertical",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".slider__thumb[data-focus-visible=\"true\"]",
        description: "The active enabled thumb carries the keyboard focus ring.",
        rust: "ring_if_focused + active_thumb",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Dragging",
        selector: ".slider__thumb[data-dragging=\"true\"]",
        description: "Pointer drag state updates the value and scales the inner thumb to 90%; gpui applies the scale without CSS's 250ms ramp.",
        rust: "DragState",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled slider",
        selector: ".slider[data-disabled=\"true\"]",
        description: "All thumbs are inert, dimmed and removed from form submission and tab order.",
        rust: "Slider::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled thumb",
        selector: ".slider__thumb[data-disabled=\"true\"]",
        description: "One thumb is inert and omitted while its siblings remain interactive.",
        rust: "Slider::disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill start",
        selector: ".slider__track[data-fill-start=\"true\"]",
        description: "The accent fill reaches the low edge.",
        rust: "fill_from == 0",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill end",
        selector: ".slider__track[data-fill-end=\"true\"]",
        description: "The accent fill reaches the high edge.",
        rust: "fill_to == 1",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".slider",
        value: "grid w-full gap-1",
        description: "Root layout with label and output above the track.",
        rust: "Slider::render flex_col + gap(px(4.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: "[data-slot=\"label\"] / .slider__output",
        value: "text-sm font-medium; output tabular-nums",
        description: "Label and output typography.",
        rust: "Slider::render text_size(px(14.)) + FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__track",
        value: "rounded-xl bg-default; horizontal h-5; vertical w-5",
        description: "Twenty-pixel track with transparent end borders for the thumb overhang.",
        rust: "20px default-color track + small_radius; no separate transparent end borders",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".slider__fill",
        value: "pointer-events-none absolute bg-accent",
        description: "Accent span representing the selected interval.",
        rust: "absolute accent fill from fill_from to fill_to",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb",
        value: "28x20 horizontal or 20x28 vertical outer pill; 24x16 or 16x24 inner pill",
        description: "Accent outer handle with accent-foreground inner handle.",
        rust: "28x20 / 20x28 outer + 24x16 / 16x24 inner",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-dragging=\"true\"]::after",
        value: "scale(0.9); 250ms ease-out; motion-reduce none",
        description: "Dragging feedback and reduced-motion override.",
        rust: "DragState inner geometry scale; instant under gpui",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-focus-visible=\"true\"]",
        value: "status-focused",
        description: "Keyboard focus treatment.",
        rust: "util::ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider[data-disabled=\"true\"]",
        value: "status-disabled; label opacity 100%",
        description: "Whole-slider disabled treatment.",
        rust: "layout.disabled_opacity",
        status: ImplementationStatus::Partial,
    },
];

pub(crate) const SLIDER: ReferenceMetadata = ReferenceMetadata {
    page: "Slider",
    import_line: "use herogpui::components::slider::Slider;",
    source_module: "slider",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(controls)/slider.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/slider/slider.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/slider.css",
    required_parts: SLIDER_REQUIRED_PARTS,
    api: SLIDER_API,
    parts: SLIDER_PARTS,
    states: SLIDER_STATES,
    styling: SLIDER_STYLING,
};

pub(crate) const ALL: &[ReferenceMetadata] = &[DROPDOWN, SLIDER];

pub(crate) fn for_import(import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.import_line == import_line)
}

#[cfg(test)]
pub(crate) fn for_route(page: &str, import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.page == page && metadata.import_line == import_line)
}
