//! Checked-in, build-time reference data sourced from HeroUI v3.
//!
//! This module is intentionally data-only. A later metadata wave can add a
//! `ReferenceMetadata` value without changing the renderer in `reference.rs`.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ImplementationStatus {
    Implemented,
    Partial,
    Unavailable,
}

impl ImplementationStatus {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Implemented => "Implemented",
            Self::Partial => "Partial",
            Self::Unavailable => "Not ported",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ApiDoc {
    pub(crate) owner: &'static str,
    pub(crate) prop: &'static str,
    pub(crate) ty: &'static str,
    pub(crate) default: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct PartDoc {
    pub(crate) name: &'static str,
    pub(crate) slot: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StateDoc {
    pub(crate) state: &'static str,
    pub(crate) selector: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StyleDoc {
    pub(crate) class_or_token: &'static str,
    pub(crate) value: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ReferenceMetadata {
    pub(crate) page: &'static str,
    pub(crate) import_line: &'static str,
    pub(crate) source_module: &'static str,
    pub(crate) version: &'static str,
    pub(crate) docs_source: &'static str,
    pub(crate) api_source: &'static str,
    pub(crate) style_source: &'static str,
    pub(crate) required_parts: &'static [&'static str],
    pub(crate) api: &'static [ApiDoc],
    pub(crate) parts: &'static [PartDoc],
    pub(crate) states: &'static [StateDoc],
    pub(crate) styling: &'static [StyleDoc],
}

const DROPDOWN_REQUIRED_PARTS: &[&str] = &[
    "Dropdown",
    "Dropdown.Trigger",
    "Dropdown.Popover",
    "Dropdown.Menu",
    "Dropdown.Section",
    "Dropdown.Item",
    "Dropdown.ItemIndicator",
    "Dropdown.SubmenuIndicator",
    "Dropdown.SubmenuTrigger",
];

const DROPDOWN_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Dropdown",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the open state of the menu (controlled).",
        rust_owner: "Dropdown",
        rust: "is_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "defaultOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the default open state of the menu (uncontrolled).",
        rust_owner: "Dropdown",
        rust: "default_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "onOpenChange",
        ty: "(isOpen: boolean) => void",
        default: "—",
        description: "Handler called when the open state changes.",
        rust_owner: "Dropdown",
        rust: "on_open_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "trigger",
        ty: "\"press\" | \"longPress\"",
        default: "\"press\"",
        description: "The type of interaction that triggers the menu.",
        rust_owner: "Dropdown",
        rust: "trigger(DropdownTrigger)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Dropdown content.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the trigger.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Trigger content or a render function.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "placement",
        ty: "PopoverPlacement",
        default: "\"bottom\"",
        description: "Placement of the popover relative to the trigger.",
        rust_owner: "Dropdown",
        rust: "placement(DropdownPlacement)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the popover.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Content children rendered in the popover.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\" | \"none\"",
        default: "\"none\"",
        description: "Whether single or multiple selection is enabled.",
        rust_owner: "Menu",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "default_selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when the selection changes.",
        rust_owner: "Menu",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items.",
        rust_owner: "Menu",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onAction",
        ty: "(key: Key) => void",
        default: "—",
        description: "Handler called when an item is activated.",
        rust_owner: "Menu",
        rust: "on_action(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the menu.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Menu content.",
        rust_owner: "Menu",
        rust: "new(id, items)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "—",
        description: "Selection mode for items within this section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when section selection changes.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items in the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Section content.",
        rust_owner: "Menu",
        rust: "SectionLabel + items",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "id",
        ty: "Key",
        default: "—",
        description: "Unique identifier for the item.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "textValue",
        ty: "string",
        default: "—",
        description: "Text content used for typeahead.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "variant",
        ty: "\"default\" | \"danger\"",
        default: "\"default\"",
        description: "Visual variant of the item.",
        rust_owner: "MenuItem",
        rust: "danger()",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Item content or a render function.",
        rust_owner: "MenuItem",
        rust: "new(key, label) + item_content",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "type",
        ty: "\"checkmark\" | \"dot\"",
        default: "\"checkmark\"",
        description: "Type of selection indicator to display.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the indicator.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom indicator content or render function.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item selection is indeterminate.",
        rust_owner: "Menu",
        rust: "item_content(state.is_indeterminate)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item has focus.",
        rust_owner: "Menu",
        rust: "item_content(state.is_focused)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is disabled.",
        rust_owner: "Menu",
        rust: "item_content(state.is_disabled)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is being pressed.",
        rust_owner: "Menu",
        rust: "item_content(state.is_pressed)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu indicator.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom submenu indicator content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu trigger.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Submenu trigger content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Dropdown",
        slot: "root",
        description:
            "MenuTrigger wrapper that owns open state and composes the trigger and popover.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Trigger",
        slot: "dropdown-trigger",
        description: "Button or custom element that opens the menu.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Popover",
        slot: "dropdown-popover",
        description: "Floating panel positioned relative to the trigger.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Menu",
        slot: "dropdown-menu",
        description: "Scrollable menu container and selection owner.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Section",
        slot: "menu-section",
        description: "Grouped menu items with an optional header.",
        rust_owner: "Menu",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.Item",
        slot: "menu-item",
        description: "Focusable action or selectable menu row.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.ItemIndicator",
        slot: "menu-item-indicator",
        description: "Checkmark or dot selection marker.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.SubmenuIndicator",
        slot: "submenu-indicator",
        description: "Trailing chevron for an item that opens a submenu.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.SubmenuTrigger",
        slot: "dropdown-submenu-trigger",
        description: "Item wrapper that keeps the parent open while opening a child popover.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
];

const DROPDOWN_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".dropdown__trigger:hover / .menu-item[data-hovered]",
        description: "Pointer is over the trigger or a menu item.",
        rust: "track_interaction + theme hover",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: "[data-focus=\"true\"]",
        description: "Element owns keyboard focus.",
        rust: "FocusHandle / keyed menu focus",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus indicator is visible.",
        rust: "focus_handle + status-focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ":active / [data-pressed=\"true\"]",
        description: "Trigger or item is being activated.",
        rust: "track_interaction + scale",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: "[data-disabled=\"true\"] / aria-disabled",
        description: "Trigger or item cannot be activated.",
        rust: "disabled_keys + disabled row",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Selected",
        selector: "[data-selected=\"true\"] / aria-selected",
        description: "Item is selected in single or multiple mode.",
        rust: "selected_keys + selection_mode",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Entering",
        selector: ".dropdown__popover[data-entering]",
        description: "Popover is playing its enter transition.",
        rust: "overlay_phase::Entering",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Exiting",
        selector: ".dropdown__popover[data-exiting]",
        description: "Popover remains mounted while its exit transition plays.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".dropdown",
        value: "flex flex-col gap-1",
        description: "Root wrapper layout.",
        rust: "Dropdown root: flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value: "inline-block; outline-none; cursor-interactive",
        description: "Trigger base, cursor and focus surface.",
        rust: "Dropdown::render trigger_wrap + cursor_pointer",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value:
            "transform 250ms ease-out-quart; background 150ms ease-smooth; shadow 150ms ease-out",
        description: "Trigger interaction motion.",
        rust: "Dropdown::render trigger_wrap",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "max-w-48svw; md:min-w-55; bg-overlay; p-0; text-sm; shadow-overlay",
        description: "Popover dimensions, surface and overflow behavior.",
        rust: "placed_panel + overlay surface",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "border-radius: min(32px, var(--radius-3xl))",
        description: "Floating panel radius token.",
        rust: "util::overlay_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-entering]",
        value: "150ms ease-smooth fade-in-0 zoom-in-90 + placement slide",
        description: "Popover enter motion.",
        rust: "overlay_phase::Entering + placement",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-exiting]",
        value: "100ms ease-smooth zoom-out-95 fade-out",
        description: "Popover exit motion.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__menu",
        value: "relative flex w-full flex-col gap-0.5 overflow-clip p-1",
        description: "Menu layout and inset.",
        rust: "Menu root: flex_col + gap(px(2.)) + p(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu",
        value: "relative flex w-full flex-col gap-1 overflow-clip p-1",
        description: "Shared Menu base styles used by Dropdown.Menu.",
        rust: "Menu root",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "min-h-9; gap-3; rounded-2xl; px-2; py-1.5",
        description: "Standalone Menu row metrics: 36px minimum height, 12px gap, 16px radius, 8px horizontal inset, 6px vertical inset.",
        rust: "Menu::render row .px(px(8.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"dropdown-menu\"]",
        value: "p-1.5",
        description: "Dropdown composition overrides the menu inset to 6px.",
        rust: "Menu::render dropdown_composition .p(px(6.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"menu-item\"]",
        value: "px-2.5",
        description: "Dropdown composition overrides each row's horizontal inset to 10px.",
        rust: "Menu::render dropdown_composition .px(px(10.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "transform 250ms ease-out-quart; shadow 150ms ease-out",
        description: "Menu row interaction motion.",
        rust: "menu item press/hover motion",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-hovered]",
        value: "bg-default",
        description: "Hovered menu row surface.",
        rust: "theme hover background",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-pressed]",
        value: "transform: scale(0.98)",
        description: "Pressed menu row feedback.",
        rust: "press scale",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-disabled]",
        value: "status-disabled",
        description: "Disabled row treatment.",
        rust: "disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator",
        value: "absolute start-2; size-4; text-muted",
        description: "Selection indicator placement and size.",
        rust: "indicator slot",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator--submenu",
        value: "text-muted; svg size-3",
        description: "Submenu chevron styling.",
        rust: "submenu indicator",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".menu-item--danger",
        value: "indicator and label text-danger",
        description: "Danger item variant.",
        rust: "MenuItem::danger",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--ease-smooth / --ease-out-quart",
        value: "v3 motion curves",
        description: "Official v3 easing tokens used by trigger, popover and rows.",
        rust: "Curve constants",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--overlay / --shadow-overlay / --radius-3xl",
        value: "overlay surface tokens",
        description: "Official v3 floating-surface tokens.",
        rust: "active theme overlay tokens",
        status: ImplementationStatus::Implemented,
    },
];

pub(crate) const DROPDOWN: ReferenceMetadata = ReferenceMetadata {
    page: "Dropdown",
    import_line: "use herogpui::components::dropdown::{Dropdown, MenuItem};",
    source_module: "dropdown",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/dropdown.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/dropdown/dropdown.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/dropdown.css",
    required_parts: DROPDOWN_REQUIRED_PARTS,
    api: DROPDOWN_API,
    parts: DROPDOWN_PARTS,
    states: DROPDOWN_STATES,
    styling: DROPDOWN_STYLING,
};

pub(crate) const ALL: &[ReferenceMetadata] = &[DROPDOWN];

pub(crate) fn for_import(import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.import_line == import_line)
}

#[cfg(test)]
pub(crate) fn for_route(page: &str, import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.page == page && metadata.import_line == import_line)
}
