//! Checked-in, build-time reference data sourced from HeroUI v3.
//!
//! This module is intentionally data-only. A later metadata wave can add a
//! `ReferenceMetadata` value without changing the renderer in `reference.rs`.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum ImplementationStatus {
    Implemented,
    Partial,
    Unavailable,
}

impl ImplementationStatus {
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::Implemented => "Implemented",
            Self::Partial => "Partial",
            Self::Unavailable => "Not ported",
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ApiDoc {
    pub(crate) owner: &'static str,
    pub(crate) prop: &'static str,
    pub(crate) ty: &'static str,
    pub(crate) default: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct PartDoc {
    pub(crate) name: &'static str,
    pub(crate) slot: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust_owner: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StateDoc {
    pub(crate) state: &'static str,
    pub(crate) selector: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct StyleDoc {
    pub(crate) class_or_token: &'static str,
    pub(crate) value: &'static str,
    pub(crate) description: &'static str,
    pub(crate) rust: &'static str,
    pub(crate) status: ImplementationStatus,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct ReferenceMetadata {
    pub(crate) page: &'static str,
    pub(crate) import_line: &'static str,
    pub(crate) source_module: &'static str,
    pub(crate) version: &'static str,
    pub(crate) docs_source: &'static str,
    pub(crate) api_source: &'static str,
    pub(crate) style_source: &'static str,
    pub(crate) required_parts: &'static [&'static str],
    pub(crate) api: &'static [ApiDoc],
    pub(crate) parts: &'static [PartDoc],
    pub(crate) states: &'static [StateDoc],
    pub(crate) styling: &'static [StyleDoc],
}

const DROPDOWN_REQUIRED_PARTS: &[&str] = &[
    "Dropdown",
    "Dropdown.Trigger",
    "Dropdown.Popover",
    "Dropdown.Menu",
    "Dropdown.Section",
    "Dropdown.Item",
    "Dropdown.ItemIndicator",
    "Dropdown.SubmenuIndicator",
    "Dropdown.SubmenuTrigger",
];

const DROPDOWN_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Dropdown",
        prop: "isOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the open state of the menu (controlled).",
        rust_owner: "Dropdown",
        rust: "is_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "defaultOpen",
        ty: "boolean",
        default: "—",
        description: "Sets the default open state of the menu (uncontrolled).",
        rust_owner: "Dropdown",
        rust: "default_open(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "onOpenChange",
        ty: "(isOpen: boolean) => void",
        default: "—",
        description: "Handler called when the open state changes.",
        rust_owner: "Dropdown",
        rust: "on_open_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "trigger",
        ty: "\"press\" | \"longPress\"",
        default: "\"press\"",
        description: "The type of interaction that triggers the menu.",
        rust_owner: "Dropdown",
        rust: "trigger(DropdownTrigger)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Dropdown content.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the trigger.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Trigger",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Trigger content or a render function.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "placement",
        ty: "PopoverPlacement",
        default: "\"bottom\"",
        description: "Placement of the popover relative to the trigger.",
        rust_owner: "Dropdown",
        rust: "placement(DropdownPlacement)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the popover.",
        rust_owner: "Dropdown",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Popover",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Content children rendered in the popover.",
        rust_owner: "Dropdown",
        rust: "new(id, trigger, items, is_open)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\" | \"none\"",
        default: "\"none\"",
        description: "Whether single or multiple selection is enabled.",
        rust_owner: "Menu",
        rust: "selection_mode(SelectionMode)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "default_selected_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when the selection changes.",
        rust_owner: "Menu",
        rust: "on_selection_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items.",
        rust_owner: "Menu",
        rust: "disabled_keys(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "onAction",
        ty: "(key: Key) => void",
        default: "—",
        description: "Handler called when an item is activated.",
        rust_owner: "Menu",
        rust: "on_action(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the menu.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Menu",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Menu content.",
        rust_owner: "Menu",
        rust: "new(id, items)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectionMode",
        ty: "\"single\" | \"multiple\"",
        default: "—",
        description: "Selection mode for items within this section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "selectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The currently selected keys (controlled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "defaultSelectedKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "The initial selected keys (uncontrolled).",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "onSelectionChange",
        ty: "(keys: Selection) => void",
        default: "—",
        description: "Handler called when section selection changes.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "disabledKeys",
        ty: "Iterable<Key>",
        default: "—",
        description: "Keys of disabled items in the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the section.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Section",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Section content.",
        rust_owner: "Menu",
        rust: "SectionLabel + items",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "id",
        ty: "Key",
        default: "—",
        description: "Unique identifier for the item.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "textValue",
        ty: "string",
        default: "—",
        description: "Text content used for typeahead.",
        rust_owner: "MenuItem",
        rust: "new(key, label)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "variant",
        ty: "\"default\" | \"danger\"",
        default: "\"default\"",
        description: "Visual variant of the item.",
        rust_owner: "MenuItem",
        rust: "danger()",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the item.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.Item",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Item content or a render function.",
        rust_owner: "MenuItem",
        rust: "new(key, label) + item_content",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "type",
        ty: "\"checkmark\" | \"dot\"",
        default: "\"checkmark\"",
        description: "Type of selection indicator to display.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the indicator.",
        rust_owner: "Menu",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom indicator content or render function.",
        rust_owner: "Menu",
        rust: "indicator(IndicatorKind)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.ItemIndicator",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item selection is indeterminate.",
        rust_owner: "Menu",
        rust: "item_content(state.is_indeterminate)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is selected.",
        rust_owner: "Menu",
        rust: "item_content(state.is_selected)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isFocused",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item has focus.",
        rust_owner: "Menu",
        rust: "item_content(state.is_focused)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is disabled.",
        rust_owner: "Menu",
        rust: "item_content(state.is_disabled)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.Item (render)",
        prop: "isPressed",
        ty: "boolean",
        default: "—",
        description: "Render-function state: whether the item is being pressed.",
        rust_owner: "Menu",
        rust: "item_content(state.is_pressed)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu indicator.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuIndicator",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom submenu indicator content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the submenu trigger.",
        rust_owner: "MenuItem",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Dropdown.SubmenuTrigger",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Submenu trigger content.",
        rust_owner: "MenuItem",
        rust: "submenu(items)",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Dropdown",
        slot: "root",
        description:
            "MenuTrigger wrapper that owns open state and composes the trigger and popover.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Trigger",
        slot: "dropdown-trigger",
        description: "Button or custom element that opens the menu.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Popover",
        slot: "dropdown-popover",
        description: "Floating panel positioned relative to the trigger.",
        rust_owner: "Dropdown",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Menu",
        slot: "dropdown-menu",
        description: "Scrollable menu container and selection owner.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.Section",
        slot: "menu-section",
        description: "Grouped menu items with an optional header.",
        rust_owner: "Menu",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.Item",
        slot: "menu-item",
        description: "Focusable action or selectable menu row.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.ItemIndicator",
        slot: "menu-item-indicator",
        description: "Checkmark or dot selection marker.",
        rust_owner: "Menu",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Dropdown.SubmenuIndicator",
        slot: "submenu-indicator",
        description: "Trailing chevron for an item that opens a submenu.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Dropdown.SubmenuTrigger",
        slot: "dropdown-submenu-trigger",
        description: "Item wrapper that keeps the parent open while opening a child popover.",
        rust_owner: "MenuItem",
        status: ImplementationStatus::Partial,
    },
];

const DROPDOWN_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Hovered",
        selector: ".dropdown__trigger:hover / .menu-item[data-hovered]",
        description: "Pointer is over the trigger or a menu item.",
        rust: "track_interaction + theme hover",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focused",
        selector: "[data-focus=\"true\"]",
        description: "Element owns keyboard focus.",
        rust: "FocusHandle / keyed menu focus",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ":focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus indicator is visible.",
        rust: "focus_handle + status-focused",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ":active / [data-pressed=\"true\"]",
        description: "Trigger or item is being activated.",
        rust: "track_interaction + scale",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: "[data-disabled=\"true\"] / aria-disabled",
        description: "Trigger or item cannot be activated.",
        rust: "disabled_keys + disabled row",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Selected",
        selector: "[data-selected=\"true\"] / aria-selected",
        description: "Item is selected in single or multiple mode.",
        rust: "selected_keys + selection_mode",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Entering",
        selector: ".dropdown__popover[data-entering]",
        description: "Popover is playing its enter transition.",
        rust: "overlay_phase::Entering",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Exiting",
        selector: ".dropdown__popover[data-exiting]",
        description: "Popover remains mounted while its exit transition plays.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
];

const DROPDOWN_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".dropdown",
        value: "flex flex-col gap-1",
        description: "Root wrapper layout.",
        rust: "Dropdown root: flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value: "inline-block; outline-none; cursor-interactive",
        description: "Trigger base, cursor and focus surface.",
        rust: "Dropdown::render trigger_wrap + cursor_pointer",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__trigger",
        value:
            "transform 250ms ease-out-quart; background 150ms ease-smooth; shadow 150ms ease-out",
        description: "Trigger interaction motion.",
        rust: "Dropdown::render trigger_wrap",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "max-w-48svw; md:min-w-55; bg-overlay; p-0; text-sm; shadow-overlay",
        description: "Popover dimensions, surface and overflow behavior.",
        rust: "placed_panel + overlay surface",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover",
        value: "border-radius: min(32px, var(--radius-3xl))",
        description: "Floating panel radius token.",
        rust: "util::overlay_radius",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-entering]",
        value: "150ms ease-smooth fade-in-0 zoom-in-90 + placement slide",
        description: "Popover enter motion.",
        rust: "overlay_phase::Entering + placement",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover[data-exiting]",
        value: "100ms ease-smooth zoom-out-95 fade-out",
        description: "Popover exit motion.",
        rust: "overlay_phase::Exiting",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__menu",
        value: "relative flex w-full flex-col gap-0.5 overflow-clip p-1",
        description: "Menu layout and inset.",
        rust: "Menu root: flex_col + gap(px(2.)) + p(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu",
        value: "relative flex w-full flex-col gap-1 overflow-clip p-1",
        description: "Shared Menu base styles used by Dropdown.Menu.",
        rust: "Menu root",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "min-h-9; gap-3; rounded-2xl; px-2; py-1.5",
        description: "Standalone Menu row metrics: 36px minimum height, 12px gap, 16px radius, 8px horizontal inset, 6px vertical inset.",
        rust: "Menu::render row .px(px(8.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"dropdown-menu\"]",
        value: "p-1.5",
        description: "Dropdown composition overrides the menu inset to 6px.",
        rust: "Menu::render dropdown_composition .p(px(6.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".dropdown__popover [data-slot=\"menu-item\"]",
        value: "px-2.5",
        description: "Dropdown composition overrides each row's horizontal inset to 10px.",
        rust: "Menu::render dropdown_composition .px(px(10.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item",
        value: "transform 250ms ease-out-quart; shadow 150ms ease-out",
        description: "Menu row interaction motion.",
        rust: "menu item press/hover motion",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-hovered]",
        value: "bg-default",
        description: "Hovered menu row surface.",
        rust: "theme hover background",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-pressed]",
        value: "transform: scale(0.98)",
        description: "Pressed menu row feedback.",
        rust: "press scale",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item[data-disabled]",
        value: "status-disabled",
        description: "Disabled row treatment.",
        rust: "disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator",
        value: "absolute start-2; size-4; text-muted",
        description: "Selection indicator placement and size.",
        rust: "indicator slot",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".menu-item__indicator--submenu",
        value: "text-muted; svg size-3",
        description: "Submenu chevron styling.",
        rust: "submenu indicator",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".menu-item--danger",
        value: "indicator and label text-danger",
        description: "Danger item variant.",
        rust: "MenuItem::danger",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--ease-smooth / --ease-out-quart",
        value: "v3 motion curves",
        description: "Official v3 easing tokens used by trigger, popover and rows.",
        rust: "Curve constants",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: "--overlay / --shadow-overlay / --radius-3xl",
        value: "overlay surface tokens",
        description: "Official v3 floating-surface tokens.",
        rust: "active theme overlay tokens",
        status: ImplementationStatus::Implemented,
    },
];

pub(crate) const DROPDOWN: ReferenceMetadata = ReferenceMetadata {
    page: "Dropdown",
    import_line: "use herogpui::components::dropdown::{Dropdown, MenuItem};",
    source_module: "dropdown",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(collections)/dropdown.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/dropdown/dropdown.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/dropdown.css",
    required_parts: DROPDOWN_REQUIRED_PARTS,
    api: DROPDOWN_API,
    parts: DROPDOWN_PARTS,
    states: DROPDOWN_STATES,
    styling: DROPDOWN_STYLING,
};

const SLIDER_REQUIRED_PARTS: &[&str] = &[
    "Slider",
    "Label",
    "Slider.Output",
    "Slider.Track",
    "Slider.Fill",
    "Slider.Thumb",
];

const SLIDER_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Slider",
        prop: "value",
        ty: "number | number[]",
        default: "—",
        description: "The current value or values (controlled).",
        rust_owner: "Slider",
        rust: "value(f32) / values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "defaultValue",
        ty: "number | number[]",
        default: "—",
        description: "The initial value or values (uncontrolled).",
        rust_owner: "Slider",
        rust: "default_value(f32) / default_values(values)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChange",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called whenever a thumb changes value.",
        rust_owner: "Slider",
        rust: "on_change(callback) / on_change_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "onChangeEnd",
        ty: "(value: number | number[]) => void",
        default: "—",
        description: "Handler called once when a drag or keyboard step completes.",
        rust_owner: "Slider",
        rust: "on_change_end(callback) / on_change_end_all(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "minValue",
        ty: "number",
        default: "0",
        description: "The minimum value.",
        rust_owner: "Slider",
        rust: "min_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "maxValue",
        ty: "number",
        default: "100",
        description: "The maximum value.",
        rust_owner: "Slider",
        rust: "max_value(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "step",
        ty: "number",
        default: "1",
        description: "The increment between valid values.",
        rust_owner: "Slider",
        rust: "step(f32)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "formatOptions",
        ty: "Intl.NumberFormatOptions",
        default: "—",
        description: "Formats the displayed value; the port supports decimal, percent and currency without CLDR locale data.",
        rust_owner: "Slider",
        rust: "format_options(NumberFormat)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"horizontal\"",
        description: "The direction in which values increase.",
        rust_owner: "Slider",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables every thumb and removes the slider from the tab order.",
        rust_owner: "Slider",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-label",
        ty: "string",
        default: "—",
        description: "Accessible label for an otherwise unlabelled slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "aria-labelledby",
        ty: "string",
        default: "—",
        description: "ID of the element that labels the slider.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the root.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Compound slider content; the monolithic port exposes its label, output and thumb customizations as builders.",
        rust_owner: "Slider",
        rust: "label(value)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the root DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the output.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom output content; the port currently provides only its formatted built-in output.",
        rust_owner: "Slider",
        rust: "show_value(bool)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider.Output",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the output DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the track.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Track content; the thumb closure receives each computed index and value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Slider.Track",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the track DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Fill",
        prop: "style",
        ty: "CSSProperties",
        default: "—",
        description: "Inline styles for the fill.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "index",
        ty: "number",
        default: "0",
        description: "Index of the thumb within the slider.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Disables this thumb only and removes its form field and tab stop.",
        rust_owner: "Slider",
        rust: "disabled_keys(indices)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Name of this thumb's submitted form value.",
        rust_owner: "Slider",
        rust: "thumb_names(names)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "className",
        ty: "string",
        default: "—",
        description: "Additional CSS classes for the thumb.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "children",
        ty: "ReactNode | RenderFunction",
        default: "—",
        description: "Custom thumb content with its index and current value.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Slider.Thumb",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the thumb DOM element.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "state",
        ty: "SliderState",
        default: "—",
        description: "Full slider state passed to Output and Track render functions.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "values",
        ty: "number[]",
        default: "—",
        description: "Values by thumb index; the thumb closure receives one index and value at a time.",
        rust_owner: "Slider",
        rust: "thumb(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "getThumbValueLabel",
        ty: "(index: number) => string",
        default: "—",
        description: "Returns the formatted label for a thumb.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "—",
        description: "Current orientation supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current disabled state supplied to a render function.",
        rust_owner: "Slider",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const SLIDER_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Slider",
        slot: "slider",
        description: "Root value, form, pointer and keyboard state owner.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Optional text label rendered above or beside the track.",
        rust_owner: "Slider",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Slider.Output",
        slot: "slider-output",
        description: "Formatted current value; custom output content is not yet composable.",
        rust_owner: "Slider",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Slider.Track",
        slot: "slider-track",
        description: "Pointer and keyboard surface containing fill and thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Fill",
        slot: "slider-fill",
        description: "Accent span from the minimum or between the outermost thumbs.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Slider.Thumb",
        slot: "slider-thumb",
        description: "One draggable, focusable value handle per value.",
        rust_owner: "Slider",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Horizontal",
        selector: ".slider[data-orientation=\"horizontal\"]",
        description: "Values increase from left to right.",
        rust: "Orientation::Horizontal",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical",
        selector: ".slider[data-orientation=\"vertical\"]",
        description: "Values increase from bottom to top.",
        rust: "Orientation::Vertical",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".slider__thumb[data-focus-visible=\"true\"]",
        description: "The active enabled thumb carries the keyboard focus ring.",
        rust: "ring_if_focused + active_thumb",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Dragging",
        selector: ".slider__thumb[data-dragging=\"true\"]",
        description: "Pointer drag state updates the value and scales the inner thumb to 90%; gpui applies the scale without CSS's 250ms ramp.",
        rust: "DragState",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled slider",
        selector: ".slider[data-disabled=\"true\"]",
        description: "All thumbs are inert, dimmed and removed from form submission and tab order.",
        rust: "Slider::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled thumb",
        selector: ".slider__thumb[data-disabled=\"true\"]",
        description: "One thumb is inert and omitted while its siblings remain interactive.",
        rust: "Slider::disabled_keys",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill start",
        selector: ".slider__track[data-fill-start=\"true\"]",
        description: "The accent fill reaches the low edge.",
        rust: "fill_from == 0",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Fill end",
        selector: ".slider__track[data-fill-end=\"true\"]",
        description: "The accent fill reaches the high edge.",
        rust: "fill_to == 1",
        status: ImplementationStatus::Implemented,
    },
];

const SLIDER_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".slider",
        value: "grid w-full gap-1",
        description: "Root layout with label and output above the track.",
        rust: "Slider::render flex_col + gap(px(4.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: "[data-slot=\"label\"] / .slider__output",
        value: "text-sm font-medium; output tabular-nums",
        description: "Label and output typography.",
        rust: "Slider::render text_size(px(14.)) + FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__track",
        value: "rounded-xl bg-default; horizontal h-5; vertical w-5",
        description: "Twenty-pixel track with transparent end borders for the thumb overhang.",
        rust: "20px default-color track + small_radius; no separate transparent end borders",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".slider__fill",
        value: "pointer-events-none absolute bg-accent",
        description: "Accent span representing the selected interval.",
        rust: "absolute accent fill from fill_from to fill_to",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb",
        value: "28x20 horizontal or 20x28 vertical outer pill; 24x16 or 16x24 inner pill",
        description: "Accent outer handle with accent-foreground inner handle.",
        rust: "28x20 / 20x28 outer + 24x16 / 16x24 inner",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-dragging=\"true\"]::after",
        value: "scale(0.9); 250ms ease-out; motion-reduce none",
        description: "Dragging feedback and reduced-motion override.",
        rust: "DragState inner geometry scale; instant under gpui",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".slider__thumb[data-focus-visible=\"true\"]",
        value: "status-focused",
        description: "Keyboard focus treatment.",
        rust: "util::ring_if_focused",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".slider[data-disabled=\"true\"]",
        value: "status-disabled; label opacity 100%",
        description: "Whole-slider disabled treatment.",
        rust: "layout.disabled_opacity",
        status: ImplementationStatus::Partial,
    },
];

pub(crate) const SLIDER: ReferenceMetadata = ReferenceMetadata {
    page: "Slider",
    import_line: "use herogpui::components::slider::Slider;",
    source_module: "slider",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(controls)/slider.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/slider/slider.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/slider.css",
    required_parts: SLIDER_REQUIRED_PARTS,
    api: SLIDER_API,
    parts: SLIDER_PARTS,
    states: SLIDER_STATES,
    styling: SLIDER_STYLING,
};

const CHECKBOX_REQUIRED_PARTS: &[&str] = &[
    "Checkbox",
    "Checkbox.Content",
    "Checkbox.Control",
    "Checkbox.Indicator",
    "Description",
    "FieldError",
];

const CHECKBOX_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "Checkbox",
        prop: "isSelected",
        ty: "boolean",
        default: "false",
        description: "Whether the checkbox is checked (controlled).",
        rust_owner: "Checkbox",
        rust: "is_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "defaultSelected",
        ty: "boolean",
        default: "false",
        description: "Whether the checkbox is checked initially (uncontrolled).",
        rust_owner: "Checkbox",
        rust: "default_selected(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "false",
        description: "Whether the checkbox displays the indeterminate mark.",
        rust_owner: "Checkbox",
        rust: "is_indeterminate(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables interaction, focus and form submission.",
        rust_owner: "Checkbox",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "isInvalid",
        ty: "boolean",
        default: "false",
        description: "Marks the checkbox invalid.",
        rust_owner: "Checkbox",
        rust: "is_invalid(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "isReadOnly",
        ty: "boolean",
        default: "false",
        description: "Keeps the checkbox focusable while preventing selection changes.",
        rust_owner: "Checkbox",
        rust: "is_read_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "isRequired",
        ty: "boolean",
        default: "false",
        description: "Requires the checkbox to be selected for native validation.",
        rust_owner: "Checkbox",
        rust: "is_required(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "validate",
        ty: "(value: boolean) => ValidationError | true | null | undefined",
        default: "—",
        description: "Custom validation function.",
        rust_owner: "Checkbox",
        rust: "validate(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "validationBehavior",
        ty: "\"native\" | \"aria\"",
        default: "\"native\"",
        description: "Whether invalid state blocks form submission or is announced only.",
        rust_owner: "Checkbox",
        rust: "validation_behavior(ValidationBehavior)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "variant",
        ty: "\"primary\" | \"secondary\"",
        default: "\"primary\"",
        description: "Primary field chrome or the flat surface treatment.",
        rust_owner: "Checkbox",
        rust: "variant(FieldVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Submitted form field name.",
        rust_owner: "Checkbox",
        rust: "name(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "value",
        ty: "string",
        default: "—",
        description: "Submitted value when selected.",
        rust_owner: "Checkbox",
        rust: "value(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "onChange",
        ty: "(isSelected: boolean) => void",
        default: "—",
        description: "Handler called when selection changes.",
        rust_owner: "Checkbox",
        rust: "on_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "children",
        ty: "ReactNode | CheckboxFieldRenderFunction",
        default: "—",
        description: "Compound field content; static children compose, but root render props are not handed over.",
        rust_owner: "Checkbox",
        rust: "label(element)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Checkbox",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the root DOM element.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Checkbox.Content",
        prop: "children",
        ty: "ReactNode | CheckboxButtonRenderFunction",
        default: "—",
        description: "Clickable control and label content; static content is composed by the monolithic row.",
        rust_owner: "Checkbox",
        rust: "label(element)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Checkbox.Content",
        prop: "className",
        ty: "string | CheckboxButtonClassNameFunction",
        default: "—",
        description: "Classes applied to the clickable label.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Current selected state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isIndeterminate",
        ty: "boolean",
        default: "—",
        description: "Current indeterminate state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current disabled state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isReadOnly",
        ty: "boolean",
        default: "—",
        description: "Current read-only state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isInvalid",
        ty: "boolean",
        default: "—",
        description: "Current invalid state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "CheckboxFieldRenderProps",
        prop: "isRequired",
        ty: "boolean",
        default: "—",
        description: "Current required state supplied to the root render function.",
        rust_owner: "Checkbox",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const CHECKBOX_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "Checkbox",
        slot: "checkbox",
        description: "Field root that owns value, validation, focus and form state.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Content",
        slot: "checkbox-content",
        description: "Clickable row containing the control and label.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Control",
        slot: "checkbox-control",
        description: "Focusable 16px selection box.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Indicator",
        slot: "checkbox-indicator",
        description: "Checkmark, indeterminate mark or caller-drawn indicator.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Description",
        slot: "description",
        description:
            "Optional field help text rendered as an indented sibling below the content row.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "FieldError",
        slot: "field-error",
        description: "Validation message rendered as an indented sibling below the content row.",
        rust_owner: "Checkbox",
        status: ImplementationStatus::Implemented,
    },
];

const CHECKBOX_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Selected",
        selector: ".checkbox[data-selected=\"true\"]",
        description: "Accent fill and checkmark are visible.",
        rust: "checked + accent control",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Indeterminate",
        selector: ".checkbox[data-indeterminate=\"true\"]",
        description: "Accent fill and dash indicator are visible.",
        rust: "is_indeterminate + dash",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Invalid",
        selector: ".checkbox[data-invalid=\"true\"]",
        description: "Danger treatment reflects controlled, server or custom validation.",
        rust: "validation::resolve + danger role",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ".checkbox:hover / [data-hovered=\"true\"]",
        description: "Active control uses the accent hover fill.",
        rust: "boxel.hover",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".checkbox:focus-visible / [data-focus-visible=\"true\"]",
        description: "Keyboard focus rings the control.",
        rust: "tab_stop_handle + with_focus_ring",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled",
        selector: ".checkbox[data-disabled=\"true\"]",
        description: "Control is dimmed, inert and outside the tab order.",
        rust: "is_disabled + disabled_opacity",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".checkbox:active / [data-pressed=\"true\"]",
        description: "Press activation toggles on Space or pointer release; v3 declares no additional pressed rule body.",
        rust: "on_click keyboard/pointer arbitration",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Read only",
        selector: "isReadOnly",
        description: "Control remains focusable but selection cannot change.",
        rust: "is_read_only gates activation only",
        status: ImplementationStatus::Implemented,
    },
];

const CHECKBOX_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".checkbox",
        value: "flex flex-col items-start gap-1",
        description: "Field root and sibling help/error layout.",
        rust: "Checkbox::render flex_col + items_start + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox__content",
        value: "inline-flex items-center gap-3 text-sm font-medium",
        description: "Clickable label row.",
        rust: "row gap(px(12.)) + text_size(px(14.)) + FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox__control",
        value: "size-4 rounded-md bg-field shadow-field",
        description: "Primary selection box metrics and field chrome.",
        rust: "16px + mark_radius + field background/shadow",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox__indicator",
        value: "relative z-10 flex size-3",
        description: "Indicator box and glyph size.",
        rust: "12px checkmark or dash",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox__control::before",
        value: "accent scale-70 opacity-0 -> scale-100 opacity-100; 100/200ms",
        description: "Selected background reveal.",
        rust: "selected accent fill swaps immediately",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".checkbox--secondary .checkbox__control",
        value: "shadow-none; background var(--default)",
        description: "Lower-emphasis surface variant.",
        rust: "FieldVariant::Secondary + colors.default.color",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox[data-disabled=\"true\"]",
        value: "status-disabled",
        description: "Disabled opacity and cursor treatment.",
        rust: "layout.disabled_opacity",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox[data-invalid=\"true\"]",
        value: "danger fill/checkmark or status-invalid-field",
        description: "Invalid selected and unselected treatments.",
        rust: "danger role + unchecked border",
        status: ImplementationStatus::Implemented,
    },
];

pub(crate) const CHECKBOX: ReferenceMetadata = ReferenceMetadata {
    page: "Checkbox",
    import_line: "use herogpui::components::checkbox::Checkbox;",
    source_module: "checkbox",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(forms)/checkbox.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/checkbox/checkbox.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/checkbox.css",
    required_parts: CHECKBOX_REQUIRED_PARTS,
    api: CHECKBOX_API,
    parts: CHECKBOX_PARTS,
    states: CHECKBOX_STATES,
    styling: CHECKBOX_STYLING,
};

const CHECKBOX_GROUP_REQUIRED_PARTS: &[&str] = &[
    "CheckboxGroup",
    "Label",
    "Description",
    "Checkbox",
    "Checkbox.Content",
    "Checkbox.Control",
    "Checkbox.Indicator",
    "FieldError",
];

const CHECKBOX_GROUP_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "value",
        ty: "string[]",
        default: "—",
        description: "Current selected values (controlled).",
        rust_owner: "CheckboxGroup",
        rust: "value(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "defaultValue",
        ty: "string[]",
        default: "—",
        description: "Initial selected values (uncontrolled).",
        rust_owner: "CheckboxGroup",
        rust: "default_value(keys)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "onChange",
        ty: "(value: string[]) => void",
        default: "—",
        description: "Handler called with the complete selected set.",
        rust_owner: "CheckboxGroup",
        rust: "on_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables every option and omits the group from form submission.",
        rust_owner: "CheckboxGroup",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "isRequired",
        ty: "boolean",
        default: "false",
        description: "Requires at least one enabled option to be selected.",
        rust_owner: "CheckboxGroup",
        rust: "is_required(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "isReadOnly",
        ty: "boolean",
        default: "false",
        description: "Keeps enabled options focusable while preventing changes.",
        rust_owner: "CheckboxGroup",
        rust: "is_read_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "isInvalid",
        ty: "boolean",
        default: "false",
        description: "Marks the group and every option invalid.",
        rust_owner: "CheckboxGroup",
        rust: "is_invalid(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Submitted form field name for the selected values.",
        rust_owner: "CheckboxGroup",
        rust: "name(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "children",
        ty: "ReactNode | CheckboxGroupRenderFunction",
        default: "—",
        description:
            "Compound group content; the port takes options plus label/description/error builders.",
        rust_owner: "CheckboxGroup",
        rust: "new(id, options)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "CheckboxGroup",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the group root DOM element.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "value",
        ty: "string[]",
        default: "—",
        description: "Current selection supplied to a group render function.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current disabled state supplied to a group render function.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isReadOnly",
        ty: "boolean",
        default: "—",
        description: "Current read-only state supplied to a group render function.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isInvalid",
        ty: "boolean",
        default: "—",
        description: "Current invalid state supplied to a group render function.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Render Props",
        prop: "isRequired",
        ty: "boolean",
        default: "—",
        description: "Current required state supplied to a group render function.",
        rust_owner: "CheckboxGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
];

const CHECKBOX_GROUP_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "CheckboxGroup",
        slot: "checkbox-group",
        description: "Group value, validation, form and option composition owner.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Group label with required, disabled and invalid state.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Description",
        slot: "description",
        description: "Optional group or per-option help text.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox",
        slot: "checkbox",
        description: "One generated checkbox per option.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Content",
        slot: "checkbox-content",
        description: "Option label and optional description content.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Control",
        slot: "checkbox-control",
        description: "Selection control inherited from Checkbox.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Checkbox.Indicator",
        slot: "checkbox-indicator",
        description: "Selection mark inherited from Checkbox.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "FieldError",
        slot: "field-error",
        description: "Group validation message rendered in place of the description.",
        rust_owner: "CheckboxGroup",
        status: ImplementationStatus::Implemented,
    },
];

const CHECKBOX_GROUP_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Disabled",
        selector: "isDisabled",
        description: "Every option is disabled and omitted from the successful form value.",
        rust: "CheckboxGroup::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Read only",
        selector: "isReadOnly",
        description: "Options remain focusable but cannot toggle.",
        rust: "CheckboxGroup::is_read_only -> Checkbox::is_read_only",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Invalid",
        selector: "isInvalid",
        description: "Danger treatment propagates to each option and the field error.",
        rust: "is_invalid + error_message",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Required",
        selector: "isRequired",
        description: "Native form validation requires one enabled selected value.",
        rust: "FormField::is_required",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Controlled",
        selector: "value",
        description:
            "The caller owns the selected set; callbacks report without mutating behind it.",
        rust: "util::controlled(Some(value))",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Uncontrolled",
        selector: "defaultValue",
        description: "The group owns and resets its keyed selected set.",
        rust: "util::controlled(None) + restore",
        status: ImplementationStatus::Implemented,
    },
];

const CHECKBOX_GROUP_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".checkbox-group",
        value: "flex flex-col",
        description: "Group root stacks label, options and help/error text.",
        rust: "CheckboxGroup::render flex_col + gap(px(16.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".checkbox-group [data-slot=\"checkbox\"]",
        value: "mt-4",
        description: "Sixteen-pixel spacing between option rows.",
        rust: "option list gap(px(16.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox",
        value: "gap-1 between content and per-option description",
        description: "Per-option label/help stack.",
        rust: "label_el flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".checkbox__content",
        value: "gap-3 text-sm font-medium",
        description: "Option control and text row.",
        rust: "Checkbox row",
        status: ImplementationStatus::Partial,
    },
];

pub(crate) const CHECKBOX_GROUP: ReferenceMetadata = ReferenceMetadata {
    page: "CheckboxGroup",
    import_line: "use herogpui::components::checkbox::CheckboxGroup;",
    source_module: "checkbox",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(forms)/checkbox-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/checkbox-group/checkbox-group.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/checkbox-group.css",
    required_parts: CHECKBOX_GROUP_REQUIRED_PARTS,
    api: CHECKBOX_GROUP_API,
    parts: CHECKBOX_GROUP_PARTS,
    states: CHECKBOX_GROUP_STATES,
    styling: CHECKBOX_GROUP_STYLING,
};

const RADIO_GROUP_REQUIRED_PARTS: &[&str] = &[
    "RadioGroup",
    "Label",
    "Description",
    "Radio",
    "Radio.Content",
    "Radio.Control",
    "Radio.Indicator",
    "FieldError",
];

const RADIO_GROUP_API: &[ApiDoc] = &[
    ApiDoc {
        owner: "RadioGroup",
        prop: "value",
        ty: "string",
        default: "—",
        description: "Current selected value (controlled).",
        rust_owner: "RadioGroup",
        rust: "value(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "defaultValue",
        ty: "string",
        default: "—",
        description: "Initial selected value (uncontrolled).",
        rust_owner: "RadioGroup",
        rust: "default_value(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "onChange",
        ty: "(value: string) => void",
        default: "—",
        description: "Handler called with the selected option value.",
        rust_owner: "RadioGroup",
        rust: "on_change(callback)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables every option and removes the group from the tab order.",
        rust_owner: "RadioGroup",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "isRequired",
        ty: "boolean",
        default: "false",
        description: "Requires one selected value for form submission.",
        rust_owner: "RadioGroup",
        rust: "is_required(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "isReadOnly",
        ty: "boolean",
        default: "false",
        description: "Keeps roving focus active while preventing value changes.",
        rust_owner: "RadioGroup",
        rust: "is_read_only(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "isInvalid",
        ty: "boolean",
        default: "false",
        description: "Marks the group and each radio control invalid.",
        rust_owner: "RadioGroup",
        rust: "is_invalid(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "variant",
        ty: "\"primary\" | \"secondary\"",
        default: "\"primary\"",
        description: "Primary field chrome or the flat surface treatment.",
        rust_owner: "RadioGroup",
        rust: "variant(FieldVariant)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Shared submitted name for the selected radio value.",
        rust_owner: "RadioGroup",
        rust: "name(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "orientation",
        ty: "\"horizontal\" | \"vertical\"",
        default: "\"vertical\"",
        description: "Layout and arrow-key orientation.",
        rust_owner: "RadioGroup",
        rust: "orientation(Orientation)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "children",
        ty: "ReactNode | RadioGroupRenderFunction",
        default: "—",
        description: "Compound label, description, radios and field error; root render props are not exposed as one closure.",
        rust_owner: "RadioGroup",
        rust: "new(id, options)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "RadioGroup",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the group DOM element.",
        rust_owner: "RadioGroup",
        rust: "—",
        status: ImplementationStatus::Unavailable,
    },
    ApiDoc {
        owner: "Radio",
        prop: "value",
        ty: "string",
        default: "—",
        description: "Submitted value independent of the visible label.",
        rust_owner: "RadioOption",
        rust: "value(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Radio",
        prop: "isDisabled",
        ty: "boolean",
        default: "false",
        description: "Disables one option and removes it from roving focus.",
        rust_owner: "RadioOption",
        rust: "is_disabled(bool)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Radio",
        prop: "name",
        ty: "string",
        default: "—",
        description: "Each option shares the group form name.",
        rust_owner: "RadioGroup",
        rust: "name(value)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Radio",
        prop: "children",
        ty: "ReactNode | RadioFieldRenderFunction",
        default: "—",
        description: "Static option labels and state-driven content are supported, but arbitrary part ordering is not.",
        rust_owner: "RadioGroup",
        rust: "option_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Radio",
        prop: "render",
        ty: "DOMRenderFunction",
        default: "—",
        description: "Overrides the radio field root.",
        rust_owner: "RadioGroup",
        rust: "option_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "Radio.Control",
        prop: "children",
        ty: "ReactNode",
        default: "—",
        description: "Custom content inside the control wrapper.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Radio.Indicator",
        prop: "children",
        ty: "ReactNode | RadioFieldRenderFunction",
        default: "—",
        description: "Custom indicator content receiving the option field state.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "Radio.Content",
        prop: "children",
        ty: "ReactNode | RadioButtonRenderFunction",
        default: "—",
        description: "Clickable control and label content; the port keeps the control first and customizes the label body.",
        rust_owner: "RadioGroup",
        rust: "option_content(render)",
        status: ImplementationStatus::Partial,
    },
    ApiDoc {
        owner: "RadioFieldRenderProps",
        prop: "isSelected",
        ty: "boolean",
        default: "—",
        description: "Current option selection supplied to a custom renderer.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioFieldRenderProps",
        prop: "isDisabled",
        ty: "boolean",
        default: "—",
        description: "Current option disabled state supplied to a custom renderer.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioFieldRenderProps",
        prop: "isReadOnly",
        ty: "boolean",
        default: "—",
        description: "Current group read-only state supplied to a custom renderer.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioFieldRenderProps",
        prop: "isInvalid",
        ty: "boolean",
        default: "—",
        description: "Resolved invalid state supplied to a custom renderer.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
    ApiDoc {
        owner: "RadioFieldRenderProps",
        prop: "isRequired",
        ty: "boolean",
        default: "—",
        description: "Current required state supplied to a custom renderer.",
        rust_owner: "RadioGroup",
        rust: "indicator(render)",
        status: ImplementationStatus::Implemented,
    },
];

const RADIO_GROUP_PARTS: &[PartDoc] = &[
    PartDoc {
        name: "RadioGroup",
        slot: "radio-group",
        description: "Single-selection, form, validation and roving-focus owner.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Label",
        slot: "label",
        description: "Optional group label with required and invalid state.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Description",
        slot: "description",
        description: "Group-level or per-option help text.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Radio",
        slot: "radio",
        description: "One option field with its own value and disabled state.",
        rust_owner: "RadioOption",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Radio.Content",
        slot: "radio-content",
        description: "Clickable row containing the control and label; arbitrary child ordering is not exposed.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Partial,
    },
    PartDoc {
        name: "Radio.Control",
        slot: "radio-control",
        description: "Focusable 16px selection control.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "Radio.Indicator",
        slot: "radio-indicator",
        description: "Built-in selected dot or caller-rendered indicator.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
    PartDoc {
        name: "FieldError",
        slot: "field-error",
        description: "Group-level or per-radio validation text outside clickable content.",
        rust_owner: "RadioGroup",
        status: ImplementationStatus::Implemented,
    },
];

const RADIO_GROUP_STATES: &[StateDoc] = &[
    StateDoc {
        state: "Selected",
        selector: ".radio[data-selected]",
        description: "Accent control and foreground indicator show the chosen option.",
        rust: "selected == Some(index)",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Hovered",
        selector: ".radio [data-slot=\"radio-content\"][data-hovered=\"true\"]",
        description: "v3 changes the unselected indicator fill and field border on hover; the port tracks hover for render props but does not reproduce every CSS layer.",
        rust: "util::track_interaction",
        status: ImplementationStatus::Partial,
    },
    StateDoc {
        state: "Focus visible",
        selector: ".radio [data-focus-visible=\"true\"]",
        description: "The roving keyboard stop rings the current control.",
        rust: "tab_stop_handle + with_focus_ring",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Pressed",
        selector: ".radio [data-pressed=\"true\"]",
        description: "The control shrinks to 95%, the selected fill hovers and the dot grows from 6px to 8px.",
        rust: "anim::pressed + interaction is_pressed",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled group",
        selector: "RadioGroup.isDisabled",
        description: "Every option is dimmed, inert and absent from the tab order.",
        rust: "RadioGroup::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Disabled option",
        selector: "Radio.isDisabled",
        description: "One option is dimmed and skipped by pointer and arrow navigation.",
        rust: "RadioOption::is_disabled",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Read only",
        selector: "RadioGroup.isReadOnly",
        description: "Arrows move focus while selection remains unchanged.",
        rust: "is_read_only gates selection after cursor movement",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Invalid",
        selector: ".radio[data-invalid=\"true\"]",
        description: "Controlled or message-derived invalid state outlines every control and displays the group error.",
        rust: "is_invalid || error_message.is_some()",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Vertical",
        selector: ".radio-group[data-orientation=\"vertical\"]",
        description: "Options stack and all four radio arrows rove through them.",
        rust: "Orientation::Vertical",
        status: ImplementationStatus::Implemented,
    },
    StateDoc {
        state: "Horizontal",
        selector: ".radio-group[data-orientation=\"horizontal\"]",
        description: "Options wrap in a row while radio-group arrows retain React Aria's four-arrow contract.",
        rust: "Orientation::Horizontal",
        status: ImplementationStatus::Implemented,
    },
];

const RADIO_GROUP_STYLING: &[StyleDoc] = &[
    StyleDoc {
        class_or_token: ".radio-group",
        value: "flex flex-col",
        description: "Group root around label, description, options and field error.",
        rust: "RadioGroup::render root flex_col + gap(px(4.))",
        status: ImplementationStatus::Partial,
    },
    StyleDoc {
        class_or_token: ".radio-group[data-orientation=\"vertical\"] [data-slot=\"radio\"]",
        value: "mt-4",
        description: "Sixteen-pixel vertical option spacing.",
        rust: "vertical group gap(px(16.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio-group[data-orientation=\"horizontal\"]",
        value: "flex-row flex-wrap gap-4",
        description: "Wrapping horizontal option row.",
        rust: "flex + items_center + flex_wrap + gap(px(16.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio",
        value: "flex flex-col items-start gap-1",
        description: "Option root with sibling description.",
        rust: "per-option flex_col + gap(px(4.))",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio > [data-slot=\"description\"]",
        value: "w-full ps-7 text-xs text-muted",
        description: "Help text aligned under the label at 28px logical-start padding.",
        rust: "pl(circle + gap) + Description",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio__content",
        value: "inline-flex items-center gap-3 text-sm font-medium",
        description: "Clickable control and label row.",
        rust: "gap(px(12.)) + text_size(px(14.)) + FontWeight::MEDIUM",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio__control",
        value: "size-4 rounded-lg bg-field shadow-field",
        description: "Primary selection box and field chrome.",
        rust: "16px + key_radius + field background/shadow",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio__indicator",
        value: "inset-0; selected 6px, pressed 8px",
        description: "Built-in foreground dot geometry.",
        rust: "dot px(6.) / pressed px(8.)",
        status: ImplementationStatus::Implemented,
    },
    StyleDoc {
        class_or_token: ".radio-group--secondary .radio__control",
        value: "shadow-none; background var(--default)",
        description: "Lower-emphasis surface variant.",
        rust: "FieldVariant::Secondary + colors.default.color",
        status: ImplementationStatus::Implemented,
    },
];

pub(crate) const RADIO_GROUP: ReferenceMetadata = ReferenceMetadata {
    page: "RadioGroup",
    import_line: "use herogpui::components::radio_group::RadioGroup;",
    source_module: "radio_group",
    version: "3.2.4",
    docs_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/apps/docs/content/docs/en/react/components/(forms)/radio-group.mdx",
    api_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/react/src/components/radio-group/radio-group.tsx",
    style_source: "https://github.com/heroui-inc/heroui/blob/v3.2.4/packages/styles/components/radio-group.css",
    required_parts: RADIO_GROUP_REQUIRED_PARTS,
    api: RADIO_GROUP_API,
    parts: RADIO_GROUP_PARTS,
    states: RADIO_GROUP_STATES,
    styling: RADIO_GROUP_STYLING,
};

pub(crate) const ALL: &[ReferenceMetadata] =
    &[DROPDOWN, SLIDER, CHECKBOX, CHECKBOX_GROUP, RADIO_GROUP];

pub(crate) fn for_import(import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.import_line == import_line)
}

#[cfg(test)]
pub(crate) fn for_route(page: &str, import_line: &str) -> Option<&'static ReferenceMetadata> {
    ALL.iter()
        .find(|metadata| metadata.page == page && metadata.import_line == import_line)
}
